import { montar } from './montar';

/** Arte, Mitologia e Religião — 100 perguntas (20 por nível). */
export const perguntasArteMitologia = montar('arte-mitologia', {
  1: [
    ['Quem pintou a Mona Lisa?', ['Van Gogh', 'Picasso', 'Leonardo da Vinci', 'Michelangelo'], 2, 'A pintura foi feita por volta de 1503 e mede apenas 77 por 53 centímetros.'],
    ['Em qual museu está exposta a Mona Lisa?', ['Louvre', 'Museu do Prado', 'MoMA', 'Galeria Uffizi'], 0, 'O quadro fica em Paris, protegido por um vidro à prova de balas.'],
    ['Quem pintou o teto da Capela Sistina?', ['Rafael', 'Michelangelo', 'Donatello', 'Caravaggio'], 1, 'Ele passou quatro anos deitado em andaimes para concluir a obra.'],
    ['Qual pintor holandês cortou a própria orelha?', ['Rembrandt', 'Vermeer', 'Mondrian', 'Van Gogh'], 3, 'Ele vendeu pouquíssimos quadros em vida e hoje é um dos mais valorizados do mundo.'],
    ['Quem é o rei dos deuses no Olimpo grego?', ['Zeus', 'Poseidon', 'Hades', 'Apolo'], 0, 'Seu símbolo é o raio, e ele comanda o céu e as tempestades.'],
    ['Qual é o deus grego dos mares?', ['Zeus', 'Ares', 'Hermes', 'Poseidon'], 3, 'Ele carrega um tridente e é irmão de Zeus e Hades.'],
    ['Qual religião tem a Bíblia como livro sagrado?', ['islamismo', 'hinduísmo', 'cristianismo', 'budismo'], 2, 'A Bíblia se divide em Antigo e Novo Testamento.'],
    ['Qual é o livro sagrado do islamismo?', ['Torá', 'Alcorão', 'Bíblia', 'Vedas'], 1, 'Os muçulmanos acreditam que o texto foi revelado a Maomé pelo anjo Gabriel.'],
    ['Quem é considerado o fundador do budismo?', ['Confúcio', 'Lao-Tsé', 'Maomé', 'Buda'], 3, 'Sidarta Gautama viveu na Índia por volta do século V a.C.'],
    ['Como se chama a pintura feita sobre reboco de parede ainda úmido?', ['aquarela', 'afresco', 'óleo sobre tela', 'guache'], 1, 'A técnica foi muito usada no Renascimento italiano.'],
    ['Qual escultura de Michelangelo está exposta em Florença?', ['Davi', 'O Pensador', 'Vênus de Milo', 'O Beijo'], 0, 'A estátua de mármore tem mais de cinco metros de altura.'],
    ['Quem pintou "A Noite Estrelada"?', ['Claude Monet', 'Paul Gauguin', 'Vincent van Gogh', 'Paul Cézanne'], 2, 'Ele pintou a obra em 1889, enquanto estava internado em um hospital psiquiátrico.'],
    ['Qual deus romano corresponde ao grego Zeus?', ['Marte', 'Júpiter', 'Netuno', 'Mercúrio'], 1, 'Marte corresponde a Ares, e Netuno, a Poseidon.'],
    ['Qual é a religião com mais seguidores no Brasil?', ['espiritismo', 'islamismo', 'cristianismo', 'umbanda'], 2, 'Somando católicos e evangélicos, os cristãos são a ampla maioria da população.'],
    ['Qual artista brasileira pintou o "Abaporu"?', ['Anita Malfatti', 'Di Cavalcanti', 'Candido Portinari', 'Tarsila do Amaral'], 3, 'A tela de 1928 inspirou o Manifesto Antropófago.'],
    ['Qual pintura retrata a última refeição de Jesus com os apóstolos?', ['A Última Ceia', 'A Criação de Adão', 'O Juízo Final', 'A Anunciação'], 0, 'O mural de Leonardo da Vinci está em um convento de Milão.'],
    ['Qual instrumento é associado ao deus grego Apolo?', ['lira', 'tambor', 'trompa', 'pandeiro'], 0, 'Apolo é o deus da música, da poesia e das artes.'],
    ['Qual cor se obtém misturando azul e amarelo?', ['roxo', 'laranja', 'verde', 'marrom'], 2, 'Azul, amarelo e vermelho são as cores primárias na pintura.'],
    ['Qual pintor espanhol criou o cubismo ao lado de Georges Braque?', ['Salvador Dalí', 'Pablo Picasso', 'Joan Miró', 'Francisco de Goya'], 1, 'O cubismo mostra o mesmo objeto de vários ângulos ao mesmo tempo.'],
    ['Qual estátua grega sem braços é um dos destaques do Louvre?', ['Nike de Samotrácia', 'Discóbolo', 'Laocoonte', 'Vênus de Milo'], 3, 'Ela foi encontrada em 1820 na ilha grega de Milo.'],
  ],
  2: [
    ['Qual movimento artístico é representado por Salvador Dalí?', ['cubismo', 'surrealismo', 'impressionismo', 'expressionismo'], 1, 'O surrealismo explorava sonhos e o inconsciente.'],
    ['Qual quadro deu nome ao movimento impressionista?', ['Almoço na Relva', 'Bailarinas', 'Le Moulin de la Galette', 'Impressão, Nascer do Sol'], 3, 'A obra é de Claude Monet, pintada em 1872.'],
    ['Qual escultor francês criou "O Pensador"?', ['Auguste Rodin', 'Camille Claudel', 'Constantin Brancusi', 'Alberto Giacometti'], 0, 'A escultura fazia parte de um portal inspirado na "Divina Comédia".'],
    ['Quem é a deusa grega da sabedoria?', ['Hera', 'Afrodite', 'Atena', 'Ártemis'], 2, 'Ela nasceu da cabeça de Zeus e é a padroeira de Atenas.'],
    ['Quem é o deus grego do mundo dos mortos?', ['Zeus', 'Apolo', 'Hefesto', 'Hades'], 3, 'Ele governa o submundo ao lado de Perséfone.'],
    ['Qual herói grego tinha o calcanhar como único ponto vulnerável?', ['Hércules', 'Aquiles', 'Ulisses', 'Perseu'], 1, 'A expressão "calcanhar de Aquiles" virou sinônimo de ponto fraco.'],
    ['Qual criatura mitológica tem cabeça de touro e corpo de homem?', ['centauro', 'ciclope', 'minotauro', 'sátiro'], 2, 'Ela vivia no labirinto construído por Dédalo, em Creta.'],
    ['Quantos trabalhos Hércules precisou cumprir?', ['12', '10', '7', '9'], 0, 'Entre eles, matar a Hidra de Lerna e capturar o leão de Nemeia.'],
    ['Qual religião de matriz africana cultua orixás no Brasil?', ['candomblé', 'xintoísmo', 'taoismo', 'siquismo'], 0, 'Ela chegou ao país com africanos escravizados, sobretudo na Bahia.'],
    ['Qual orixá está associado ao ferro, à guerra e às estradas?', ['Oxum', 'Iemanjá', 'Ogum', 'Oxóssi'], 2, 'No sincretismo, costuma ser associado a São Jorge.'],
    ['Qual orixá é associada ao mar?', ['Oxum', 'Iansã', 'Nanã', 'Iemanjá'], 3, 'Em 2 de fevereiro, milhares de fiéis levam oferendas ao mar em sua homenagem.'],
    ['Quantos mandamentos Moisés recebeu, segundo a tradição bíblica?', ['5', '10', '7', '12'], 1, 'Segundo a Bíblia, foram entregues em tábuas de pedra no monte Sinai.'],
    ['Qual cidade sagrada do islamismo recebe a peregrinação anual dos fiéis?', ['Jerusalém', 'Medina', 'Meca', 'Bagdá'], 2, 'A peregrinação, chamada hajj, é um dos cinco pilares do islamismo.'],
    ['Qual festa cristã celebra a ressurreição de Jesus?', ['Páscoa', 'Natal', 'Pentecostes', 'Advento'], 0, 'A data é móvel e definida pelo calendário lunar.'],
    ['Qual é o principal livro sagrado do judaísmo?', ['Alcorão', 'Torá', 'Vedas', 'Bhagavad Gita'], 1, 'A Torá corresponde aos cinco primeiros livros da Bíblia hebraica.'],
    ['Qual religião tem a roda do darma como símbolo?', ['judaísmo', 'islamismo', 'cristianismo', 'budismo'], 3, 'Os oito raios representam o caminho óctuplo ensinado por Buda.'],
    ['Qual estilo arquitetônico marca as catedrais medievais com arcos ogivais e vitrais?', ['românico', 'barroco', 'neoclássico', 'gótico'], 3, 'Notre-Dame de Paris é um dos exemplos mais famosos.'],
    ['Qual pintor brasileiro é autor de "Os Retirantes"?', ['Di Cavalcanti', 'Candido Portinari', 'Alfredo Volpi', 'Anita Malfatti'], 1, 'A obra de 1944 retrata uma família fugindo da seca no Nordeste.'],
    ['Quem foi o grande mestre do barroco mineiro, autor dos profetas de Congonhas?', ['Aleijadinho', 'Mestre Valentim', 'Vítor Meireles', 'Almeida Júnior'], 0, 'Antônio Francisco Lisboa esculpiu mesmo depois de perder o movimento das mãos.'],
    ['Quem pintou o quadro "Independência ou Morte"?', ['Vítor Meireles', 'Almeida Júnior', 'Pedro Américo', 'Rodolfo Amoedo'], 2, 'A tela de 1888 idealiza a cena do Grito do Ipiranga.'],
  ],
  3: [
    ['Qual pintor renascentista criou "A Escola de Atenas"?', ['Rafael Sanzio', 'Michelangelo', 'Botticelli', 'Ticiano'], 0, 'O afresco está nos aposentos do Vaticano e reúne filósofos da Antiguidade.'],
    ['Quem pintou "O Nascimento de Vênus"?', ['Ticiano', 'Caravaggio', 'Sandro Botticelli', 'Giotto'], 2, 'A obra de 1485 é um dos símbolos do Renascimento florentino.'],
    ['Qual movimento rompeu com a figuração e deu origem à arte abstrata?', ['cubismo', 'fauvismo', 'dadaísmo', 'abstracionismo'], 3, 'Kandinsky é apontado como autor da primeira aquarela abstrata, em 1910.'],
    ['Quem apresentou um urinol assinado como obra de arte, marco do dadaísmo?', ['Man Ray', 'Marcel Duchamp', 'Tristan Tzara', 'Kurt Schwitters'], 1, 'A peça, de 1917, se chama "A Fonte" e questiona o que define a arte.'],
    ['Qual artista americano ficou famoso pelas latas de sopa Campbell?', ['Jackson Pollock', 'Roy Lichtenstein', 'Andy Warhol', 'Keith Haring'], 2, 'Ele é o maior nome da pop art, que usava imagens do consumo de massa.'],
    ['Qual pintora mexicana ficou conhecida por seus autorretratos intensos?', ['Frida Kahlo', 'Remedios Varo', 'Leonora Carrington', 'María Izquierdo'], 0, 'Um grave acidente de ônibus marcou sua vida e sua obra.'],
    ['Qual obra de Picasso retrata o bombardeio de uma cidade basca?', ['As Meninas', 'Guernica', 'Les Demoiselles d’Avignon', 'O Velho Guitarrista'], 1, 'O painel de 1937 denuncia o ataque aéreo durante a Guerra Civil Espanhola.'],
    ['Qual deus egípcio tem cabeça de chacal e guia os mortos?', ['Rá', 'Hórus', 'Osíris', 'Anúbis'], 3, 'Ele presidia a mumificação e a pesagem do coração.'],
    ['Qual deus egípcio representa o Sol?', ['Osíris', 'Rá', 'Seth', 'Thot'], 1, 'Os faraós se consideravam filhos dele.'],
    ['Qual deus nórdico é o pai de Thor?', ['Loki', 'Balder', 'Heimdall', 'Odin'], 3, 'Ele sacrificou um olho em troca de sabedoria.'],
    ['Qual é o nome do martelo de Thor?', ['Gungnir', 'Gram', 'Mjolnir', 'Skofnung'], 2, 'Segundo os mitos, só quem fosse digno poderia erguê-lo.'],
    ['Qual é o salão dos guerreiros mortos na mitologia nórdica?', ['Valhala', 'Asgard', 'Midgard', 'Niflheim'], 0, 'As valquírias escolhiam quem seria levado para lá.'],
    ['Qual personagem grego foi condenado a empurrar eternamente uma pedra morro acima?', ['Tântalo', 'Prometeu', 'Ícaro', 'Sísifo'], 3, 'A pedra sempre rolava de volta pouco antes do topo.'],
    ['Quem teve o fígado devorado diariamente por uma águia após roubar o fogo dos deuses?', ['Atlas', 'Prometeu', 'Sísifo', 'Narciso'], 1, 'Ele entregou o fogo à humanidade, contrariando Zeus.'],
    ['Qual personagem mitológico se apaixonou pelo próprio reflexo?', ['Narciso', 'Adônis', 'Eros', 'Ganimedes'], 0, 'A flor narciso e o termo narcisismo vêm dessa história.'],
    ['Qual lenda brasileira fala de um menino de uma perna só com gorro vermelho?', ['Curupira', 'Boitatá', 'Saci-Pererê', 'Caipora'], 2, 'Ele adora pregar peças e viaja dentro de redemoinhos.'],
    ['Qual lenda amazônica conta que um animal vira rapaz nas festas ribeirinhas?', ['Iara', 'Mapinguari', 'Boto-cor-de-rosa', 'Cuca'], 2, 'A lenda costuma explicar gravidezes sem pai conhecido nas comunidades.'],
    ['Qual figura do folclore brasileiro encanta pescadores com seu canto?', ['Iara', 'Cuca', 'Mula sem cabeça', 'Caipora'], 0, 'A mãe-d’água é a versão brasileira das sereias europeias.'],
    ['Qual movimento artístico distorce formas para expressar emoções intensas?', ['realismo', 'impressionismo', 'cubismo', 'expressionismo'], 3, 'Surgiu na Alemanha no início do século XX.'],
    ['Qual obra de Edvard Munch mostra uma figura gritando sobre uma ponte?', ['A Dança da Vida', 'O Grito', 'Melancolia', 'Madonna'], 1, 'Existem quatro versões da obra feitas pelo próprio artista.'],
  ],
  4: [
    ['Qual técnica de pintura usa pigmentos diluídos em água sobre papel?', ['têmpera', 'encáustica', 'óleo sobre tela', 'aquarela'], 3, 'A transparência das camadas é a marca registrada da técnica.'],
    ['Qual pintor holandês é autor de "A Ronda Noturna"?', ['Johannes Vermeer', 'Rembrandt', 'Peter Paul Rubens', 'Frans Hals'], 1, 'A tela de 1642 é o maior tesouro do Rijksmuseum, em Amsterdã.'],
    ['Qual pintor barroco italiano é célebre pelos contrastes violentos de luz e sombra?', ['Ticiano', 'Tintoretto', 'Caravaggio', 'Veronese'], 2, 'Sua vida foi tão dramática quanto sua obra: ele morreu foragido por homicídio.'],
    ['Como se chama a técnica de contraste intenso entre luz e sombra?', ['claro-escuro', 'sfumato', 'pontilhismo', 'impasto'], 0, 'Em italiano, o termo é "chiaroscuro".'],
    ['Qual técnica de Leonardo da Vinci suaviza contornos com camadas quase invisíveis?', ['tenebrismo', 'sfumato', 'grafismo', 'têmpera'], 1, 'O efeito dá à Mona Lisa aquele sorriso ambíguo.'],
    ['Qual movimento usa pequenos pontos de cores puras justapostas?', ['fauvismo', 'futurismo', 'pontilhismo', 'construtivismo'], 2, 'Georges Seurat é seu principal representante.'],
    ['Qual arquiteto projetou a basílica da Sagrada Família, em Barcelona?', ['Antoni Gaudí', 'Santiago Calatrava', 'Frank Gehry', 'Le Corbusier'], 0, 'As obras começaram em 1882 e seguem em andamento até hoje.'],
    ['Qual arquiteto formulou os "cinco pontos da arquitetura moderna"?', ['Mies van der Rohe', 'Walter Gropius', 'Frank Lloyd Wright', 'Le Corbusier'], 3, 'Entre eles estão os pilotis e o terraço-jardim.'],
    ['Qual escola alemã dos anos 1920 uniu arte, artesanato e indústria?', ['Art Nouveau', 'De Stijl', 'Bauhaus', 'Secessão Vienense'], 2, 'Fechada pelos nazistas em 1933, influenciou o design no mundo inteiro.'],
    ['Qual movimento brasileiro propunha "devorar" influências estrangeiras?', ['Antropofagia', 'Concretismo', 'Neoconcretismo', 'Tropicalismo'], 0, 'O manifesto de Oswald de Andrade é de 1928.'],
    ['Qual artista participou da Semana de 22 e pintou "A Boba"?', ['Tarsila do Amaral', 'Anita Malfatti', 'Zina Aita', 'Regina Gomide Graz'], 1, 'Sua exposição de 1917 provocou uma crítica ferrenha de Monteiro Lobato.'],
    ['Qual artista brasileira criou os "Bichos", esculturas articuladas do neoconcretismo?', ['Tomie Ohtake', 'Fayga Ostrower', 'Maria Martins', 'Lygia Clark'], 3, 'As obras precisam ser manipuladas pelo público para se completar.'],
    ['Qual artista brasileiro criou os "Parangolés", capas para vestir e dançar?', ['Hélio Oiticica', 'Cildo Meireles', 'Antonio Dias', 'Amilcar de Castro'], 0, 'Ele levou passistas da Mangueira para dentro do museu, em 1965.'],
    ['Qual divindade hindu tem cabeça de elefante?', ['Vishnu', 'Shiva', 'Brahma', 'Ganesha'], 3, 'É considerado o removedor de obstáculos.'],
    ['Qual é a tríade principal de divindades do hinduísmo?', ['Ganesha, Vishnu e Shiva', 'Brahma, Vishnu e Shiva', 'Krishna, Rama e Shiva', 'Indra, Agni e Varuna'], 1, 'Eles representam, respectivamente, criação, preservação e destruição.'],
    ['Como se chama o ciclo de mortes e renascimentos no hinduísmo e no budismo?', ['nirvana', 'carma', 'samsara', 'darma'], 2, 'O carma é a lei de causa e efeito que move esse ciclo.'],
    ['Qual é o estado de libertação do sofrimento no budismo?', ['samsara', 'nirvana', 'carma', 'mantra'], 1, 'Alcançá-lo significa romper o ciclo de renascimentos.'],
    ['Qual ordem monástica cristã foi fundada por Bento de Núrsia?', ['franciscanos', 'jesuítas', 'dominicanos', 'beneditinos'], 3, 'O lema da ordem é "ora et labora": reza e trabalha.'],
    ['Qual ordem religiosa foi fundada por Inácio de Loyola?', ['franciscanos', 'carmelitas', 'jesuítas', 'dominicanos'], 2, 'A Companhia de Jesus teve papel central na catequese no Brasil colonial.'],
    ['Quem é considerado o primeiro papa pela tradição católica?', ['Pedro', 'Paulo', 'Lino', 'Clemente'], 0, 'A Basílica de São Pedro, no Vaticano, teria sido erguida sobre seu túmulo.'],
  ],
  5: [
    ['Qual caverna francesa é famosa por suas pinturas rupestres?', ['Chauvet', 'Altamira', 'Lascaux', 'Atapuerca'], 2, 'As pinturas têm cerca de 17 mil anos e foram achadas por adolescentes em 1940.'],
    ['Qual parque nacional do Piauí abriga milhares de pinturas rupestres?', ['Chapada dos Veadeiros', 'Lençóis Maranhenses', 'Sete Cidades', 'Serra da Capivara'], 3, 'O sítio, dirigido por décadas pela arqueóloga Niède Guidon, é patrimônio mundial.'],
    ['Qual escultor grego é associado à estátua do "Discóbolo"?', ['Fídias', 'Míron', 'Policleto', 'Praxíteles'], 1, 'O original em bronze se perdeu; restaram cópias romanas em mármore.'],
    ['Qual escultor dirigiu as obras de decoração do Partenon?', ['Fídias', 'Míron', 'Policleto', 'Lisipo'], 0, 'Ele também esculpiu a estátua de Zeus em Olímpia, uma das sete maravilhas.'],
    ['Quais são as três ordens da arquitetura grega clássica?', ['dórica, jônica e coríntia', 'toscana, dórica e romana', 'jônica, gótica e coríntia', 'dórica, corintiana e bizantina'], 0, 'Elas se distinguem sobretudo pelo capitel, o topo da coluna.'],
    ['Qual templo de Istambul foi a maior catedral cristã do mundo por quase mil anos?', ['Basílica de São Marcos', 'Santa Sofia', 'Igreja da Natividade', 'São Vital de Ravena'], 1, 'Construída em 537, virou mesquita, depois museu e novamente mesquita.'],
    ['Qual pintor flamengo criou o tríptico "O Jardim das Delícias"?', ['Jan van Eyck', 'Pieter Bruegel', 'Hans Memling', 'Hieronymus Bosch'], 3, 'A obra, de cerca de 1500, impressiona pelas criaturas fantásticas.'],
    ['Qual pintor espanhol retratou "Os Fuzilamentos de 3 de Maio"?', ['Velázquez', 'El Greco', 'Francisco de Goya', 'Bartolomé Murillo'], 2, 'A tela denuncia a repressão napoleônica em Madri, em 1808.'],
    ['Qual obra de Velázquez mostra o próprio pintor, a infanta e o reflexo dos reis?', ['A Rendição de Breda', 'As Meninas', 'O Triunfo de Baco', 'Cristo Crucificado'], 1, 'A pintura de 1656 é estudada até hoje por seu jogo de perspectivas.'],
    ['Qual movimento do início do século XX exaltava máquinas, velocidade e modernidade?', ['dadaísmo', 'surrealismo', 'futurismo', 'construtivismo'], 2, 'O manifesto foi lançado pelo italiano Marinetti em 1909.'],
    ['Qual artista criou a técnica do "dripping", pingando tinta sobre a tela no chão?', ['Jackson Pollock', 'Mark Rothko', 'Willem de Kooning', 'Franz Kline'], 0, 'Ele é o principal nome do expressionismo abstrato americano.'],
    ['Qual arquiteto projetou o Museu Guggenheim de Nova York?', ['I. M. Pei', 'Frank Gehry', 'Renzo Piano', 'Frank Lloyd Wright'], 3, 'O prédio em espiral foi concluído em 1959, ano da morte do arquiteto.'],
    ['Qual paisagista brasileiro assinou o calçadão de Copacabana e jardins de Brasília?', ['Lucio Costa', 'Oscar Niemeyer', 'Athos Bulcão', 'Roberto Burle Marx'], 3, 'Ele também foi pintor e descobriu dezenas de espécies vegetais.'],
    ['Qual artista criou os painéis de azulejos que marcam a arquitetura de Brasília?', ['Athos Bulcão', 'Candido Portinari', 'Di Cavalcanti', 'Alfredo Volpi'], 0, 'Seus azulejos combinam formas simples em composições sempre diferentes.'],
    ['Qual pintor brasileiro ficou conhecido por suas bandeirinhas de festa junina?', ['Alberto da Veiga Guignard', 'José Pancetti', 'Alfredo Volpi', 'Iberê Camargo'], 2, 'Filho de imigrantes italianos, ele começou como pintor de paredes.'],
    ['Qual deusa romana corresponde à grega Afrodite?', ['Juno', 'Vênus', 'Minerva', 'Ceres'], 1, 'Ela é a deusa do amor e da beleza.'],
    ['Quem decifrou o enigma da Esfinge na mitologia grega?', ['Édipo', 'Teseu', 'Jasão', 'Belerofonte'], 0, 'A resposta ao enigma era o próprio ser humano.'],
    ['Qual herói grego matou o Minotauro no labirinto de Creta?', ['Perseu', 'Teseu', 'Hércules', 'Aquiles'], 1, 'Ele usou um fio de lã dado por Ariadne para encontrar a saída.'],
    ['Qual era o nome do navio em que Jasão partiu em busca do Velo de Ouro?', ['Odisseia', 'Pégaso', 'Argo', 'Nau Catarineta'], 2, 'Seus tripulantes ficaram conhecidos como argonautas.'],
    ['Qual texto sagrado hindu faz parte do épico Mahabharata?', ['Vedas', 'Upanixades', 'Ramayana', 'Bhagavad Gita'], 3, 'Nele, o deus Krishna aconselha o guerreiro Arjuna antes da batalha.'],
  ],
});
