import { montar } from './montar';

/** Biologia e Corpo Humano — 100 perguntas (20 por nível). */
export const perguntasBiologiaCorpo = montar('biologia-corpo', {
  1: [
    ['Qual órgão bombeia o sangue pelo corpo humano?', ['Pulmão', 'Fígado', 'Coração', 'Rim'], 2, 'O coração bate cerca de 100 mil vezes por dia em um adulto.'],
    ['Quantos ossos tem o corpo humano adulto?', ['206', '180', '250', '300'], 0, 'Bebês nascem com cerca de 300 ossos, que se fundem ao longo do crescimento.'],
    ['Quais órgãos são responsáveis pela respiração?', ['O coração', 'Os pulmões', 'O estômago', 'O fígado'], 1, 'Os pulmões trocam oxigênio por gás carbônico em estruturas chamadas alvéolos.'],
    ['Qual é o maior órgão do corpo humano?', ['Fígado', 'Intestino', 'Cérebro', 'Pele'], 3, 'A pele de um adulto cobre cerca de 2 m² e pesa em média 4 quilos.'],
    ['Qual é o maior animal do mundo?', ['Baleia-azul', 'Elefante africano', 'Girafa', 'Tubarão-baleia'], 0, 'A baleia-azul pode passar de 30 metros e pesar mais de 150 toneladas.'],
    ['Qual gás as plantas liberam no ar durante a fotossíntese?', ['Gás carbônico', 'Nitrogênio', 'Metano', 'Oxigênio'], 3, 'Elas absorvem gás carbônico e devolvem oxigênio à atmosfera.'],
    ['Qual é o menor osso do corpo humano?', ['Fêmur', 'Rádio', 'Estribo', 'Úmero'], 2, 'O estribo fica no ouvido médio e mede cerca de 3 milímetros.'],
    ['Quantos corações tem um polvo?', ['Um', 'Três', 'Dois', 'Quatro'], 1, 'Dois bombeiam sangue para as brânquias e um para o resto do corpo.'],
    ['Qual grupo de animais amamenta seus filhotes?', ['Répteis', 'Anfíbios', 'Aves', 'Mamíferos'], 3, 'A presença de glândulas mamárias e pelos define os mamíferos.'],
    ['Qual é o maior osso do corpo humano?', ['Úmero', 'Fêmur', 'Tíbia', 'Clavícula'], 1, 'O fêmur, osso da coxa, pode suportar até 30 vezes o peso do corpo.'],
    ['Quais órgãos filtram o sangue e produzem a urina?', ['Os rins', 'O fígado', 'O baço', 'O pâncreas'], 0, 'Os rins filtram cerca de 180 litros de sangue por dia.'],
    ['De qual animal vem a lã?', ['Vaca', 'Cabra', 'Ovelha', 'Porco'], 2, 'A tosquia é feita normalmente uma vez por ano e não machuca o animal.'],
    ['Quantos dentes tem um adulto, contando os sisos?', ['28', '32', '20', '36'], 1, 'As crianças têm 20 dentes de leite, trocados a partir dos seis anos.'],
    ['Qual parte da planta realiza a maior parte da fotossíntese?', ['A raiz', 'O caule', 'A folha', 'A flor'], 2, 'As folhas concentram os cloroplastos, onde a luz é transformada em energia.'],
    ['Qual é o animal terrestre mais rápido do mundo?', ['Leão', 'Cavalo', 'Avestruz', 'Guepardo'], 3, 'O guepardo alcança cerca de 110 km/h, mas só por poucos segundos.'],
    ['Em qual órgão o alimento é digerido pela ação do suco gástrico?', ['No estômago', 'No pulmão', 'No coração', 'No cérebro'], 0, 'O suco gástrico é tão ácido que dissolveria metal; o muco protege a parede do órgão.'],
    ['Qual sistema do corpo humano é formado pelos ossos?', ['Esquelético', 'Nervoso', 'Digestório', 'Circulatório'], 0, 'Além de sustentar o corpo, os ossos produzem células do sangue na medula.'],
    ['Qual destes animais é um anfíbio?', ['Tartaruga', 'Cobra', 'Sapo', 'Lagarto'], 2, 'Anfíbios vivem parte da vida na água e parte na terra.'],
    ['Como se chama a transformação da lagarta em borboleta?', ['Fotossíntese', 'Metamorfose', 'Fecundação', 'Germinação'], 1, 'Dentro do casulo, o corpo do inseto é praticamente reconstruído.'],
    ['Qual órgão comanda o corpo e é responsável pelo pensamento?', ['Coração', 'Fígado', 'Pulmão', 'Cérebro'], 3, 'O cérebro humano tem cerca de 86 bilhões de neurônios.'],
  ],
  2: [
    ['Qual é a unidade básica de todos os seres vivos?', ['Átomo', 'Célula', 'Molécula', 'Tecido'], 1, 'A teoria celular afirma que todo ser vivo é formado por uma ou mais células.'],
    ['Qual pigmento dá a cor verde às plantas?', ['Caroteno', 'Melanina', 'Hemoglobina', 'Clorofila'], 3, 'A clorofila absorve luz vermelha e azul e reflete a verde.'],
    ['Qual gás o ser humano precisa inspirar para viver?', ['Oxigênio', 'Gás carbônico', 'Nitrogênio', 'Hidrogênio'], 0, 'Curiosamente, o ar que respiramos é formado em quase 78% por nitrogênio.'],
    ['Qual proteína do sangue transporta o oxigênio?', ['Insulina', 'Albumina', 'Hemoglobina', 'Queratina'], 2, 'É o ferro da hemoglobina que dá ao sangue sua cor vermelha.'],
    ['Qual órgão produz a insulina?', ['Fígado', 'Rim', 'Estômago', 'Pâncreas'], 3, 'A insulina é produzida nas ilhotas de Langerhans, no pâncreas.'],
    ['Quantas cavidades tem o coração humano?', ['Duas', 'Quatro', 'Três', 'Seis'], 1, 'São dois átrios e dois ventrículos, separando sangue venoso e arterial.'],
    ['Qual é o maior órgão interno do corpo humano?', ['Coração', 'Pulmão', 'Fígado', 'Rim'], 2, 'O fígado pesa cerca de 1,5 kg e desempenha mais de 500 funções.'],
    ['Em qual parte do corpo ocorre a maior absorção de nutrientes?', ['Intestino delgado', 'Estômago', 'Intestino grosso', 'Esôfago'], 0, 'Suas vilosidades aumentam a superfície de absorção para cerca de 250 m².'],
    ['Como é chamado o esqueleto externo de insetos e crustáceos?', ['Exoesqueleto', 'Endoesqueleto', 'Notocorda', 'Cartilagem'], 0, 'Feito de quitina, precisa ser trocado para que o animal cresça.'],
    ['Como são classificados os animais que se alimentam apenas de vegetais?', ['Carnívoros', 'Onívoros', 'Herbívoros', 'Detritívoros'], 2, 'Muitos herbívoros têm estômagos com várias câmaras para digerir celulose.'],
    ['Qual grupo de animais tem o corpo coberto de penas?', ['Mamíferos', 'Répteis', 'Anfíbios', 'Aves'], 3, 'As penas servem para voar, mas também para isolamento térmico e exibição.'],
    ['Qual sistema é responsável pela defesa do organismo contra infecções?', ['Sistema nervoso', 'Sistema imunológico', 'Sistema endócrino', 'Sistema respiratório'], 1, 'Os glóbulos brancos são as principais células de defesa do corpo.'],
    ['Qual vitamina é produzida pela pele quando exposta ao sol?', ['Vitamina A', 'Vitamina C', 'Vitamina D', 'Vitamina K'], 2, 'A vitamina D é essencial para a absorção de cálcio pelos ossos.'],
    ['Quantos cromossomos tem uma célula humana comum?', ['46', '23', '48', '44'], 0, 'São 23 pares; os gametas têm apenas 23 cromossomos.'],
    ['Qual molécula guarda a informação genética dos seres vivos?', ['RNA', 'DNA', 'ATP', 'Colágeno'], 1, 'O DNA tem forma de dupla hélice, descrita em 1953.'],
    ['Qual tipo de divisão celular forma os gametas?', ['Mitose', 'Fissão binária', 'Brotamento', 'Meiose'], 3, 'A meiose reduz pela metade o número de cromossomos das células-filhas.'],
    ['Qual é o maior animal terrestre da atualidade?', ['Rinoceronte', 'Hipopótamo', 'Girafa', 'Elefante africano'], 3, 'Um macho adulto pode pesar mais de seis toneladas.'],
    ['Qual grupo reúne os mamíferos que põem ovos?', ['Marsupiais', 'Monotremados', 'Cetáceos', 'Roedores'], 1, 'O ornitorrinco e a equidna são os únicos representantes vivos.'],
    ['Qual estrutura do ouvido interno é responsável pelo equilíbrio?', ['O labirinto', 'A laringe', 'A traqueia', 'A faringe'], 0, 'Os canais semicirculares detectam a posição e o movimento da cabeça.'],
    ['Qual tecido liga o músculo ao osso?', ['Ligamento', 'Cartilagem', 'Tendão', 'Membrana'], 2, 'Os ligamentos, por sua vez, ligam um osso a outro.'],
  ],
  3: [
    ['Qual organela é chamada de "usina de energia" da célula?', ['Mitocôndria', 'Ribossomo', 'Lisossomo', 'Complexo de Golgi'], 0, 'É nela que ocorre a respiração celular, produzindo ATP.'],
    ['Qual organela realiza a fotossíntese nas plantas?', ['Vacúolo', 'Mitocôndria', 'Cloroplasto', 'Núcleo'], 2, 'Os cloroplastos têm DNA próprio, indício de sua origem bacteriana.'],
    ['Quem formulou a teoria da evolução por seleção natural?', ['Lamarck', 'Mendel', 'Pasteur', 'Charles Darwin'], 3, 'Darwin publicou "A Origem das Espécies" em 1859.'],
    ['Quem é considerado o pai da genética?', ['Charles Darwin', 'Gregor Mendel', 'James Watson', 'Carl Linnaeus'], 1, 'O monge austríaco descobriu as leis da hereditariedade cruzando ervilhas.'],
    ['Como é chamada a troca gasosa que ocorre nos alvéolos pulmonares?', ['Digestão', 'Filtração', 'Hematose', 'Excreção'], 2, 'Na hematose, o sangue libera gás carbônico e recebe oxigênio.'],
    ['Qual tipo sanguíneo é considerado doador universal?', ['O negativo', 'AB positivo', 'A positivo', 'B negativo'], 0, 'O sangue O negativo não tem antígenos A, B nem Rh na superfície das hemácias.'],
    ['Qual tipo sanguíneo é considerado receptor universal?', ['O negativo', 'AB positivo', 'A negativo', 'B positivo'], 1, 'Quem tem AB positivo não produz anticorpos contra os antígenos A, B ou Rh.'],
    ['Quantos pares de cromossomos tem o ser humano?', ['46', '24', '21', '23'], 3, 'Um dos pares define o sexo biológico: XX ou XY.'],
    ['Qual reino biológico inclui cogumelos e leveduras?', ['Plantae', 'Fungi', 'Protista', 'Monera'], 1, 'Os fungos não fazem fotossíntese: absorvem nutrientes já prontos.'],
    ['Qual cientista descobriu a penicilina?', ['Louis Pasteur', 'Robert Koch', 'Jonas Salk', 'Alexander Fleming'], 3, 'A descoberta acidental, em 1928, inaugurou a era dos antibióticos.'],
    ['Qual é o nome científico da espécie humana?', ['Homo erectus', 'Homo habilis', 'Homo sapiens', 'Australopithecus'], 2, 'A nomenclatura binomial foi criada por Carl Linnaeus no século XVIII.'],
    ['Qual estrutura óssea protege o cérebro?', ['O crânio', 'A coluna vertebral', 'A caixa torácica', 'A pelve'], 0, 'O crânio adulto é formado por 22 ossos, a maioria fundida entre si.'],
    ['Como se chama a perda de água pelas folhas das plantas?', ['Osmose', 'Fotossíntese', 'Respiração', 'Transpiração'], 3, 'A transpiração ajuda a puxar a água das raízes até as folhas.'],
    ['Qual glândula é conhecida como "glândula-mestra" do corpo?', ['Tireoide', 'Hipófise', 'Suprarrenal', 'Pâncreas'], 1, 'A hipófise comanda o funcionamento de várias outras glândulas.'],
    ['Qual hormônio regula a quantidade de açúcar no sangue?', ['Insulina', 'Adrenalina', 'Tiroxina', 'Testosterona'], 0, 'A falta ou a resistência à insulina caracteriza o diabetes.'],
    ['Qual é o maior músculo do corpo humano?', ['Bíceps', 'Peitoral', 'Glúteo máximo', 'Sartório'], 2, 'Ele é essencial para manter o corpo ereto e para subir escadas.'],
    ['Qual parte do neurônio transmite o impulso nervoso para outras células?', ['Dendrito', 'Corpo celular', 'Axônio', 'Nucléolo'], 2, 'Alguns axônios humanos chegam a ter quase um metro de comprimento.'],
    ['Quais animais formam o grupo dos cetáceos?', ['Baleias e golfinhos', 'Tubarões e raias', 'Focas e leões-marinhos', 'Polvos e lulas'], 0, 'São mamíferos totalmente adaptados à vida aquática.'],
    ['Como se chama a passagem de água através de uma membrana semipermeável?', ['Difusão simples', 'Transporte ativo', 'Fagocitose', 'Osmose'], 3, 'A água se move do meio menos concentrado para o mais concentrado em solutos.'],
    ['Quais vasos levam o sangue do coração para o resto do corpo?', ['Veias', 'Artérias', 'Capilares', 'Vasos linfáticos'], 1, 'As artérias têm paredes musculosas para suportar a pressão do bombeamento.'],
  ],
  4: [
    ['Em qual fase da mitose os cromossomos se alinham no centro da célula?', ['Prófase', 'Anáfase', 'Telófase', 'Metáfase'], 3, 'Na anáfase seguinte, as cromátides são puxadas para polos opostos.'],
    ['Qual base nitrogenada existe no RNA, mas não no DNA?', ['Timina', 'Uracila', 'Citosina', 'Guanina'], 1, 'No RNA, a uracila ocupa o lugar da timina ao parear com a adenina.'],
    ['Como se chama a produção de proteínas a partir do RNA mensageiro?', ['Replicação', 'Transcrição', 'Tradução', 'Transdução'], 2, 'A tradução ocorre nos ribossomos, que leem o código de três em três bases.'],
    ['Onde ocorre a maior parte da respiração celular aeróbica?', ['Nas mitocôndrias', 'No núcleo', 'Nos ribossomos', 'No retículo endoplasmático'], 0, 'O ciclo de Krebs e a cadeia respiratória acontecem dentro dessa organela.'],
    ['Qual cientista propôs a lei do uso e desuso dos órgãos?', ['Charles Darwin', 'Jean-Baptiste Lamarck', 'Gregor Mendel', 'Alfred Wallace'], 1, 'Lamarck acreditava que caracteres adquiridos em vida eram transmitidos aos filhos.'],
    ['Como se chama o conjunto de todos os genes de um organismo?', ['Cariótipo', 'Fenótipo', 'Genoma', 'Alelo'], 2, 'O sequenciamento do genoma humano foi concluído em 2003.'],
    ['Qual estrutura impede que o alimento entre na traqueia?', ['Epiglote', 'Glote', 'Faringe', 'Úvula'], 0, 'Ao engolir, a epiglote fecha a entrada das vias aéreas como uma tampa.'],
    ['Qual parte do cérebro controla o equilíbrio e a coordenação motora?', ['Bulbo', 'Hipotálamo', 'Córtex frontal', 'Cerebelo'], 3, 'Apesar de pequeno, o cerebelo concentra mais da metade dos neurônios do cérebro.'],
    ['Qual ciclo transforma o nitrogênio do ar em compostos que as plantas absorvem?', ['Ciclo do carbono', 'Ciclo da água', 'Ciclo do nitrogênio', 'Ciclo do fósforo'], 2, 'Bactérias fixadoras nas raízes de leguminosas fazem boa parte desse trabalho.'],
    ['Como se chama a relação ecológica em que os dois organismos se beneficiam?', ['Mutualismo', 'Comensalismo', 'Parasitismo', 'Predatismo'], 0, 'Um exemplo é a relação entre abelhas e flores.'],
    ['Qual tipo de célula não possui núcleo delimitado por membrana?', ['Eucarionte', 'Procarionte', 'Célula-tronco', 'Gameta'], 1, 'As bactérias são procariontes: seu material genético fica solto no citoplasma.'],
    ['Qual é o principal hormônio produzido pela glândula tireoide?', ['Insulina', 'Cortisol', 'Adrenalina', 'Tiroxina'], 3, 'A tiroxina regula o metabolismo, o crescimento e a temperatura corporal.'],
    ['Qual doença é causada pela falta de vitamina C?', ['Escorbuto', 'Raquitismo', 'Beribéri', 'Pelagra'], 0, 'O escorbuto matou milhares de marinheiros antes do uso de frutas cítricas a bordo.'],
    ['Qual pigmento determina a cor da pele humana?', ['Caroteno', 'Hemoglobina', 'Clorofila', 'Melanina'], 3, 'A melanina também protege as células contra a radiação ultravioleta.'],
    ['Qual é a camada mais externa da pele?', ['Derme', 'Epiderme', 'Hipoderme', 'Tecido adiposo'], 1, 'A epiderme se renova completamente a cada quatro semanas, aproximadamente.'],
    ['Quantas vértebras formam a coluna cervical humana?', ['5', '12', '7', '9'], 2, 'Curiosamente, girafas também têm sete vértebras cervicais, só que enormes.'],
    ['Qual é o maior nervo do corpo humano?', ['Nervo óptico', 'Nervo ciático', 'Nervo vago', 'Nervo femoral'], 1, 'O ciático vai da base da coluna até o pé e pode ter a espessura de um dedo.'],
    ['Qual órgão armazena a bile produzida pelo fígado?', ['Baço', 'Pâncreas', 'Apêndice', 'Vesícula biliar'], 3, 'A bile ajuda a digerir gorduras no intestino delgado.'],
    ['Qual processo as leveduras realizam para produzir álcool e gás carbônico?', ['Respiração aeróbica', 'Fotossíntese', 'Fermentação', 'Quimiossíntese'], 2, 'É esse processo que faz o pão crescer e transforma o mosto em cerveja e vinho.'],
    ['A qual classe de animais pertencem as aranhas?', ['Aracnídeos', 'Insetos', 'Crustáceos', 'Miriápodes'], 0, 'Aracnídeos têm oito patas e o corpo dividido em duas partes, não três.'],
  ],
  5: [
    ['Qual cientista observou células pela primeira vez, em um corte de cortiça?', ['Louis Pasteur', 'Antonie van Leeuwenhoek', 'Robert Hooke', 'Theodor Schwann'], 2, 'Em 1665, Hooke batizou as cavidades de "cells", ou celas.'],
    ['Quem chegou à teoria da seleção natural ao mesmo tempo que Darwin?', ['Lamarck', 'Mendel', 'Thomas Huxley', 'Alfred Russel Wallace'], 3, 'A carta de Wallace levou Darwin a finalmente publicar sua teoria.'],
    ['Qual estrutura une as duas cromátides irmãs de um cromossomo?', ['Telômero', 'Centrômero', 'Nucléolo', 'Cinetocoro'], 1, 'A posição do centrômero classifica os cromossomos em metacêntricos, submetacêntricos e outros.'],
    ['Qual molécula funciona como a "moeda energética" das células?', ['ATP', 'DNA', 'RNA', 'Glicogênio'], 0, 'O trifosfato de adenosina libera energia ao perder um grupo fosfato.'],
    ['Como se chama o processo em que a célula engloba partículas sólidas?', ['Fagocitose', 'Pinocitose', 'Osmose', 'Difusão facilitada'], 0, 'É assim que certos glóbulos brancos destroem bactérias invasoras.'],
    ['Como se chama o conjunto de características observáveis de um organismo?', ['Genótipo', 'Fenótipo', 'Cariótipo', 'Genoma'], 1, 'O fenótipo resulta da interação entre o genótipo e o ambiente.'],
    ['Qual hormônio prepara o corpo para a reação de luta ou fuga?', ['Insulina', 'Tiroxina', 'Melatonina', 'Adrenalina'], 3, 'Produzida pelas suprarrenais, ela acelera o coração e dilata as pupilas.'],
    ['Quantos pares de nervos cranianos existem no ser humano?', ['10', '8', '12', '14'], 2, 'Entre eles estão o nervo óptico, o olfatório e o vago.'],
    ['Qual cientista derrubou a teoria da geração espontânea?', ['Robert Koch', 'Louis Pasteur', 'Edward Jenner', 'Alexander Fleming'], 1, 'Seus experimentos com frascos "pescoço de cisne" mostraram que a vida vem de vida.'],
    ['Qual médico inglês criou a primeira vacina, contra a varíola?', ['Louis Pasteur', 'Robert Koch', 'Edward Jenner', 'Oswaldo Cruz'], 2, 'Jenner usou material da varíola bovina, em 1796 — daí a palavra "vacina".'],
    ['Como se chama o fenômeno em que espécies distintas desenvolvem formas parecidas em ambientes semelhantes?', ['Convergência evolutiva', 'Irradiação adaptativa', 'Deriva genética', 'Especiação'], 0, 'É o caso do formato hidrodinâmico de tubarões, golfinhos e ictiossauros.'],
    ['Como se chama o processo de formação de novas espécies?', ['Mutação', 'Seleção artificial', 'Deriva continental', 'Especiação'], 3, 'Costuma ocorrer quando populações ficam isoladas e param de cruzar entre si.'],
    ['Qual é a unidade funcional do rim, responsável por filtrar o sangue?', ['Uretra', 'Bexiga', 'Ureter', 'Néfron'], 3, 'Cada rim humano tem cerca de um milhão de néfrons.'],
    ['Qual é a maior artéria do corpo humano?', ['Aorta', 'Carótida', 'Artéria pulmonar', 'Artéria femoral'], 0, 'A aorta sai do ventrículo esquerdo e distribui sangue para todo o organismo.'],
    ['Quanto dura, em média, a gestação de um elefante?', ['9 meses', '12 meses', '22 meses', '30 meses'], 2, 'É a gestação mais longa entre os mamíferos terrestres.'],
    ['Qual cientista brasileiro descobriu a doença de Chagas?', ['Oswaldo Cruz', 'Carlos Chagas', 'Vital Brazil', 'Adolpho Lutz'], 1, 'Chagas descreveu o parasita, o inseto transmissor e a doença — feito raro na ciência.'],
    ['Qual cientista brasileiro desenvolveu os primeiros soros antiofídicos?', ['Vital Brazil', 'Carlos Chagas', 'Oswaldo Cruz', 'Emílio Ribas'], 0, 'Ele fundou o Instituto Butantan, em São Paulo, em 1901.'],
    ['Como é chamado o conjunto de microrganismos que vivem no intestino humano?', ['Flora cutânea', 'Microbiota intestinal', 'Placa bacteriana', 'Biofilme dentário'], 1, 'São trilhões de bactérias que ajudam na digestão e na imunidade.'],
    ['Qual é o único mamífero capaz de voo verdadeiro?', ['Esquilo-voador', 'Colugo', 'Morcego', 'Petauro-do-açúcar'], 2, 'Os demais apenas planam; só o morcego bate as asas e se sustenta no ar.'],
    ['Qual tecido vegetal conduz a seiva bruta das raízes até as folhas?', ['Floema', 'Parênquima', 'Epiderme', 'Xilema'], 3, 'O floema, por sua vez, distribui a seiva elaborada produzida na fotossíntese.'],
  ],
});
