import { montar } from './montar';

/** Cinema e TV — 100 perguntas (20 por nível). */
export const perguntasCinemaTv = montar('cinema-tv', {
  1: [
    ['Qual é o rato mais famoso dos desenhos animados?', ['Pluto', 'Jerry', 'Mickey Mouse', 'Pernalonga'], 2, 'Mickey estreou em 1928, no curta "Steamboat Willie".'],
    ['Qual é o prêmio mais famoso do cinema americano?', ['Oscar', 'Grammy', 'Emmy', 'Tony'], 0, 'O Grammy premia a música; o Emmy, a televisão; e o Tony, o teatro.'],
    ['Qual estúdio produziu "Toy Story"?', ['DreamWorks', 'Pixar', 'Warner', 'Universal'], 1, 'Lançado em 1995, foi o primeiro longa inteiramente feito em computação gráfica.'],
    ['Qual super-herói usa capa vermelha e um "S" no peito?', ['Batman', 'Homem-Aranha', 'Flash', 'Superman'], 3, 'O personagem estreou nos quadrinhos em 1938.'],
    ['Qual é o nome do jovem bruxo que estuda em Hogwarts?', ['Harry Potter', 'Rony Weasley', 'Draco Malfoy', 'Neville Longbottom'], 0, 'Foram oito filmes lançados entre 2001 e 2011.'],
    ['Em qual saga aparece a frase "Que a Força esteja com você"?', ['O Senhor dos Anéis', 'Jornada nas Estrelas', 'De Volta para o Futuro', 'Star Wars'], 3, 'O primeiro filme da saga estreou em 1977.'],
    ['Qual desenho animado mostra uma família amarela na cidade de Springfield?', ['Uma Família da Pesada', 'Futurama', 'Os Simpsons', 'South Park'], 2, 'A série estreou em 1989 e é a mais longeva da TV americana em horário nobre.'],
    ['Quem dirigiu "Jurassic Park"?', ['James Cameron', 'Steven Spielberg', 'George Lucas', 'Tim Burton'], 1, 'O filme de 1993 misturou animatrônicos e computação gráfica pioneira.'],
    ['Qual filme conta a história do navio que afundou em 1912?', ['Poseidon', 'Náufrago', 'Pearl Harbor', 'Titanic'], 3, 'O filme de James Cameron foi o primeiro a arrecadar mais de 1 bilhão de dólares.'],
    ['Qual princesa da Disney perde um sapatinho de cristal?', ['Branca de Neve', 'Cinderela', 'Bela', 'Aurora'], 1, 'A animação clássica é de 1950.'],
    ['Qual super-herói se veste de morcego?', ['Batman', 'Homem de Ferro', 'Coringa', 'Robin'], 0, 'Seu nome verdadeiro é Bruce Wayne, e ele atua em Gotham City.'],
    ['Que animal é Simba, de "O Rei Leão"?', ['tigre', 'urso', 'leão', 'lobo'], 2, 'A animação de 1994 é inspirada em "Hamlet", de Shakespeare.'],
    ['Que tipo de peixe é Nemo, de "Procurando Nemo"?', ['golfinho', 'peixe-palhaço', 'tartaruga', 'tubarão'], 1, 'O filme fez a procura por peixes-palhaço de estimação disparar no mundo todo.'],
    ['Qual destes é um canal de TV aberta brasileiro?', ['HBO', 'Telecine', 'SBT', 'Netflix'], 2, 'O SBT foi fundado por Silvio Santos em 1981.'],
    ['Qual personagem de Maurício de Sousa tem um coelhinho azul chamado Sansão?', ['Cebolinha', 'Cascão', 'Magali', 'Mônica'], 3, 'A Turma da Mônica surgiu nos anos 1960 e virou filme, série e parque.'],
    ['Qual amigo do Mickey é um pato?', ['Pato Donald', 'Pateta', 'Pluto', 'Tio Patinhas'], 0, 'Donald estreou em 1934 e é conhecido pelo temperamento explosivo.'],
    ['Qual gênero de filme tem como objetivo assustar o público?', ['terror', 'comédia', 'romance', 'musical'], 0, 'O suspense trabalha a tensão, enquanto o terror busca o susto e o medo.'],
    ['Qual saga de filmes gira em torno da destruição de um anel mágico?', ['As Crônicas de Nárnia', 'Harry Potter', 'O Senhor dos Anéis', 'Percy Jackson'], 2, 'A trilogia foi gravada inteiramente na Nova Zelândia.'],
    ['Qual é a identidade secreta do Homem-Aranha?', ['Bruce Wayne', 'Peter Parker', 'Clark Kent', 'Tony Stark'], 1, 'Ele ganhou os poderes após ser picado por uma aranha radioativa.'],
    ['Qual é o nome do caubói de brinquedo de "Toy Story"?', ['Buzz Lightyear', 'Jessie', 'Rex', 'Woody'], 3, 'Ele é o brinquedo favorito do menino Andy.'],
  ],
  2: [
    ['Qual filme brasileiro venceu o Oscar de Melhor Filme Internacional em 2025?', ['Cidade de Deus', 'Ainda Estou Aqui', 'Central do Brasil', 'O Pagador de Promessas'], 1, 'Foi a primeira estatueta do Oscar conquistada por um filme brasileiro.'],
    ['Quem dirigiu "Cidade de Deus"?', ['Walter Salles', 'José Padilha', 'Bruno Barreto', 'Fernando Meirelles'], 3, 'O filme de 2002 foi codirigido por Kátia Lund e rendeu quatro indicações ao Oscar.'],
    ['Qual atriz brasileira foi indicada ao Oscar por "Central do Brasil"?', ['Fernanda Montenegro', 'Sônia Braga', 'Glória Pires', 'Marieta Severo'], 0, 'A indicação, em 1999, foi a primeira de uma atriz brasileira na categoria.'],
    ['Qual filme de 1997 tem Leonardo DiCaprio e Kate Winslet como protagonistas?', ['Romeu + Julieta', 'O Aviador', 'Titanic', 'A Praia'], 2, 'O filme venceu 11 Oscars, empatando o recorde histórico.'],
    ['Qual série da Netflix se passa em Hawkins e tem o Mundo Invertido?', ['Dark', 'La Casa de Papel', 'Black Mirror', 'Stranger Things'], 3, 'A série estreou em 2016 com forte estética dos anos 1980.'],
    ['Quem dirigiu "Tropa de Elite"?', ['Fernando Meirelles', 'José Padilha', 'Walter Salles', 'Kleber Mendonça Filho'], 1, 'O filme venceu o Urso de Ouro do Festival de Berlim em 2008.'],
    ['Qual é o nome do protagonista de "Tropa de Elite"?', ['Neto', 'Matias', 'Capitão Nascimento', 'Baiano'], 2, 'O papel foi interpretado por Wagner Moura.'],
    ['Qual diretor americano fez "Pulp Fiction"?', ['Quentin Tarantino', 'Martin Scorsese', 'Francis Ford Coppola', 'Steven Spielberg'], 0, 'O filme de 1994 venceu a Palma de Ouro em Cannes.'],
    ['Qual série acompanha uma família mafiosa de Nova Jersey?', ['Os Sopranos', 'Breaking Bad', 'The Wire', 'Mad Men'], 0, 'Estreou em 1999 e é apontada como marco da chamada era de ouro da TV.'],
    ['Qual série mostra um professor de química que passa a fabricar metanfetamina?', ['Dexter', 'Narcos', 'Breaking Bad', 'Ozark'], 2, 'Walter White foi interpretado por Bryan Cranston em cinco temporadas.'],
    ['Qual animação da Disney tem a canção "Let It Go"?', ['Moana', 'Enrolados', 'Valente', 'Frozen'], 3, 'A música venceu o Oscar de Melhor Canção Original em 2014.'],
    ['Quem interpretou o Coringa no filme de 2019?', ['Heath Ledger', 'Joaquin Phoenix', 'Jack Nicholson', 'Jared Leto'], 1, 'O papel lhe rendeu o Oscar de Melhor Ator.'],
    ['Qual ator interpretou João Grilo em "O Auto da Compadecida"?', ['Selton Mello', 'Lima Duarte', 'Matheus Nachtergaele', 'Marco Nanini'], 2, 'O filme de 2000 nasceu de uma minissérie da TV Globo.'],
    ['Qual série espanhola tem assaltantes com máscaras de Salvador Dalí?', ['La Casa de Papel', 'Elite', 'Vis a Vis', 'As Telefonistas'], 0, 'O macacão vermelho e a máscara viraram fantasia popular no carnaval.'],
    ['Qual filme da Marvel encerrou a saga contra Thanos, em 2019?', ['Vingadores: Guerra Infinita', 'Vingadores: Ultimato', 'Os Vingadores', 'Capitã Marvel'], 1, 'O filme se tornou a maior bilheteria da história na época de seu lançamento.'],
    ['Quem dirigiu "O Poderoso Chefão"?', ['Martin Scorsese', 'Steven Spielberg', 'Brian De Palma', 'Francis Ford Coppola'], 3, 'O filme de 1972 é baseado no romance de Mario Puzo.'],
    ['Qual ator interpretou Vito Corleone em "O Poderoso Chefão", de 1972?', ['Al Pacino', 'Robert De Niro', 'James Caan', 'Marlon Brando'], 3, 'De Niro interpretaria o mesmo personagem, mais jovem, na continuação.'],
    ['Qual foi o primeiro longa-metragem de animação da Disney?', ['Pinóquio', 'Branca de Neve e os Sete Anões', 'Fantasia', 'Dumbo'], 1, 'Lançado em 1937, foi chamado de "a loucura de Disney" antes do sucesso.'],
    ['Qual estúdio japonês produziu "A Viagem de Chihiro"?', ['Studio Ghibli', 'Toei Animation', 'Madhouse', 'Studio Bones'], 0, 'O filme venceu o Oscar de Melhor Animação em 2003.'],
    ['Qual filme de Charles Chaplin satiriza Adolf Hitler?', ['Tempos Modernos', 'Luzes da Cidade', 'O Grande Ditador', 'O Garoto'], 2, 'Lançado em 1940, foi o primeiro filme falado de Chaplin.'],
  ],
  3: [
    ['Qual filme brasileiro venceu o Urso de Ouro do Festival de Berlim em 1998?', ['Central do Brasil', 'Cidade de Deus', 'Tropa de Elite', 'Bacurau'], 0, 'O filme de Walter Salles também rendeu indicação ao Oscar para Fernanda Montenegro.'],
    ['Qual filme venceu o Oscar de Melhor Filme em 2020, o primeiro falado em outra língua?', ['Roma', 'Coringa', 'Parasita', '1917'], 2, 'A produção sul-coreana venceu quatro categorias naquela noite.'],
    ['Quem dirigiu "Parasita"?', ['Park Chan-wook', 'Kim Ki-duk', 'Hirokazu Kore-eda', 'Bong Joon-ho'], 3, 'Ele também dirigiu "O Hospedeiro" e "Expresso do Amanhã".'],
    ['Qual ator venceu o Oscar por interpretar o Coringa?', ['Heath Ledger', 'Joaquin Phoenix', 'Rami Malek', 'Leonardo DiCaprio'], 1, 'Heath Ledger venceu na categoria de ator coadjuvante, em 2009, pelo mesmo personagem.'],
    ['Qual filme de Alfred Hitchcock tem a célebre cena do chuveiro?', ['Os Pássaros', 'Um Corpo que Cai', 'Psicose', 'Janela Indiscreta'], 2, 'A cena de 45 segundos exigiu cerca de 70 posições de câmera.'],
    ['Qual filme de Orson Welles é apontado como um dos maiores da história?', ['Cidadão Kane', 'Casablanca', 'E o Vento Levou', 'Ben-Hur'], 0, 'Welles tinha 25 anos quando dirigiu, escreveu e protagonizou o filme, em 1941.'],
    ['Qual diretor fez "Taxi Driver" e "Os Bons Companheiros"?', ['Francis Ford Coppola', 'Martin Scorsese', 'Brian De Palma', 'Woody Allen'], 1, 'Ele só ganhou seu primeiro Oscar de direção em 2007, por "Os Infiltrados".'],
    ['Qual atriz brasileira venceu o Globo de Ouro de melhor atriz em 2025?', ['Fernanda Montenegro', 'Sônia Braga', 'Alice Braga', 'Fernanda Torres'], 3, 'Ela venceu por "Ainda Estou Aqui", 26 anos depois da indicação de sua mãe ao Oscar.'],
    ['Qual série da HBO é baseada nos livros de George R. R. Martin?', ['Westworld', 'Game of Thrones', 'True Detective', 'Succession'], 1, 'A série foi ao ar de 2011 a 2019 e virou fenômeno mundial.'],
    ['Qual filme de 1999 tem a regra "não se fala sobre o clube"?', ['Matrix', 'Seven', 'Fargo', 'Clube da Luta'], 3, 'Dirigido por David Fincher, fracassou nos cinemas e virou cult depois.'],
    ['Qual diretor pernambucano fez "Bacurau"?', ['Fernando Meirelles', 'José Padilha', 'Kleber Mendonça Filho', 'Walter Salles'], 2, 'O filme, codirigido por Juliano Dornelles, venceu o Prêmio do Júri em Cannes.'],
    ['Quem dirigiu "Que Horas Ela Volta?"', ['Anna Muylaert', 'Laís Bodanzky', 'Daniela Thomas', 'Tata Amaral'], 0, 'O filme de 2015 discute relações de classe a partir de uma empregada doméstica.'],
    ['Qual estúdio produziu "Shrek"?', ['Pixar', 'Disney', 'Illumination', 'DreamWorks'], 3, 'O filme venceu o primeiro Oscar de Melhor Animação, em 2002.'],
    ['Qual ator interpretou Forrest Gump?', ['Kevin Costner', 'Tom Hanks', 'Robin Williams', 'Michael Douglas'], 1, 'O papel lhe rendeu o segundo Oscar consecutivo de Melhor Ator.'],
    ['Qual filme de 1994 tem Tim Robbins e Morgan Freeman em uma penitenciária?', ['Um Sonho de Liberdade', 'À Espera de um Milagre', 'Os Intocáveis', 'Fuga de Alcatraz'], 0, 'Fracasso de bilheteria na estreia, hoje lidera listas de melhores filmes.'],
    ['Qual é o nome do vilão de "O Silêncio dos Inocentes"?', ['Norman Bates', 'Michael Myers', 'Hannibal Lecter', 'Jack Torrance'], 2, 'Anthony Hopkins ganhou o Oscar aparecendo apenas cerca de 16 minutos em cena.'],
    ['Qual autor escreveu as novelas "Roque Santeiro" e "O Bem-Amado"?', ['Manoel Carlos', 'Gilberto Braga', 'Dias Gomes', 'Aguinaldo Silva'], 2, 'Dias Gomes também é autor da peça "O Pagador de Promessas".'],
    ['Quem dirigiu a trilogia "O Senhor dos Anéis"?', ['Peter Jackson', 'James Cameron', 'Ridley Scott', 'Christopher Nolan'], 0, 'O último filme da trilogia venceu todos os 11 Oscars a que concorreu.'],
    ['Qual filme de Christopher Nolan se passa dentro de sonhos?', ['Interestelar', 'Tenet', 'Amnésia', 'A Origem'], 3, 'O final com o pião girando até hoje divide o público.'],
    ['Qual filme inaugurou a era do cinema falado, em 1927?', ['Metrópolis', 'O Cantor de Jazz', 'Luzes da Cidade', 'Nosferatu'], 1, 'Foi o primeiro longa com diálogos sincronizados a fazer sucesso comercial.'],
  ],
  4: [
    ['Quantas estatuetas do Oscar o filme "Titanic" conquistou?', ['7', '8', '9', '11'], 3, 'Ele empatou com "Ben-Hur" e depois com "O Retorno do Rei" no recorde histórico.'],
    ['Qual foi o primeiro filme brasileiro indicado ao Oscar de Melhor Filme Estrangeiro?', ['Central do Brasil', 'O Pagador de Promessas', 'O Quatrilho', 'Cidade de Deus'], 1, 'A indicação veio em 1963, um ano após o filme vencer em Cannes.'],
    ['Qual filme brasileiro venceu a Palma de Ouro em Cannes, em 1962?', ['Cidade de Deus', 'Central do Brasil', 'O Pagador de Promessas', 'Deus e o Diabo na Terra do Sol'], 2, 'É até hoje o único filme brasileiro a conquistar a Palma de Ouro.'],
    ['Qual cineasta liderou o Cinema Novo com "Deus e o Diabo na Terra do Sol"?', ['Glauber Rocha', 'Nelson Pereira dos Santos', 'Cacá Diegues', 'Ruy Guerra'], 0, 'Ele tinha apenas 25 anos quando dirigiu o filme, em 1964.'],
    ['Qual conceito Glauber Rocha defendeu em seu manifesto de 1965?', ['Cinema de poesia', 'Estética da fome', 'Neorrealismo tropical', 'Cinema de autor puro'], 1, 'A ideia era transformar a precariedade em força estética e política.'],
    ['Qual movimento do cinema italiano influenciou o Cinema Novo brasileiro?', ['Expressionismo alemão', 'Nouvelle Vague', 'Neorrealismo italiano', 'Dogma 95'], 2, 'O neorrealismo filmava nas ruas, com atores não profissionais e orçamento mínimo.'],
    ['Qual movimento francês dos anos 1960 reuniu Godard e Truffaut?', ['Nouvelle Vague', 'Dogma 95', 'Free Cinema', 'Cinema Novo'], 0, 'Os diretores vinham da crítica na revista Cahiers du Cinéma.'],
    ['Qual diretor sueco dirigiu "O Sétimo Selo"?', ['Federico Fellini', 'Michelangelo Antonioni', 'Akira Kurosawa', 'Ingmar Bergman'], 3, 'A cena do cavaleiro jogando xadrez com a Morte é uma das mais citadas do cinema.'],
    ['Qual diretor japonês fez "Os Sete Samurais"?', ['Yasujiro Ozu', 'Kenji Mizoguchi', 'Akira Kurosawa', 'Hayao Miyazaki'], 2, 'O filme de 1954 inspirou o faroeste americano "Sete Homens e um Destino".'],
    ['Qual filme de Federico Fellini retrata a vida noturna de Roma com Marcello Mastroianni?', ['La Dolce Vita', 'Oito e Meio', 'Amarcord', 'A Estrada'], 0, 'O termo "paparazzo" nasceu do nome de um personagem desse filme.'],
    ['Quem dirigiu "2001: Uma Odisseia no Espaço"?', ['Ridley Scott', 'Stanley Kubrick', 'Steven Spielberg', 'George Lucas'], 1, 'O filme de 1968 foi lançado um ano antes da chegada do homem à Lua.'],
    ['Qual é o nome do computador de "2001: Uma Odisseia no Espaço"?', ['Skynet', 'Mother', 'TARS', 'HAL 9000'], 3, 'Cada letra de HAL antecede em uma posição as letras de IBM no alfabeto.'],
    ['Qual atriz tem o maior número de Oscars de atuação?', ['Katharine Hepburn', 'Meryl Streep', 'Ingrid Bergman', 'Frances McDormand'], 0, 'Ela venceu quatro vezes, mas nunca compareceu à cerimônia para receber o prêmio.'],
    ['Quem foi a primeira mulher a vencer o Oscar de Melhor Direção?', ['Sofia Coppola', 'Greta Gerwig', 'Jane Campion', 'Kathryn Bigelow'], 3, 'Ela venceu em 2010 por "Guerra ao Terror".'],
    ['Quem escreveu a novela "Avenida Brasil"?', ['Gilberto Braga', 'João Emanuel Carneiro', 'Manoel Carlos', 'Aguinaldo Silva'], 1, 'O último capítulo, em 2012, parou o país e até adiou compromissos oficiais.'],
    ['Qual foi a primeira telenovela brasileira exibida inteiramente em cores?', ['Selva de Pedra', 'Irmãos Coragem', 'O Bem-Amado', 'Gabriela'], 2, 'Foi ao ar em 1973, na TV Globo.'],
    ['Qual foi a primeira emissora de televisão do Brasil?', ['TV Globo', 'TV Tupi', 'TV Record', 'TV Excelsior'], 1, 'A TV Tupi foi inaugurada por Assis Chateaubriand em São Paulo.'],
    ['Em que ano a televisão começou a funcionar no Brasil?', ['1930', '1940', '1945', '1950'], 3, 'A primeira transmissão oficial ocorreu em 18 de setembro de 1950.'],
    ['Qual apresentador fundou o SBT?', ['Chacrinha', 'Flávio Cavalcanti', 'Silvio Santos', 'Hebe Camargo'], 2, 'Senor Abravanel começou como camelô e vendedor de canetas na rua.'],
    ['Quem realizou a primeira exibição pública de cinema, em 1895?', ['Os irmãos Lumière', 'Thomas Edison', 'Georges Méliès', 'Eadweard Muybridge'], 0, 'A sessão aconteceu em um café de Paris, para 33 espectadores.'],
  ],
  5: [
    ['Qual filme de Georges Méliès mostra uma nave acertando o olho da Lua?', ['A Chegada do Trem', 'O Grande Roubo do Trem', 'Viagem à Lua', 'O Nascimento de uma Nação'], 2, 'O curta de 1902 é um marco dos efeitos especiais no cinema.'],
    ['Qual filme alemão de 1927 é um marco do expressionismo e da ficção científica?', ['O Gabinete do Dr. Caligari', 'Nosferatu', 'M, o Vampiro de Düsseldorf', 'Metrópolis'], 3, 'Dirigido por Fritz Lang, retrata uma cidade dividida entre elite e operários.'],
    ['Qual cineasta soviético desenvolveu a teoria da montagem em "O Encouraçado Potemkin"?', ['Dziga Vertov', 'Sergei Eisenstein', 'Vsevolod Pudovkin', 'Andrei Tarkovski'], 1, 'A sequência da escadaria de Odessa é citada e imitada até hoje.'],
    ['Qual foi o primeiro longa-metragem de animação brasileiro?', ['Sinfonia Amazônica', 'O Menino Maluquinho', 'Cassiopeia', 'Uma História de Amor e Fúria'], 0, 'Lançado em 1953, foi feito quase sozinho por Anélio Latini Filho.'],
    ['Qual animação brasileira foi indicada ao Oscar de Melhor Filme de Animação?', ['O Menino e o Mundo', 'Rio', 'Uma História de Amor e Fúria', 'Tainá'], 0, 'A indicação, em 2016, foi inédita para o Brasil na categoria.'],
    ['Qual atriz estrelou "Dona Flor e Seus Dois Maridos", em 1976?', ['Regina Duarte', 'Sônia Braga', 'Betty Faria', 'Marília Pêra'], 1, 'O filme foi um dos maiores sucessos de público da história do cinema brasileiro.'],
    ['Qual cineasta dirigiu "Limite", clássico experimental brasileiro de 1931?', ['Humberto Mauro', 'Glauber Rocha', 'Alberto Cavalcanti', 'Mário Peixoto'], 3, 'Ele tinha apenas 22 anos e nunca concluiu outro longa-metragem.'],
    ['Qual foi o primeiro filme brasileiro a vencer um Oscar?', ['Central do Brasil', 'Cidade de Deus', 'Ainda Estou Aqui', 'O Pagador de Promessas'], 2, 'A vitória veio na categoria de Melhor Filme Internacional, em 2025.'],
    ['Quem dirigiu "Ainda Estou Aqui"?', ['Fernando Meirelles', 'Walter Salles', 'Kleber Mendonça Filho', 'Anna Muylaert'], 1, 'É o mesmo diretor de "Central do Brasil" e "Diários de Motocicleta".'],
    ['Quem escreveu o livro que deu origem a "Ainda Estou Aqui"?', ['Fernando Gabeira', 'Zuenir Ventura', 'Marcelo Rubens Paiva', 'Ignácio de Loyola Brandão'], 2, 'O livro relata o desaparecimento de seu pai, o deputado Rubens Paiva, na ditadura.'],
    ['Qual filme de Alfred Hitchcock foi montado para parecer um único plano contínuo?', ['Festim Diabólico', 'Janela Indiscreta', 'Intriga Internacional', 'Pacto Sinistro'], 0, 'Os cortes eram disfarçados em movimentos sobre as costas dos atores.'],
    ['Qual diretor é conhecido por planos simétricos e cores pastel em "O Grande Hotel Budapeste"?', ['Tim Burton', 'David Lynch', 'Paul Thomas Anderson', 'Wes Anderson'], 3, 'Seu estilo virou referência estética até fora do cinema.'],
    ['Qual filme venceu o primeiro Oscar de Melhor Filme, em 1929?', ['O Cantor de Jazz', 'Aurora', 'Ben-Hur', 'Asas'], 3, 'O filme mudo sobre pilotos da Primeira Guerra levou o prêmio principal.'],
    ['Qual ator recusou o Oscar de Melhor Ator por "O Poderoso Chefão"?', ['Marlon Brando', 'George C. Scott', 'Al Pacino', 'Dustin Hoffman'], 0, 'Ele enviou uma ativista indígena para recusar o prêmio em protesto, em 1973.'],
    ['Qual série da HBO acompanha a família Roy e a disputa por um império de mídia?', ['Billions', 'The Morning Show', 'Succession', 'Mad Men'], 2, 'A série venceu diversos Emmys entre 2018 e 2023.'],
    ['Qual diretor brasileiro fez "O Som ao Redor"?', ['Karim Aïnouz', 'Kleber Mendonça Filho', 'Marcelo Gomes', 'Lírio Ferreira'], 1, 'O filme de 2012 revelou seu olhar sobre a vida urbana do Recife.'],
    ['Qual filme de Walter Salles acompanha a viagem de um jovem Che Guevara?', ['Diários de Motocicleta', 'Na Estrada', 'Abril Despedaçado', 'Terra Estrangeira'], 0, 'A produção de 2004 venceu o Oscar de Melhor Canção Original.'],
    ['Qual movimento cinematográfico dinamarquês foi criado por Lars von Trier?', ['Nouvelle Vague', 'Dogma 95', 'Free Cinema', 'Neorrealismo'], 1, 'O manifesto proibia trilha sonora externa, cenários construídos e efeitos especiais.'],
    ['Qual filme brasileiro recebeu quatro indicações ao Oscar, incluindo direção, em 2004?', ['Central do Brasil', 'Tropa de Elite', 'Cidade de Deus', 'Carandiru'], 2, 'As indicações vieram dois anos depois do lançamento do filme no Brasil.'],
    ['Qual apresentador brasileiro ficou conhecido como "Velho Guerreiro"?', ['Silvio Santos', 'Flávio Cavalcanti', 'Jô Soares', 'Chacrinha'], 3, 'Abelardo Barbosa jogava abacaxis na plateia e inventou o bordão "Quem não se comunica, se trumbica".'],
  ],
});
