import { montar } from './montar';

/** Curiosidades Gerais — 100 perguntas (20 por nível). */
export const perguntasCuriosidades = montar('curiosidades', {
  1: [
    ['Quantos dias tem o mês de fevereiro em um ano comum?', ['30', '29', '28', '31'], 2, 'Nos anos bissextos, ele ganha um dia a mais.'],
    ['Qual cor do semáforo indica que é preciso parar?', ['vermelho', 'verde', 'amarelo', 'azul'], 0, 'O amarelo é o sinal de atenção.'],
    ['Quantas cores costumam ser citadas no arco-íris?', ['5', '7', '6', '8'], 1, 'Vermelho, laranja, amarelo, verde, azul, anil e violeta.'],
    ['Qual animal é conhecido como "o melhor amigo do homem"?', ['gato', 'cavalo', 'papagaio', 'cachorro'], 3, 'A domesticação dos cães começou há mais de 15 mil anos.'],
    ['Qual prato brasileiro é feito com feijão preto e carnes de porco?', ['feijoada', 'moqueca', 'acarajé', 'vatapá'], 0, 'É tradicionalmente servida às quartas e sábados.'],
    ['Quantos lados tem um pentágono?', ['3', '4', '6', '5'], 3, 'O prefixo grego "penta" significa cinco.'],
    ['Qual bebida é feita a partir de grãos torrados e moídos?', ['chá', 'suco', 'café', 'leite'], 2, 'O Brasil é o maior produtor mundial desse grão.'],
    ['Qual é o animal mais alto do mundo?', ['elefante', 'girafa', 'avestruz', 'camelo'], 1, 'Um macho adulto pode passar dos 5,5 metros de altura.'],
    ['Qual fruta amazônica é consumida como creme gelado no Brasil?', ['manga', 'caju', 'graviola', 'açaí'], 3, 'No Pará, é comum comer açaí salgado, com peixe e farinha.'],
    ['Quantos minutos tem meia hora?', ['15', '30', '45', '60'], 1, 'Metade dos 60 minutos de uma hora.'],
    ['Qual é a cor do losango da bandeira do Brasil?', ['amarelo', 'azul', 'branco', 'vermelho'], 0, 'O losango amarelo aparece sobre o fundo verde.'],
    ['Quantas estrelas há na bandeira do Brasil?', ['22', '26', '27', '30'], 2, 'Cada estrela representa um estado, mais o Distrito Federal.'],
    ['Qual frase está escrita na bandeira do Brasil?', ['Pátria Amada', 'Ordem e Progresso', 'Brasil Unido', 'Liberdade e Justiça'], 1, 'O lema é inspirado no positivismo de Auguste Comte.'],
    ['Qual inseto produz o mel?', ['formiga', 'vespa', 'abelha', 'besouro'], 2, 'Uma abelha produz menos de uma colher de chá de mel em toda a vida.'],
    ['Qual objeto é usado no pulso para ver as horas?', ['bússola', 'termômetro', 'calendário', 'relógio'], 3, 'O relógio de pulso foi popularizado no início do século XX.'],
    ['Qual é a capital do estado de São Paulo?', ['São Paulo', 'Campinas', 'Santos', 'Sorocaba'], 0, 'A cidade e o estado têm o mesmo nome.'],
    ['Qual comida típica de festa junina é feita de milho?', ['pamonha', 'feijoada', 'acarajé', 'coxinha'], 0, 'Curau, canjica e bolo de fubá também levam milho.'],
    ['Quantas patas tem uma aranha?', ['6', '4', '8', '10'], 2, 'Os insetos, por sua vez, têm seis patas.'],
    ['Qual metal precioso de cor amarelada é usado em joias e medalhas?', ['prata', 'ouro', 'cobre', 'platina'], 1, 'Seu símbolo químico é Au.'],
    ['Qual é o satélite natural da Terra?', ['Sol', 'Marte', 'Vênus', 'Lua'], 3, 'Ela está a cerca de 384 mil quilômetros de distância.'],
  ],
  2: [
    ['Qual país é o maior produtor mundial de café?', ['Colômbia', 'Brasil', 'Vietnã', 'Etiópia'], 1, 'O Brasil lidera a produção há mais de 150 anos.'],
    ['Qual prato baiano é feito com massa de feijão-fradinho frita no azeite de dendê?', ['vatapá', 'caruru', 'moqueca', 'acarajé'], 3, 'É vendido tradicionalmente por baianas de tabuleiro.'],
    ['Qual animal é o símbolo da organização ambiental WWF?', ['panda', 'tigre', 'baleia', 'elefante'], 0, 'O logotipo foi criado em 1961, inspirado em uma panda do zoológico de Londres.'],
    ['Qual destes animais não consegue pular?', ['canguru', 'cavalo', 'elefante', 'rinoceronte'], 2, 'O peso e a estrutura das patas impedem que ele tire os quatro pés do chão.'],
    ['Qual prato japonês é feito com arroz temperado e peixe cru?', ['ramen', 'tempurá', 'yakisoba', 'sushi'], 3, 'A maior comunidade japonesa fora do Japão está no Brasil.'],
    ['Qual é a moeda oficial do Japão?', ['yuan', 'iene', 'won', 'rupia'], 1, 'O yuan é chinês; o won, sul-coreano.'],
    ['Qual moeda é usada na maior parte da União Europeia?', ['libra', 'dólar', 'euro', 'franco'], 2, 'Ela entrou em circulação física em 2002.'],
    ['Qual cor resulta da mistura de vermelho com branco?', ['rosa', 'roxo', 'laranja', 'marrom'], 0, 'Adicionar branco a uma cor cria o que se chama de tom pastel.'],
    ['Qual animal marinho tem oito braços?', ['polvo', 'lula', 'estrela-do-mar', 'caranguejo'], 0, 'A lula tem oito braços e mais dois tentáculos.'],
    ['Qual é o ingrediente principal do guacamole?', ['tomate', 'pimentão', 'abacate', 'abobrinha'], 2, 'O prato é originário do México e já era consumido pelos astecas.'],
    ['Quantas casas tem um tabuleiro de xadrez?', ['36', '49', '81', '64'], 3, 'São oito fileiras por oito colunas, alternando claras e escuras.'],
    ['Quantas cartas tem um baralho comum, sem os coringas?', ['50', '52', '54', '48'], 1, 'São quatro naipes de 13 cartas cada.'],
    ['Qual jogo usa peças retangulares marcadas com pontos?', ['xadrez', 'damas', 'dominó', 'truco'], 2, 'É febre nas calçadas e praças do Nordeste brasileiro.'],
    ['Qual parte da planta normalmente fica enterrada?', ['raiz', 'caule', 'folha', 'flor'], 0, 'Ela absorve água e nutrientes e fixa a planta ao solo.'],
    ['Qual é o país mais populoso da América do Sul?', ['Argentina', 'Brasil', 'Colômbia', 'Peru'], 1, 'O Brasil tem mais habitantes que todos os vizinhos somados.'],
    ['Quantas semanas tem um ano?', ['48', '50', '54', '52'], 3, 'São 52 semanas e mais um ou dois dias.'],
    ['Qual é o nome do medo de lugares fechados?', ['acrofobia', 'aracnofobia', 'agorafobia', 'claustrofobia'], 3, 'A agorafobia, ao contrário, é o medo de espaços abertos ou cheios.'],
    ['Qual é o nome do medo de altura?', ['claustrofobia', 'acrofobia', 'agorafobia', 'hidrofobia'], 1, 'Vem do grego "akros", que significa elevado.'],
    ['Qual ave é usada como símbolo da paz?', ['pomba', 'águia', 'coruja', 'andorinha'], 0, 'A imagem da pomba com um ramo de oliveira vem da narrativa bíblica do dilúvio.'],
    ['Qual é o nome da arte japonesa de dobrar papel?', ['ikebana', 'bonsai', 'origami', 'sudoku'], 2, 'O tsuru, um pássaro de papel, é a dobradura mais conhecida.'],
  ],
  3: [
    ['Qual preparo de carne na brasa é tradição no Rio Grande do Sul?', ['churrasco', 'barreado', 'tacacá', 'baião de dois'], 0, 'A carne é assada lentamente em espetos sobre brasas.'],
    ['Qual prato paraense leva tucupi e jambu?', ['vatapá', 'baião de dois', 'tacacá', 'escondidinho'], 2, 'O jambu provoca uma leve dormência na boca.'],
    ['Qual bebida destilada brasileira é feita da cana-de-açúcar?', ['vodca', 'tequila', 'rum', 'cachaça'], 3, 'É a base da caipirinha, drinque conhecido no mundo todo.'],
    ['De qual planta é feita a tequila?', ['cana-de-açúcar', 'agave', 'milho', 'uva'], 1, 'Apenas o agave azul de certas regiões do México pode ser usado.'],
    ['Qual doce brasileiro é feito de leite condensado com chocolate?', ['beijinho', 'quindim', 'brigadeiro', 'cocada'], 2, 'Ele é presença obrigatória em festas de aniversário.'],
    ['Qual político deu nome ao doce brigadeiro?', ['Eduardo Gomes', 'Getúlio Vargas', 'Juscelino Kubitschek', 'Carlos Lacerda'], 0, 'O doce era vendido em festas da campanha presidencial dele, nos anos 1940.'],
    ['Qual flor é símbolo da primavera japonesa?', ['lótus', 'cerejeira', 'crisântemo', 'orquídea'], 1, 'A floração das sakuras dura poucos dias e atrai multidões.'],
    ['Qual mamífero australiano põe ovos?', ['coala', 'canguru', 'vombate', 'ornitorrinco'], 3, 'Ele tem bico de pato, cauda de castor e esporões venenosos.'],
    ['Qual é o nome do filhote de cavalo?', ['bezerro', 'potro', 'leitão', 'cordeiro'], 1, 'A fêmea jovem é chamada de potranca.'],
    ['Qual é o nome do filhote da vaca?', ['potro', 'cordeiro', 'leitão', 'bezerro'], 3, 'O leitão é filhote de porco; o cordeiro, de ovelha.'],
    ['Qual civilização inventou o papel?', ['Egito', 'Índia', 'China', 'Grécia'], 2, 'A invenção é atribuída a Cai Lun, por volta do ano 105.'],
    ['Qual sistema de escrita em relevo é usado por pessoas cegas?', ['braille', 'Libras', 'Morse', 'cirílico'], 0, 'Foi criado pelo francês Louis Braille, ele próprio cego, em 1824.'],
    ['Qual é a língua de sinais oficial do Brasil?', ['braille', 'ASL', 'Morse', 'Libras'], 3, 'A Língua Brasileira de Sinais foi reconhecida por lei em 2002.'],
    ['Qual código usa pontos e traços para transmitir mensagens?', ['braille', 'código Morse', 'código binário', 'alfabeto cirílico'], 1, 'O sinal de socorro SOS é três pontos, três traços e três pontos.'],
    ['Qual é o maior mamífero terrestre nativo da América do Sul?', ['anta', 'capivara', 'onça-pintada', 'lobo-guará'], 0, 'A anta pode pesar mais de 300 quilos e é grande dispersora de sementes.'],
    ['Qual é o maior roedor do mundo?', ['rato-toupeira', 'castor', 'capivara', 'paca'], 2, 'Ela pode chegar a 80 quilos e é comum em áreas alagadas do Brasil.'],
    ['Qual pássaro consegue voar para trás?', ['andorinha', 'tucano', 'beija-flor', 'gaivota'], 2, 'Suas asas batem até 80 vezes por segundo.'],
    ['Qual alimento praticamente não estraga, podendo durar milhares de anos?', ['mel', 'arroz', 'leite', 'pão'], 0, 'Potes de mel encontrados em tumbas egípcias ainda estavam comestíveis.'],
    ['Qual carnaval de rua brasileiro já foi registrado como o maior do mundo pelo Guinness?', ['Carnaval do Rio', 'Carnaval de Veneza', 'Carnaval de Olinda', 'Carnaval de Salvador'], 3, 'Os trios elétricos levam milhões de pessoas às ruas da capital baiana.'],
    ['Qual é a bebida mais consumida no mundo depois da água?', ['café', 'chá', 'cerveja', 'refrigerante'], 1, 'O chá é consumido há mais de 4 mil anos, sobretudo na Ásia.'],
  ],
  4: [
    ['Como se chama o fenômeno em que a Lua encobre totalmente o Sol?', ['eclipse lunar', 'aurora boreal', 'equinócio', 'eclipse solar'], 3, 'Ele só ocorre quando a Lua está exatamente entre a Terra e o Sol.'],
    ['Quantos dias a Lua leva para completar uma volta ao redor da Terra?', ['7', '27', '60', '90'], 1, 'São cerca de 27,3 dias, quase o mesmo tempo que ela leva para girar sobre si mesma.'],
    ['Quem foi a primeira mulher a viajar ao espaço?', ['Sally Ride', 'Mae Jemison', 'Valentina Tereshkova', 'Judith Resnik'], 2, 'A soviética orbitou a Terra 48 vezes em 1963.'],
    ['Quem foi o primeiro brasileiro a ir ao espaço?', ['Marcos Pontes', 'Bartolomeu de Gusmão', 'Alberto Santos Dumont', 'Clóvis Beviláqua'], 0, 'Ele passou oito dias na Estação Espacial Internacional, em 2006.'],
    ['Qual invenção do cotidiano é atribuída a Santos Dumont?', ['o paraquedas', 'o relógio de pulso', 'o telefone', 'o motor a combustão'], 1, 'Ele pediu a um amigo joalheiro um relógio que pudesse ver sem soltar os comandos.'],
    ['Qual foi o avião com que Santos Dumont voou em Paris, em 1906?', ['Demoiselle', 'Dirigível nº 6', '14-Bis', 'Spirit of St. Louis'], 2, 'O voo foi o primeiro homologado por uma entidade aeronáutica oficial.'],
    ['Qual é o maior diamante bruto já encontrado no mundo?', ['Cullinan', 'Koh-i-Noor', 'Hope', 'Estrela do Sul'], 0, 'Descoberto na África do Sul em 1905, pesava mais de 3.100 quilates.'],
    ['Qual é o substantivo coletivo de peixes?', ['manada', 'alcateia', 'matilha', 'cardume'], 3, 'Manada é de bois e elefantes; alcateia, de lobos.'],
    ['Qual ave não voa e vive no hemisfério sul, inclusive na Antártida?', ['avestruz', 'ema', 'pinguim', 'kiwi'], 2, 'Suas asas viraram nadadeiras: ele "voa" debaixo d’água.'],
    ['Qual é o maior felino das Américas?', ['onça-pintada', 'puma', 'jaguatirica', 'lince'], 0, 'Ela tem a mordida mais forte entre os grandes felinos em relação ao tamanho.'],
    ['Qual é a velocidade aproximada do som no ar?', ['100 m/s', '340 m/s', '1.000 m/s', '3.000 m/s'], 1, 'Por isso vemos o relâmpago antes de ouvir o trovão.'],
    ['Como se chama o estrondo produzido quando uma aeronave ultrapassa a velocidade do som?', ['efeito Doppler', 'ressonância', 'eco', 'barreira do som'], 3, 'Chuck Yeager foi o primeiro a rompê-la, em 1947.'],
    ['Qual era a moeda de Portugal antes do euro?', ['escudo', 'peseta', 'lira', 'franco'], 0, 'A peseta era da Espanha, e a lira, da Itália.'],
    ['Qual foi a moeda brasileira imediatamente anterior ao real?', ['cruzeiro', 'cruzado', 'cruzado novo', 'cruzeiro real'], 3, 'Ela circulou por menos de um ano, entre 1993 e 1994.'],
    ['Qual documento é obrigatório para dirigir no Brasil?', ['RG', 'CNH', 'CPF', 'CTPS'], 1, 'A Carteira Nacional de Habilitação tem validade de alguns anos e precisa ser renovada.'],
    ['Qual cor de bandeira é usada tradicionalmente para sinalizar rendição?', ['preta', 'vermelha', 'branca', 'amarela'], 2, 'O uso é reconhecido pelas Convenções de Genebra.'],
    ['Qual é o telefone da Polícia Militar no Brasil?', ['192', '190', '193', '199'], 1, 'O 192 é do Samu e o 193, do Corpo de Bombeiros.'],
    ['Qual número aciona o Corpo de Bombeiros no Brasil?', ['190', '192', '199', '193'], 3, 'A Defesa Civil atende pelo 199.'],
    ['Quantos anos têm, respectivamente, um século e um milênio?', ['10 e 100', '50 e 500', '100 e 1.000', '100 e 500'], 2, 'Uma década, por sua vez, corresponde a dez anos.'],
    ['Qual pedra preciosa é conhecida por sua cor verde intensa?', ['esmeralda', 'safira', 'rubi', 'topázio'], 0, 'O Brasil é um dos maiores produtores mundiais dessa gema.'],
  ],
  5: [
    ['Qual é o maior animal invertebrado do mundo?', ['polvo-gigante', 'água-viva-juba-de-leão', 'lula-gigante', 'caranguejo-aranha'], 2, 'Ela pode passar de 13 metros e só foi filmada viva em 2012.'],
    ['Qual é a espécie de árvore mais alta do mundo?', ['baobá', 'eucalipto', 'samaúma', 'sequoia'], 3, 'A maior delas, chamada Hyperion, passa dos 115 metros de altura.'],
    ['Qual foi o primeiro animal a orbitar a Terra?', ['Ham', 'Laika', 'Belka', 'Félicette'], 1, 'A cadela soviética foi lançada a bordo da Sputnik 2, em 1957.'],
    ['Qual foi o primeiro país a conceder o direito de voto às mulheres?', ['Nova Zelândia', 'Estados Unidos', 'Reino Unido', 'Finlândia'], 0, 'A conquista veio em 1893, 39 anos antes do Brasil.'],
    ['Qual país tem o maior número de línguas faladas?', ['Papua-Nova Guiné', 'Índia', 'Indonésia', 'Nigéria'], 0, 'São mais de 800 idiomas em um país de cerca de 10 milhões de habitantes.'],
    ['Qual é a palavra mais longa registrada em dicionários de língua portuguesa?', ['anticonstitucionalissimamente', 'pneumoultramicroscopicossilicovulcanoconiótico', 'otorrinolaringologista', 'inconstitucionalidade'], 1, 'Com 46 letras, designa uma doença pulmonar causada por poeira de sílica.'],
    ['Qual instrumento mede a velocidade do vento?', ['barômetro', 'higrômetro', 'pluviômetro', 'anemômetro'], 3, 'Ele costuma ter conchas que giram com a passagem do ar.'],
    ['Qual instrumento mede a quantidade de chuva?', ['anemômetro', 'higrômetro', 'pluviômetro', 'barômetro'], 2, 'A medida é dada em milímetros de altura de água acumulada.'],
    ['Qual é a origem da palavra "salário"?', ['do trabalho no campo', 'do pagamento em sal feito a soldados romanos', 'do nome de uma moeda grega', 'do latim para "esforço"'], 1, 'O sal era um produto valioso, usado para conservar alimentos.'],
    ['No Brasil, a que peso corresponde uma arroba, mesma palavra usada para o símbolo @?', ['10 kg', '12 kg', '15 kg', '20 kg'], 2, 'A unidade ainda é usada no comércio de gado.'],
    ['Qual é o maior meteorito já encontrado em território brasileiro?', ['Bendegó', 'Angra dos Reis', 'Santa Luzia', 'Campo do Cielo'], 0, 'Com mais de cinco toneladas, ele sobreviveu ao incêndio do Museu Nacional em 2018.'],
    ['Qual objeto do cotidiano Walter Hunt inventou em poucas horas, em 1849?', ['zíper', 'clipe de papel', 'grampeador', 'alfinete de segurança'], 3, 'Ele vendeu a patente por 400 dólares para quitar uma dívida.'],
    ['Quem foi o primeiro explorador a chegar ao Polo Sul?', ['Robert Scott', 'Ernest Shackleton', 'Richard Byrd', 'Roald Amundsen'], 3, 'O norueguês chegou em dezembro de 1911, cinco semanas antes de Scott.'],
    ['Como é chamado o fenômeno em que o Sol não se põe durante o verão polar?', ['sol da meia-noite', 'aurora boreal', 'solstício branco', 'noite polar'], 0, 'No inverno acontece o contrário: o Sol não nasce por semanas.'],
    ['Quantos quilos tem uma tonelada?', ['100', '500', '1.000', '10.000'], 2, 'A tonelada é a unidade usada para cargas e produção agrícola.'],
    ['Quantos mililitros tem um litro?', ['100', '1.000', '10', '10.000'], 1, 'O prefixo "mili" indica a milésima parte.'],
    ['Qual sistema de medidas é oficial no Brasil?', ['Sistema Internacional, métrico', 'sistema imperial', 'sistema britânico', 'sistema decimal americano'], 0, 'O metro, o quilograma e o segundo são algumas de suas unidades básicas.'],
    ['Qual país ainda usa oficialmente o sistema imperial, com milhas e libras?', ['Canadá', 'Estados Unidos', 'Austrália', 'França'], 1, 'Mianmar e Libéria são os outros dois países que não adotaram plenamente o sistema métrico.'],
    ['Qual é a origem mais aceita para o nome "Brasil"?', ['o sobrenome de um rei português', 'o nome de uma tribo indígena', 'a árvore pau-brasil', 'uma ilha mítica dos celtas'], 2, 'A madeira, chamada "brasa" pela cor avermelhada, foi o primeiro produto explorado aqui.'],
    ['Qual é o nome oficial do país?', ['Estados Unidos do Brasil', 'União Brasileira', 'Reino do Brasil', 'República Federativa do Brasil'], 3, 'O nome foi adotado pela Constituição de 1967 e mantido em 1988.'],
  ],
});
