import { montar } from './montar';

/** Esportes — 100 perguntas (20 por nível). */
export const perguntasEsportes = montar('esportes', {
  1: [
    ['De quantos em quantos anos acontecem os Jogos Olímpicos de verão?', ['2', '3', '4', '5'], 2, 'Os Jogos de Inverno também são a cada quatro anos, alternados com os de verão.'],
    ['Quantos jogadores de cada time ficam em quadra no vôlei?', ['6', '5', '7', '11'], 0, 'Um deles pode ser o líbero, especialista em defesa.'],
    ['Quantos jogadores de cada time ficam em quadra no basquete?', ['4', '5', '6', '7'], 1, 'As cinco posições clássicas vão do armador ao pivô.'],
    ['Em qual esporte se usa raquete e uma bolinha amarela em quadra dividida por rede?', ['tênis de mesa', 'badminton', 'squash', 'tênis'], 3, 'A bola amarela foi adotada nos anos 1970 para facilitar a visualização na TV.'],
    ['Qual era o esporte de Ayrton Senna?', ['automobilismo', 'motociclismo', 'ciclismo', 'atletismo'], 0, 'Senna foi tricampeão mundial de Fórmula 1 em 1988, 1990 e 1991.'],
    ['Quantos anéis formam o símbolo olímpico?', ['3', '4', '6', '5'], 3, 'Eles representam os cinco continentes habitados.'],
    ['Qual esporte é jogado com tacos, uma bolinha e buracos no gramado?', ['beisebol', 'críquete', 'golfe', 'hóquei'], 2, 'O objetivo é completar o percurso com o menor número de tacadas.'],
    ['Em qual esporte Gustavo Kuerten, o Guga, fez sucesso?', ['vôlei', 'tênis', 'natação', 'judô'], 1, 'Ele chegou a ser o número 1 do ranking mundial em 2000.'],
    ['Quantos jogadores de cada time ficam em quadra no futsal?', ['4', '6', '7', '5'], 3, 'São quatro jogadores de linha e um goleiro.'],
    ['Qual medalha é entregue ao primeiro colocado nas Olimpíadas?', ['prata', 'ouro', 'bronze', 'platina'], 1, 'As medalhas de ouro atuais são de prata com banho de ouro.'],
    ['Qual destes esportes é praticado em uma piscina?', ['natação', 'judô', 'boxe', 'esgrima'], 0, 'Polo aquático e nado artístico também são disputados na água.'],
    ['Qual é o país de origem do judô?', ['China', 'Coreia do Sul', 'Japão', 'Brasil'], 2, 'A modalidade foi criada por Jigoro Kano em 1882.'],
    ['Em quantos períodos é dividida uma partida de basquete na NBA?', ['2', '4', '3', '5'], 1, 'Cada quarto tem 12 minutos na liga americana.'],
    ['Qual esporte usa uma bola laranja e uma cesta a mais de três metros do chão?', ['vôlei', 'handebol', 'basquete', 'futsal'], 2, 'A cesta fica a 3,05 metros de altura.'],
    ['Qual é a distância aproximada de uma maratona?', ['triatlo', 'meia-maratona', 'cross-country', 'maratona'], 3, 'A prova tem 42,195 quilômetros — e "maratona" é o nome dessa corrida.'],
    ['Qual esporte olímpico é uma luta disputada com quimono e faixas coloridas?', ['judô', 'boxe', 'esgrima', 'levantamento de peso'], 0, 'No Brasil, o judô é a modalidade que mais rendeu medalhas olímpicas.'],
    ['Quantos pontos vale uma cesta de três no basquete?', ['3', '2', '1', '4'], 0, 'Os lances livres valem um ponto cada.'],
    ['Em qual esporte os atletas usam luvas e disputam em um ringue?', ['karatê', 'judô', 'boxe', 'esgrima'], 2, 'As lutas são divididas em rounds de três minutos no profissional.'],
    ['Qual país sediou os Jogos Olímpicos de 2016?', ['Estados Unidos', 'Brasil', 'Japão', 'Grécia'], 1, 'Foi a primeira vez que a América do Sul recebeu a Olimpíada.'],
    ['Como se chama o ataque forte no vôlei, batendo a bola para baixo?', ['bloqueio', 'saque', 'levantamento', 'cortada'], 3, 'Também é chamada de "spike" ou "ataque".'],
  ],
  2: [
    ['Em qual cidade nasceram os Jogos Olímpicos da Antiguidade?', ['Atenas', 'Olímpia', 'Esparta', 'Roma'], 1, 'Os jogos eram realizados em honra ao deus Zeus, a partir de 776 a.C.'],
    ['Quantos pontos são necessários para vencer um set no vôlei, exceto o quinto?', ['15', '21', '30', '25'], 3, 'É preciso ainda ter dois pontos de vantagem sobre o adversário.'],
    ['Em qual Olimpíada o vôlei masculino brasileiro conquistou seu primeiro ouro?', ['Barcelona 1992', 'Atlanta 1996', 'Sydney 2000', 'Atenas 2004'], 0, 'A seleção venceu a Holanda na final, com Marcelo Negrão e Tande em quadra.'],
    ['Qual piloto brasileiro foi tricampeão mundial de Fórmula 1 e morreu em 1994?', ['Nelson Piquet', 'Emerson Fittipaldi', 'Ayrton Senna', 'Rubens Barrichello'], 2, 'O acidente fatal ocorreu no GP de San Marino, em Ímola.'],
    ['Quantos títulos mundiais de Fórmula 1 Nelson Piquet conquistou?', ['1', '2', '4', '3'], 3, 'Os títulos vieram em 1981, 1983 e 1987.'],
    ['Qual torneio de tênis é disputado na grama, em Londres?', ['Roland Garros', 'Wimbledon', 'US Open', 'Australian Open'], 1, 'É o mais antigo torneio de tênis do mundo, disputado desde 1877.'],
    ['Em qual superfície é disputado o torneio de Roland Garros?', ['grama', 'quadra dura', 'saibro', 'carpete'], 2, 'O saibro deixa o jogo mais lento e favorece longos ralis.'],
    ['Em qual modalidade Robert Scheidt conquistou cinco medalhas olímpicas?', ['vela', 'natação', 'judô', 'atletismo'], 0, 'Ele competiu nas classes Laser e Star ao longo de sete Olimpíadas.'],
    ['Qual esporte combina natação, ciclismo e corrida?', ['triatlo', 'pentatlo moderno', 'decatlo', 'biatlo'], 0, 'A versão olímpica tem 1,5 km de natação, 40 km de bike e 10 km de corrida.'],
    ['Quantas provas compõem o decatlo?', ['5', '7', '10', '12'], 2, 'São disputadas em dois dias, e o vencedor é considerado o atleta mais completo.'],
    ['Qual país é o maior vencedor de medalhas na história das Olimpíadas?', ['China', 'Rússia', 'Alemanha', 'Estados Unidos'], 3, 'Os americanos passam de mil medalhas de ouro somando todas as edições.'],
    ['Qual esporte tem as posições de armador, ala e pivô?', ['vôlei', 'basquete', 'handebol', 'futsal'], 1, 'O armador é quem organiza as jogadas de ataque.'],
    ['Qual é a principal liga de basquete dos Estados Unidos?', ['MLB', 'NFL', 'NBA', 'NHL'], 2, 'A liga foi fundada em 1946 e tem 30 franquias.'],
    ['Qual esporte é conhecido como "o esporte bretão"?', ['futebol', 'rúgbi', 'críquete', 'golfe'], 0, 'O apelido vem da Grã-Bretanha, onde o futebol foi regulamentado em 1863.'],
    ['Qual é a prova mais curta e veloz do atletismo olímpico?', ['400 metros', '100 metros rasos', 'salto em distância', 'revezamento 4x400'], 1, 'O campeão dos 100 metros costuma ser chamado de "homem mais rápido do mundo".'],
    ['Qual jamaicano é considerado o homem mais rápido da história?', ['Carl Lewis', 'Asafa Powell', 'Yohan Blake', 'Usain Bolt'], 3, 'Ele detém os recordes mundiais dos 100 e dos 200 metros.'],
    ['Qual esporte usa termos como "strike" e "home run"?', ['críquete', 'boliche', 'golfe', 'beisebol'], 3, 'É o esporte nacional dos Estados Unidos e muito popular no Japão.'],
    ['Qual é o país de origem do caratê?', ['China', 'Japão', 'Coreia do Sul', 'Tailândia'], 1, 'A modalidade nasceu na ilha de Okinawa.'],
    ['Qual arte marcial olímpica tem origem coreana?', ['taekwondo', 'judô', 'caratê', 'kung fu'], 0, 'O nome significa, aproximadamente, "o caminho dos pés e das mãos".'],
    ['Como se chamam os Jogos Olímpicos disputados por atletas com deficiência?', ['Jogos Mundiais', 'Universíade', 'Paralimpíadas', 'Jogos Pan-Americanos'], 2, 'Acontecem logo após a Olimpíada, na mesma cidade-sede.'],
  ],
  3: [
    ['Quem conquistou a primeira medalha de ouro olímpica do Brasil, em 1920?', ['Guilherme Paraense', 'Adhemar Ferreira da Silva', 'Maria Lenk', 'Éder Jofre'], 0, 'A conquista veio no tiro esportivo, nos Jogos da Antuérpia.'],
    ['Qual atleta brasileiro venceu o salto triplo em 1952 e 1956?', ['Joaquim Cruz', 'João Carlos de Oliveira', 'Adhemar Ferreira da Silva', 'Nelson Prudêncio'], 2, 'Ele bateu recordes mundiais e ainda atuou como ator no cinema.'],
    ['Qual brasileiro ganhou o ouro nos 800 metros em Los Angeles 1984?', ['Robson Caetano', 'Vanderlei Cordeiro de Lima', 'Cláudio Roberto', 'Joaquim Cruz'], 3, 'Até hoje é o único ouro olímpico do Brasil em provas de pista.'],
    ['Qual maratonista brasileiro foi agarrado por um invasor durante a prova em 2004?', ['Marilson Gomes dos Santos', 'Vanderlei Cordeiro de Lima', 'Ronaldo da Costa', 'Franck Caldeira'], 1, 'Mesmo assim ele terminou em terceiro e ganhou a medalha Pierre de Coubertin.'],
    ['Qual é a distância exata de uma maratona?', ['40 km', '41,195 km', '42,195 km', '45 km'], 2, 'A distância foi fixada nos Jogos de Londres de 1908.'],
    ['Em quais Olimpíadas o vôlei feminino brasileiro conquistou o ouro?', ['Pequim 2008 e Londres 2012', 'Atenas 2004 e Pequim 2008', 'Londres 2012 e Rio 2016', 'Sydney 2000 e Atenas 2004'], 0, 'Foram dois títulos seguidos, comandados pelo técnico José Roberto Guimarães.'],
    ['Qual esporte revelou as brasileiras Hortência e Magic Paula?', ['vôlei', 'basquete', 'handebol', 'futsal'], 1, 'Elas foram campeãs mundiais em 1994, na Austrália.'],
    ['Quantos títulos mundiais de Fórmula 1 Michael Schumacher conquistou?', ['5', '6', '8', '7'], 3, 'Foram dois pela Benetton e cinco consecutivos pela Ferrari.'],
    ['Qual piloto brasileiro foi bicampeão mundial de Fórmula 1 nos anos 1970?', ['Nelson Piquet', 'Emerson Fittipaldi', 'Ayrton Senna', 'José Carlos Pace'], 1, 'Ele venceu em 1972 e 1974, sendo o primeiro brasileiro campeão da categoria.'],
    ['Qual é o nome do autódromo de Fórmula 1 em São Paulo?', ['Jacarepaguá', 'Goiânia', 'Tarumã', 'Interlagos'], 3, 'O nome oficial é Autódromo José Carlos Pace.'],
    ['Qual tenista brasileiro venceu Roland Garros três vezes?', ['Thomaz Koch', 'Fernando Meligeni', 'Gustavo Kuerten', 'Marcelo Melo'], 2, 'Os títulos vieram em 1997, 2000 e 2001.'],
    ['Qual Grand Slam do tênis é disputado na Austrália?', ['Australian Open', 'Wimbledon', 'US Open', 'Roland Garros'], 0, 'É o primeiro grande torneio do calendário, em janeiro.'],
    ['Quantos torneios formam o Grand Slam do tênis?', ['2', '3', '5', '4'], 3, 'Australian Open, Roland Garros, Wimbledon e US Open.'],
    ['Qual boxeador brasileiro foi campeão mundial nos anos 1960?', ['Maguila', 'Éder Jofre', 'Acelino Popó', 'Servílio de Oliveira'], 1, 'Conhecido como "Galo de Ouro", é considerado o maior boxeador brasileiro.'],
    ['Qual manifestação brasileira mistura luta, dança e música?', ['capoeira', 'jiu-jítsu', 'vale-tudo', 'huka-huka'], 0, 'Criada por africanos escravizados, foi proibida por lei até 1940.'],
    ['Qual família brasileira é associada à criação do jiu-jítsu brasileiro?', ['Nogueira', 'Silva', 'Gracie', 'Machado'], 2, 'Carlos e Hélio Gracie adaptaram o jiu-jítsu japonês no início do século XX.'],
    ['Qual é o maior evento de MMA do mundo?', ['Bellator', 'Pride', 'UFC', 'One Championship'], 2, 'A primeira edição aconteceu em 1993, com Royce Gracie campeão.'],
    ['Qual nadador é o maior medalhista olímpico da história?', ['Michael Phelps', 'Mark Spitz', 'Ian Thorpe', 'Caeleb Dressel'], 0, 'Ele soma 28 medalhas olímpicas, sendo 23 de ouro.'],
    ['Qual nadador brasileiro conquistou o ouro nos 50 metros livre em 2008?', ['Gustavo Borges', 'Fernando Scherer', 'Thiago Pereira', 'Cesar Cielo'], 3, 'Foi o primeiro ouro olímpico do Brasil na natação.'],
    ['Contra qual seleção o Brasil venceu a final do futebol masculino na Olimpíada de 2016?', ['Argentina', 'Alemanha', 'México', 'Espanha'], 1, 'A decisão foi nos pênaltis, com gol de Neymar na cobrança final.'],
  ],
  4: [
    ['Em que ano foram realizados os primeiros Jogos Olímpicos da era moderna?', ['1888', '1892', '1900', '1896'], 3, 'A primeira edição reuniu 14 países em Atenas.'],
    ['Quem idealizou os Jogos Olímpicos modernos?', ['Demetrius Vikelas', 'Pierre de Coubertin', 'Avery Brundage', 'Juan Antonio Samaranch'], 1, 'O barão francês fundou o Comitê Olímpico Internacional em 1894.'],
    ['Qual é o lema olímpico tradicional?', ['Mais forte, mais unido, mais veloz', 'Paz e esporte', 'Mais rápido, mais alto, mais forte', 'União entre os povos'], 2, 'Em latim: "Citius, Altius, Fortius". Em 2021 foi acrescentado "Communis".'],
    ['Qual cidade sediou os primeiros Jogos Olímpicos modernos?', ['Atenas', 'Paris', 'Londres', 'Roma'], 0, 'A escolha homenageou a Grécia, berço dos jogos antigos.'],
    ['Qual atleta venceu quatro provas nos Jogos de Berlim, em 1936?', ['Carl Lewis', 'Jesse Owens', 'Paavo Nurmi', 'Emil Zátopek'], 1, 'Suas vitórias desmentiram na prática a propaganda racial nazista.'],
    ['Qual país liderou o boicote aos Jogos de Moscou, em 1980?', ['União Soviética', 'Cuba', 'Estados Unidos', 'Alemanha Oriental'], 2, 'A URSS revidou boicotando os Jogos de Los Angeles, em 1984.'],
    ['Qual é a mais famosa competição de ciclismo do mundo?', ['Tour de France', 'Giro d’Italia', 'Vuelta a España', 'Paris-Roubaix'], 0, 'A prova acontece desde 1903 e dura cerca de três semanas.'],
    ['Qual competição de rúgbi é disputada a cada quatro anos?', ['Seis Nações', 'Super Rugby', 'The Rugby Championship', 'Copa do Mundo de Rúgbi'], 3, 'A primeira edição foi em 1987, na Nova Zelândia e na Austrália.'],
    ['Qual é a liga de futebol americano dos Estados Unidos?', ['MLS', 'NBA', 'NFL', 'MLB'], 2, 'A MLS é de futebol e a MLB, de beisebol.'],
    ['Como se chama a partida final da liga de futebol americano?', ['Super Bowl', 'World Series', 'Stanley Cup', 'All-Star Game'], 0, 'É um dos eventos de TV mais assistidos do mundo todos os anos.'],
    ['Qual é o troféu da principal liga de hóquei no gelo da América do Norte?', ['Larry O’Brien', 'Stanley Cup', 'Vince Lombardi', 'Commissioner’s Trophy'], 1, 'A taça existe desde 1893 e traz gravado o nome de cada campeão.'],
    ['Qual modalidade olímpica de inverno combina esqui cross-country e tiro?', ['pentatlo moderno', 'esqui alpino', 'patinação de velocidade', 'biatlo'], 3, 'Os atletas precisam controlar a respiração para acertar os alvos.'],
    ['Qual ginasta brasileira conquistou o ouro no solo nos Jogos de Paris, em 2024?', ['Rebeca Andrade', 'Daiane dos Santos', 'Jade Barbosa', 'Flávia Saraiva'], 0, 'Ela se tornou a maior medalhista olímpica da história do Brasil.'],
    ['Qual elemento da ginástica artística leva o nome de uma brasileira?', ['Produnova', 'Yurchenko', 'Amanar', 'Dos Santos'], 3, 'Daiane dos Santos criou o duplo twist carpado, inscrito no código em 2003.'],
    ['Qual velocista estabeleceu o recorde mundial dos 100 metros com 9s58?', ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Asafa Powell'], 1, 'A marca foi feita no Mundial de Berlim, em 2009.'],
    ['Em que ano o Rio de Janeiro sediou os Jogos Pan-Americanos?', ['1999', '2003', '2007', '2011'], 2, 'A estrutura construída então foi reaproveitada na Olimpíada de 2016.'],
    ['Em qual esporte existe a prova do salto com vara?', ['natação', 'atletismo', 'ginástica artística', 'ciclismo'], 1, 'O recorde mundial masculino já passou dos 6,20 metros.'],
    ['Qual é o peso do disco usado no atletismo masculino adulto?', ['500 g', '1 kg', '1,5 kg', '2 kg'], 3, 'No feminino, o disco pesa 1 quilo.'],
    ['Qual pontuação encerra imediatamente uma luta de judô?', ['waza-ari', 'yuko', 'ippon', 'koka'], 2, 'O ippon equivale a um nocaute: a luta acaba na hora.'],
    ['Quantos títulos olímpicos o vôlei masculino brasileiro conquistou?', ['3', '2', '4', '1'], 0, 'Os ouros vieram em 1992, 2004 e 2016.'],
  ],
  5: [
    ['Quem foi o primeiro brasileiro campeão mundial de boxe?', ['Maguila', 'Acelino Popó', 'Éder Jofre', 'Miguel de Oliveira'], 2, 'Ele conquistou o cinturão dos galos em 1960.'],
    ['Qual velejador brasileiro subiu ao pódio olímpico em cinco edições dos Jogos?', ['Lars Grael', 'Marcelo Ferreira', 'Martine Grael', 'Robert Scheidt'], 3, 'Ele estreou em Atlanta 1996 e seguiu competindo por mais de 20 anos.'],
    ['Quem foi a primeira mulher brasileira a competir em Jogos Olímpicos?', ['Adhemar Ferreira da Silva', 'Maria Lenk', 'Maria Esther Bueno', 'Hortência'], 1, 'A nadadora competiu em Los Angeles 1932 e depois virou recordista mundial.'],
    ['Qual tenista brasileira venceu Wimbledon nos anos 1960?', ['Maria Esther Bueno', 'Suzana Petersen', 'Niege Dias', 'Patrícia Medrado'], 0, 'Ela conquistou 19 títulos de Grand Slam somando simples e duplas.'],
    ['Qual país africano conquistou o ouro na maratona com Abebe Bikila, que correu descalço?', ['Etiópia', 'Quênia', 'Marrocos', 'Uganda'], 0, 'A façanha aconteceu nas ruas de Roma, em 1960.'],
    ['Qual corredor queniano completou uma maratona em menos de duas horas, em evento especial?', ['Kenenisa Bekele', 'Eliud Kipchoge', 'Haile Gebrselassie', 'Wilson Kipsang'], 1, 'A marca, feita em Viena em 2019, não vale como recorde oficial.'],
    ['Qual corrida de Fórmula 1 é disputada nas ruas de um principado europeu?', ['GP da Itália', 'GP da Bélgica', 'GP da Espanha', 'GP de Mônaco'], 3, 'O circuito é o mais lento e estreito do calendário, disputado desde 1929.'],
    ['Qual piloto igualou Michael Schumacher no recorde de títulos mundiais de Fórmula 1?', ['Sebastian Vettel', 'Fernando Alonso', 'Lewis Hamilton', 'Max Verstappen'], 2, 'Ambos somam sete campeonatos.'],
    ['Qual brasileiro venceu quatro vezes as 500 Milhas de Indianápolis?', ['Emerson Fittipaldi', 'Hélio Castroneves', 'Gil de Ferran', 'Tony Kanaan'], 1, 'Ele comemora escalando o alambrado, o que lhe rendeu o apelido de "Spiderman".'],
    ['Qual Grand Slam encerra a temporada do tênis?', ['Australian Open', 'Roland Garros', 'US Open', 'Wimbledon'], 2, 'É disputado em Nova York, entre agosto e setembro.'],
    ['Qual tenista tem o maior número de títulos de Grand Slam no masculino?', ['Novak Djokovic', 'Rafael Nadal', 'Roger Federer', 'Pete Sampras'], 0, 'O sérvio ultrapassou a marca de 20 títulos em 2023.'],
    ['Qual esporte olímpico foi criado por um professor canadense em 1891?', ['vôlei', 'handebol', 'hóquei', 'basquete'], 3, 'James Naismith usou cestos de pêssego pregados na parede do ginásio.'],
    ['Quem inventou o vôlei, em 1895?', ['James Naismith', 'Pierre de Coubertin', 'Walter Camp', 'William Morgan'], 3, 'Ele buscava um esporte menos violento que o basquete para adultos.'],
    ['Qual é a altura da rede no vôlei masculino adulto?', ['2,43 m', '2,24 m', '2,50 m', '2,10 m'], 0, 'No feminino, a rede fica a 2,24 metros.'],
    ['A que altura fica o aro de basquete?', ['2,75 m', '3,00 m', '3,05 m', '3,20 m'], 2, 'A medida corresponde a 10 pés, herdada da criação do esporte nos Estados Unidos.'],
    ['Quantos buracos tem um campo de golfe oficial?', ['9', '18', '24', '36'], 1, 'O padrão foi definido pelo campo de St Andrews, na Escócia.'],
    ['Qual torneio de golfe entrega ao campeão um paletó verde?', ['Masters de Augusta', 'US Open', 'The Open', 'PGA Championship'], 0, 'A tradição do "green jacket" começou em 1949.'],
    ['Qual é o comprimento de uma piscina olímpica?', ['25 metros', '50 metros', '100 metros', '33 metros'], 1, 'As piscinas de 25 metros são chamadas de piscina curta.'],
    ['Qual é o estilo mais veloz da natação?', ['costas', 'peito', 'crawl', 'borboleta'], 2, 'Por isso ele é o preferido nas provas de nado livre.'],
    ['Qual esporte paralímpico usa uma bola com guizos e atletas com venda nos olhos?', ['vôlei sentado', 'bocha', 'rúgbi em cadeira de rodas', 'goalball'], 3, 'O silêncio da torcida é obrigatório durante as jogadas.'],
  ],
});
