import { montar } from './montar';

/** Física e Química — 100 perguntas (20 por nível). */
export const perguntasFisicaQuimica = montar('fisica-quimica', {
  1: [
    ['Qual é a fórmula química da água?', ['CO2', 'O2', 'H2O', 'NaCl'], 2, 'Cada molécula tem dois átomos de hidrogênio ligados a um de oxigênio.'],
    ['Qual cientista formulou a lei da gravitação universal?', ['Isaac Newton', 'Albert Einstein', 'Galileu Galilei', 'Nikola Tesla'], 0, 'A história da maçã é provavelmente lenda, mas a lei de 1687 mudou a ciência.'],
    ['A que temperatura a água ferve ao nível do mar?', ['50 °C', '100 °C', '150 °C', '80 °C'], 1, 'Em cidades altas, como La Paz, a água ferve a menos de 90 °C.'],
    ['Em que estado está a água a 10 graus abaixo de zero?', ['Líquido', 'Gasoso', 'Plasma', 'Sólido'], 3, 'A água congela a 0 °C e é uma das poucas substâncias que se expandem ao congelar.'],
    ['Qual gás é usado para encher balões que sobem no ar?', ['Hélio', 'Oxigênio', 'Nitrogênio', 'Gás carbônico'], 0, 'O hélio é mais leve que o ar e, ao contrário do hidrogênio, não é inflamável.'],
    ['Qual é o símbolo químico do ouro?', ['Or', 'Ou', 'Go', 'Au'], 3, 'A sigla vem do latim "aurum".'],
    ['Qual escala de temperatura é usada no dia a dia no Brasil?', ['Fahrenheit', 'Kelvin', 'Celsius', 'Rankine'], 2, 'A escala Celsius define 0 grau para o congelamento e 100 para a fervura da água.'],
    ['Qual força puxa os objetos em direção ao centro da Terra?', ['Magnetismo', 'Gravidade', 'Atrito', 'Eletricidade'], 1, 'É a mesma força que mantém a Lua em órbita ao redor do planeta.'],
    ['Qual astro fornece luz e calor à Terra?', ['A Lua', 'Vênus', 'Júpiter', 'O Sol'], 3, 'A luz do Sol leva cerca de oito minutos para chegar até nós.'],
    ['Qual instrumento mede a temperatura?', ['Barômetro', 'Termômetro', 'Higrômetro', 'Amperímetro'], 1, 'O barômetro mede pressão; o higrômetro, umidade do ar.'],
    ['Qual metal é líquido à temperatura ambiente?', ['Mercúrio', 'Ferro', 'Chumbo', 'Alumínio'], 0, 'Por ser tóxico, o mercúrio foi substituído nos termômetros modernos.'],
    ['Qual é o gás mais abundante na atmosfera terrestre?', ['Oxigênio', 'Gás carbônico', 'Nitrogênio', 'Hidrogênio'], 2, 'O nitrogênio representa cerca de 78% do ar que respiramos.'],
    ['Como se chama a passagem do estado líquido para o gasoso?', ['Fusão', 'Evaporação', 'Condensação', 'Solidificação'], 1, 'É o que acontece com a água das roupas no varal.'],
    ['Qual é a menor partícula que caracteriza um elemento químico?', ['Molécula', 'Célula', 'Átomo', 'Cristal'], 2, 'A palavra átomo vem do grego e significa "indivisível".'],
    ['Qual unidade aparece na conta de luz para medir o consumo?', ['Volt', 'Ampère', 'Watt', 'Quilowatt-hora'], 3, 'Um quilowatt-hora equivale a manter um aparelho de mil watts ligado por uma hora.'],
    ['Qual substância do dia a dia tem fórmula NaCl?', ['Sal de cozinha', 'Açúcar', 'Bicarbonato', 'Vinagre'], 0, 'É formada pela ligação iônica entre sódio e cloro.'],
    ['Qual cor resulta da soma de todas as cores da luz visível?', ['Branco', 'Preto', 'Cinza', 'Marrom'], 0, 'O preto, ao contrário, é a ausência de luz.'],
    ['Qual é o planeta mais próximo do Sol?', ['Vênus', 'Terra', 'Mercúrio', 'Marte'], 2, 'Mercúrio completa uma volta ao redor do Sol em apenas 88 dias.'],
    ['Como se chama a passagem do estado gasoso para o líquido?', ['Sublimação', 'Condensação', 'Fusão', 'Vaporização'], 1, 'É o que forma as gotinhas do lado de fora de um copo gelado.'],
    ['Qual dispositivo transforma energia elétrica em movimento?', ['Gerador', 'Transformador', 'Resistor', 'Motor'], 3, 'O gerador faz o caminho inverso: transforma movimento em eletricidade.'],
  ],
  2: [
    ['Qual é a fórmula química do gás carbônico?', ['CO', 'CO2', 'C2O', 'CaCO3'], 1, 'É o gás liberado na respiração e na queima de combustíveis fósseis.'],
    ['Quem formulou a teoria da relatividade?', ['Isaac Newton', 'Niels Bohr', 'Max Planck', 'Albert Einstein'], 3, 'A relatividade restrita é de 1905 e a geral, de 1915.'],
    ['Qual é aproximadamente a velocidade da luz no vácuo?', ['300 mil km/s', '300 km/s', '30 mil km/s', '3 milhões de km/s'], 0, 'Nada com massa pode alcançar essa velocidade, segundo a relatividade.'],
    ['Quantos elementos químicos a tabela periódica reconhece atualmente?', ['92', '103', '118', '130'], 2, 'Os últimos elementos foram criados artificialmente em laboratório.'],
    ['Qual é o elemento químico mais abundante do universo?', ['Oxigênio', 'Carbono', 'Hélio', 'Hidrogênio'], 3, 'O hidrogênio responde por cerca de 75% da matéria comum do cosmos.'],
    ['Qual partícula do átomo tem carga elétrica negativa?', ['Próton', 'Elétron', 'Nêutron', 'Fóton'], 1, 'Os elétrons ficam na eletrosfera, girando ao redor do núcleo.'],
    ['Qual partícula do núcleo atômico não tem carga elétrica?', ['Próton', 'Elétron', 'Nêutron', 'Íon'], 2, 'Foi descoberta por James Chadwick em 1932.'],
    ['Qual é a unidade de força no Sistema Internacional?', ['Newton', 'Joule', 'Watt', 'Pascal'], 0, 'Um newton acelera 1 kg a 1 metro por segundo a cada segundo.'],
    ['Qual é a unidade de potência no Sistema Internacional?', ['Watt', 'Joule', 'Newton', 'Volt'], 0, 'Um watt corresponde a um joule de energia por segundo.'],
    ['Qual é o pH de uma solução neutra?', ['0', '1', '7', '14'], 2, 'Abaixo de 7 a solução é ácida; acima, básica.'],
    ['Qual gás de efeito estufa é emitido em maior quantidade pela atividade humana?', ['Metano', 'Ozônio', 'Oxigênio', 'Gás carbônico'], 3, 'A queima de combustíveis fósseis é a principal fonte dessas emissões.'],
    ['Qual cientista organizou os elementos na primeira tabela periódica?', ['Lavoisier', 'Dmitri Mendeleiev', 'John Dalton', 'Ernest Rutherford'], 1, 'Em 1869, ele deixou lacunas para elementos ainda não descobertos — e acertou.'],
    ['Qual metal é o mais usado na fabricação de fios elétricos?', ['Ferro', 'Alumínio', 'Cobre', 'Zinco'], 2, 'O cobre conduz muito bem eletricidade e é relativamente barato.'],
    ['O que a escala Richter mede?', ['A magnitude de terremotos', 'A velocidade do vento', 'A temperatura do ar', 'A acidez de soluções'], 0, 'A escala é logarítmica: cada grau representa uma energia cerca de 32 vezes maior.'],
    ['Qual é o principal componente do aço?', ['Cobre', 'Ferro', 'Alumínio', 'Chumbo'], 1, 'O aço é uma liga de ferro com pequena quantidade de carbono.'],
    ['Qual é a fórmula química da amônia?', ['CH4', 'H2SO4', 'NaOH', 'NH3'], 3, 'A amônia é matéria-prima de fertilizantes e produtos de limpeza.'],
    ['Como se chama a separação da luz branca nas cores do arco-íris por um prisma?', ['Reflexão', 'Difração', 'Absorção', 'Dispersão'], 3, 'Cada cor tem um índice de refração diferente e se desvia em ângulo próprio.'],
    ['Qual lei de Newton afirma que "toda ação gera uma reação"?', ['Primeira lei', 'Terceira lei', 'Segunda lei', 'Lei da gravitação'], 1, 'As forças de ação e reação atuam em corpos diferentes e por isso não se anulam.'],
    ['Qual é o estado da matéria mais abundante no universo?', ['Plasma', 'Sólido', 'Líquido', 'Gasoso'], 0, 'Estrelas, como o Sol, são feitas de plasma — gás ionizado em altíssima temperatura.'],
    ['Qual é o símbolo químico do sódio?', ['So', 'Sd', 'Na', 'S'], 2, 'A sigla vem do latim "natrium".'],
  ],
  3: [
    ['Qual expressão representa a segunda lei de Newton?', ['F = m · a', 'E = m · c²', 'P = m · g', 'v = d / t'], 0, 'A força resultante é igual ao produto da massa pela aceleração.'],
    ['Qual é o número atômico do carbono?', ['4', '5', '6', '12'], 2, 'O carbono tem seis prótons e é a base de toda a química orgânica.'],
    ['Qual cientista descobriu o núcleo atômico com o experimento da lâmina de ouro?', ['J. J. Thomson', 'Niels Bohr', 'John Dalton', 'Ernest Rutherford'], 3, 'Ao ver partículas alfa desviarem, ele concluiu que o átomo é praticamente vazio.'],
    ['Como se chama a ligação química em que há transferência de elétrons?', ['Covalente', 'Iônica', 'Metálica', 'Ponte de hidrogênio'], 1, 'Forma compostos como o sal de cozinha, entre um metal e um ametal.'],
    ['Qual é a unidade de carga elétrica no Sistema Internacional?', ['Ampère', 'Volt', 'Coulomb', 'Ohm'], 2, 'Um coulomb equivale à carga de cerca de 6,24 quintilhões de elétrons.'],
    ['Qual lei relaciona tensão, corrente e resistência elétrica?', ['Lei de Ohm', 'Lei de Coulomb', 'Lei de Faraday', 'Lei de Lenz'], 0, 'A relação é simples: tensão é igual a resistência vezes corrente.'],
    ['Como se chama a passagem direta do estado sólido para o gasoso?', ['Fusão', 'Sublimação', 'Condensação', 'Liquefação'], 1, 'O gelo-seco e a naftalina sublimam à temperatura ambiente.'],
    ['Qual elemento químico tem o símbolo Fe?', ['Flúor', 'Frâncio', 'Fósforo', 'Ferro'], 3, 'A sigla vem do latim "ferrum".'],
    ['Qual é a fórmula do ácido sulfúrico?', ['HCl', 'H2SO4', 'HNO3', 'H2CO3'], 1, 'É o produto químico mais fabricado no mundo, usado em baterias e fertilizantes.'],
    ['Como se chama a quantidade de matéria que contém 6,02 × 10²³ partículas?', ['Massa atômica', 'Número atômico', 'Massa molar', 'Mol'], 3, 'Esse número é chamado constante de Avogadro.'],
    ['Qual sábio da Antiguidade enunciou o princípio do empuxo?', ['Newton', 'Pascal', 'Arquimedes', 'Torricelli'], 2, 'Segundo a lenda, ele gritou "Eureca!" ao perceber o princípio na banheira.'],
    ['Qual força se opõe ao deslizamento entre duas superfícies?', ['Atrito', 'Empuxo', 'Tração', 'Força normal'], 0, 'Sem atrito, seria impossível andar ou frear um carro.'],
    ['Qual grandeza física é medida em pascal?', ['Força', 'Trabalho', 'Potência', 'Pressão'], 3, 'Um pascal corresponde a um newton distribuído por metro quadrado.'],
    ['Qual gás nobre é usado nos letreiros luminosos vermelhos?', ['Argônio', 'Neônio', 'Hélio', 'Criptônio'], 1, 'O termo "luz neon" virou sinônimo desse tipo de letreiro.'],
    ['Qual é o pH aproximado do suco de limão?', ['2', '7', '9', '12'], 0, 'Quanto menor o pH, mais ácida é a substância.'],
    ['Qual teoria define ácido como uma substância doadora de prótons?', ['Teoria de Lewis', 'Teoria de Ostwald', 'Teoria de Brønsted-Lowry', 'Teoria de Nernst'], 2, 'Para Arrhenius, ácido era o que liberava íons H+ em água; Brønsted ampliou o conceito.'],
    ['Qual modelo atômico ficou conhecido como "pudim de passas"?', ['Modelo de Rutherford', 'Modelo de Bohr', 'Modelo de Thomson', 'Modelo de Dalton'], 2, 'Thomson imaginou elétrons espalhados por uma esfera de carga positiva.'],
    ['Qual processo produz a energia das estrelas?', ['A fusão nuclear', 'A fissão nuclear', 'A combustão', 'A radioatividade natural'], 0, 'No Sol, núcleos de hidrogênio se fundem formando hélio e liberando energia.'],
    ['Qual é a unidade de frequência no Sistema Internacional?', ['Decibel', 'Newton', 'Joule', 'Hertz'], 3, 'Um hertz equivale a um ciclo por segundo.'],
    ['Como se chama o fenômeno em que uma onda contorna obstáculos?', ['Reflexão', 'Difração', 'Refração', 'Polarização'], 1, 'É por isso que ouvimos um som vindo da esquina antes de ver a fonte.'],
  ],
  4: [
    ['Qual é o valor aproximado da aceleração da gravidade na Terra?', ['1,6 m/s²', '6,7 m/s²', '3,7 m/s²', '9,8 m/s²'], 3, 'Na Lua, esse valor cai para cerca de 1,6 m/s².'],
    ['Qual cientista propôs que os elétrons ocupam órbitas com energias definidas?', ['Ernest Rutherford', 'Niels Bohr', 'J. J. Thomson', 'Max Planck'], 1, 'O modelo de Bohr explicou as raias do espectro do hidrogênio.'],
    ['Qual partícula, detectada em 2012, está associada à origem da massa?', ['Neutrino', 'Múon', 'Bóson de Higgs', 'Quark top'], 2, 'A confirmação veio do acelerador LHC, do Cern, na fronteira franco-suíça.'],
    ['Qual princípio afirma ser impossível medir com precisão total a posição e a velocidade de uma partícula?', ['Princípio da incerteza', 'Princípio de Pauli', 'Princípio de Arquimedes', 'Princípio de Le Chatelier'], 0, 'Foi enunciado por Werner Heisenberg em 1927.'],
    ['Qual equação relaciona massa e energia?', ['F = m · a', 'E = m · c²', 'P = V · I', 'Q = m · c · ΔT'], 1, 'Ela mostra que uma pequena massa equivale a uma quantidade enorme de energia.'],
    ['Como se chama a quebra do núcleo de um átomo pesado em núcleos menores?', ['Fusão nuclear', 'Decaimento alfa', 'Fissão nuclear', 'Ionização'], 2, 'É o processo usado nas usinas nucleares e nas bombas atômicas.'],
    ['Qual elemento é o combustível mais comum das usinas nucleares?', ['Urânio', 'Chumbo', 'Tório', 'Rádio'], 0, 'O urânio-235 é o isótopo capaz de sustentar a reação em cadeia.'],
    ['Qual lei afirma que a pressão de um gás é inversamente proporcional ao seu volume?', ['Lei de Charles', 'Lei de Gay-Lussac', 'Lei de Avogadro', 'Lei de Boyle'], 3, 'A relação vale para temperatura constante.'],
    ['Qual é o valor do zero absoluto na escala Celsius?', ['0 °C', '-100 °C', '-273,15 °C', '-459 °C'], 2, 'Nessa temperatura, o movimento das partículas atinge o mínimo possível.'],
    ['Qual é a escala absoluta de temperatura usada na ciência?', ['Kelvin', 'Celsius', 'Fahrenheit', 'Réaumur'], 0, 'Ela começa no zero absoluto e não usa o símbolo de grau.'],
    ['Como se chama o desvio da luz ao passar de um meio para outro?', ['Reflexão', 'Refração', 'Difração', 'Interferência'], 1, 'É o que faz um canudo parecer quebrado dentro de um copo de água.'],
    ['Qual é a unidade de resistência elétrica?', ['Volt', 'Ampère', 'Coulomb', 'Ohm'], 3, 'O símbolo é a letra grega ômega.'],
    ['Qual cientista descobriu os elementos polônio e rádio?', ['Marie Curie', 'Lise Meitner', 'Rosalind Franklin', 'Dorothy Hodgkin'], 0, 'Ela foi a primeira pessoa a ganhar dois prêmios Nobel em áreas diferentes.'],
    ['Como se chama a reação química que libera calor para o ambiente?', ['Endotérmica', 'Catalítica', 'Reversível', 'Exotérmica'], 3, 'A combustão e a neutralização de ácidos são exemplos clássicos.'],
    ['Qual é o nome dos catalisadores biológicos que aceleram reações nos seres vivos?', ['Hormônios', 'Enzimas', 'Vitaminas', 'Anticorpos'], 1, 'Quase todas são proteínas e agem em condições muito específicas de pH e temperatura.'],
    ['Qual é o elemento mais eletronegativo da tabela periódica?', ['Oxigênio', 'Cloro', 'Flúor', 'Nitrogênio'], 2, 'Sua alta eletronegatividade faz do flúor um elemento extremamente reativo.'],
    ['A qual família pertencem o hélio, o neônio e o argônio?', ['Halogênios', 'Gases nobres', 'Metais alcalinos', 'Calcogênios'], 1, 'Eles têm a camada de valência completa e quase não formam ligações.'],
    ['Qual técnica separa misturas aproveitando diferentes pontos de ebulição?', ['Filtração', 'Decantação', 'Centrifugação', 'Destilação'], 3, 'É o método usado nas refinarias de petróleo e na produção de bebidas destiladas.'],
    ['Qual grandeza física é medida em joules?', ['Potência', 'Força', 'Energia', 'Pressão'], 2, 'Um joule é o trabalho de uma força de 1 newton ao longo de 1 metro.'],
    ['O que afirma a primeira lei da termodinâmica?', ['A energia não se cria nem se destrói, apenas se transforma', 'A entropia sempre aumenta', 'Todo corpo em repouso tende a permanecer em repouso', 'Calor flui do corpo frio para o quente'], 0, 'É a lei da conservação da energia aplicada a sistemas térmicos.'],
  ],
  5: [
    ['Qual experimento determinou a carga elétrica do elétron?', ['Experimento de Rutherford', 'Experimento da dupla fenda', 'Experimento da gota de óleo de Millikan', 'Experimento de Michelson-Morley'], 2, 'Millikan equilibrou gotas de óleo carregadas em um campo elétrico, em 1909.'],
    ['Qual cientista unificou eletricidade e magnetismo em um conjunto de equações?', ['Michael Faraday', 'André-Marie Ampère', 'Georg Ohm', 'James Clerk Maxwell'], 3, 'As equações de Maxwell previram que a luz é uma onda eletromagnética.'],
    ['Qual efeito explica a emissão de elétrons por metais expostos à luz?', ['Efeito Compton', 'Efeito fotoelétrico', 'Efeito Doppler', 'Efeito Joule'], 1, 'A explicação de Einstein para esse efeito lhe rendeu o Nobel de 1921.'],
    ['Qual princípio impede que dois elétrons tenham o mesmo conjunto de números quânticos?', ['Princípio da exclusão de Pauli', 'Princípio da incerteza', 'Regra de Hund', 'Princípio de Aufbau'], 0, 'É ele que explica a estrutura das camadas eletrônicas e a tabela periódica.'],
    ['Qual é o nome do isótopo de hidrogênio que tem um nêutron no núcleo?', ['Deutério', 'Trítio', 'Prótio', 'Hélio-3'], 0, 'A água pesada, usada em reatores nucleares, é feita com deutério.'],
    ['Qual princípio descreve como um equilíbrio químico responde a perturbações?', ['Lei de Hess', 'Princípio de Le Chatelier', 'Lei de Raoult', 'Lei de Dalton'], 1, 'O sistema se desloca no sentido que atenua a perturbação aplicada.'],
    ['Qual grandeza se conserva em qualquer colisão, elástica ou inelástica?', ['Energia cinética', 'Temperatura', 'Velocidade', 'Quantidade de movimento'], 3, 'A energia cinética só se conserva nas colisões perfeitamente elásticas.'],
    ['Quem mediu pela primeira vez a pressão atmosférica usando uma coluna de mercúrio?', ['Blaise Pascal', 'Robert Boyle', 'Evangelista Torricelli', 'Daniel Bernoulli'], 2, 'O experimento de 1643 deu origem ao barômetro.'],
    ['Qual equação descreve o comportamento quântico de uma partícula?', ['Equação de Maxwell', 'Equação de Schrödinger', 'Equação de Bernoulli', 'Equação de Navier-Stokes'], 1, 'Sua solução, a função de onda, dá a probabilidade de encontrar a partícula.'],
    ['Qual efeito altera a frequência percebida de uma onda quando a fonte se move?', ['Efeito fotoelétrico', 'Efeito Compton', 'Efeito Doppler', 'Efeito Zeeman'], 2, 'É o que muda o som da sirene de uma ambulância ao passar por você.'],
    ['O que afirma a segunda lei da termodinâmica?', ['A entropia de um sistema isolado tende a aumentar', 'A energia total se conserva', 'A pressão é inversa ao volume', 'Corpos se atraem na razão do inverso do quadrado da distância'], 0, 'É a lei que define o sentido do tempo nos processos naturais.'],
    ['Qual cientista é considerado o pai da química moderna e enunciou a conservação das massas?', ['Berzelius', 'Joseph Priestley', 'John Dalton', 'Antoine Lavoisier'], 3, 'Ele foi guilhotinado durante o Terror, na Revolução Francesa.'],
    ['Qual tipo de ligação mantém as moléculas de água unidas entre si?', ['Ligação iônica', 'Ligação covalente', 'Ligação metálica', 'Ligação de hidrogênio'], 3, 'Essas ligações explicam o alto ponto de ebulição da água e a tensão superficial.'],
    ['Qual é a unidade de radioatividade no Sistema Internacional?', ['Becquerel', 'Curie', 'Sievert', 'Gray'], 0, 'Um becquerel equivale a uma desintegração nuclear por segundo.'],
    ['Qual processo industrial produz amônia a partir de nitrogênio e hidrogênio?', ['Processo Solvay', 'Processo Bessemer', 'Processo Haber-Bosch', 'Processo Ostwald'], 2, 'Ele viabilizou os fertilizantes modernos e é apontado como responsável por alimentar bilhões de pessoas.'],
    ['Qual estado da matéria surge quando átomos são resfriados a quase zero absoluto?', ['Plasma', 'Condensado de Bose-Einstein', 'Vidro', 'Cristal líquido'], 1, 'Nesse estado, os átomos passam a se comportar como uma única entidade quântica.'],
    ['Qual teoria descreve a origem do universo a partir de um estado quente e denso?', ['Teoria do Big Bang', 'Teoria do estado estacionário', 'Teoria das cordas', 'Teoria do multiverso'], 0, 'A radiação cósmica de fundo, detectada em 1964, é sua principal evidência.'],
    ['Como se chama o limite de um buraco negro além do qual nada escapa?', ['Singularidade', 'Horizonte de eventos', 'Disco de acreção', 'Ergosfera'], 1, 'Nem mesmo a luz consegue atravessar esse limite de volta.'],
    ['Quantas vezes a massa do próton é maior que a do elétron?', ['10 vezes', '100 vezes', 'Cerca de 1.836 vezes', 'São iguais'], 2, 'Por isso quase toda a massa do átomo está concentrada no núcleo.'],
    ['Qual é o quarto estado da matéria, presente nas estrelas?', ['Sólido', 'Líquido', 'Gasoso', 'Plasma'], 3, 'No plasma, os elétrons se separam dos núcleos, formando um gás ionizado.'],
  ],
});
