import { montar } from './montar';

/** Futebol — 100 perguntas (20 por nível). */
export const perguntasFutebol = montar('futebol', {
  1: [
    ['Quantos jogadores de cada time ficam em campo em uma partida de futebol?', ['9', '10', '11', '12'], 2, 'São dez jogadores de linha mais o goleiro.'],
    ['Quantas Copas do Mundo o Brasil já conquistou?', ['5', '4', '3', '6'], 0, 'Os títulos vieram em 1958, 1962, 1970, 1994 e 2002.'],
    ['Qual jogador brasileiro é conhecido como "o Rei do Futebol"?', ['Garrincha', 'Pelé', 'Zico', 'Romário'], 1, 'Edson Arantes do Nascimento é o único tricampeão mundial como jogador.'],
    ['Qual é a cor tradicional da camisa da seleção brasileira?', ['azul', 'vermelha', 'branca', 'amarela'], 3, 'A camisa amarela foi adotada em 1954, após a derrota de 1950 de uniforme branco.'],
    ['Quanto tempo dura uma partida de futebol, sem contar os acréscimos?', ['90 minutos', '60 minutos', '80 minutos', '120 minutos'], 0, 'São dois tempos de 45 minutos, com intervalo de 15.'],
    ['Qual cartão indica a expulsão de um jogador?', ['azul', 'verde', 'amarelo', 'vermelho'], 3, 'Dois cartões amarelos na mesma partida resultam em um vermelho.'],
    ['Em qual cidade fica o estádio do Maracanã?', ['São Paulo', 'Belo Horizonte', 'Rio de Janeiro', 'Salvador'], 2, 'Foi construído para a Copa do Mundo de 1950.'],
    ['Qual jogador pode usar as mãos dentro de campo?', ['zagueiro', 'goleiro', 'atacante', 'volante'], 1, 'E apenas dentro da própria grande área.'],
    ['De quantos em quantos anos acontece a Copa do Mundo?', ['2', '3', '5', '4'], 3, 'A única interrupção ocorreu por causa da Segunda Guerra Mundial.'],
    ['Qual é o principal campeonato nacional de clubes do Brasil?', ['Copa do Brasil', 'Campeonato Brasileiro', 'Libertadores', 'Copa Sul-Americana'], 1, 'Disputado por pontos corridos, com 20 clubes na Série A.'],
    ['Qual país sediou a Copa do Mundo de 2014?', ['Brasil', 'África do Sul', 'Rússia', 'Alemanha'], 0, 'Foi a segunda vez que o Brasil sediou o torneio, após 1950.'],
    ['Quantos pontos vale uma vitória no Campeonato Brasileiro?', ['1', '2', '3', '4'], 2, 'O empate vale um ponto para cada time.'],
    ['Como é chamado o gol marcado por um jogador contra a própria equipe?', ['gol olímpico', 'gol contra', 'gol de placa', 'gol de bicicleta'], 1, 'O gol olímpico é o marcado diretamente de escanteio.'],
    ['Qual clube brasileiro é conhecido como "Timão"?', ['Palmeiras', 'Santos', 'Corinthians', 'São Paulo'], 2, 'O clube foi fundado em 1910 por operários do bairro do Bom Retiro.'],
    ['Qual jogador argentino levantou a taça da Copa do Mundo de 2022?', ['Ángel Di María', 'Ronaldo', 'Neymar', 'Lionel Messi'], 3, 'A Argentina venceu a França nos pênaltis, no Catar.'],
    ['Qual é a principal competição de clubes da América do Sul?', ['Copa Libertadores', 'Liga dos Campeões', 'Copa do Brasil', 'Mundial de Clubes'], 0, 'Disputada desde 1960, reúne os melhores clubes do continente.'],
    ['Em quantos tempos é dividida uma partida de futebol?', ['2', '3', '4', '1'], 0, 'Na prorrogação, são disputados mais dois tempos de 15 minutos.'],
    ['Qual clube carioca é conhecido como "Mengão"?', ['Vasco da Gama', 'Fluminense', 'Flamengo', 'Botafogo'], 2, 'É o clube com a maior torcida do Brasil.'],
    ['Qual é a punição para uma falta grave cometida dentro da grande área?', ['escanteio', 'pênalti', 'tiro livre indireto', 'lateral'], 1, 'A cobrança é feita a 11 metros do gol, só com o goleiro pela frente.'],
    ['Qual país é mundialmente conhecido como "o país do futebol"?', ['Argentina', 'Itália', 'Alemanha', 'Brasil'], 3, 'O Brasil é o único pentacampeão mundial.'],
  ],
  2: [
    ['Em que ano o Brasil conquistou sua primeira Copa do Mundo?', ['1950', '1958', '1962', '1970'], 1, 'O título veio na Suécia, com Pelé de apenas 17 anos.'],
    ['Qual país sediou a Copa de 1950, vencida pelo Uruguai?', ['Suíça', 'Suécia', 'Chile', 'Brasil'], 3, 'A decisão no Maracanã reuniu quase 200 mil pessoas.'],
    ['Como ficou conhecida a derrota do Brasil para o Uruguai em 1950?', ['Maracanaço', 'Mineiraço', 'Fatalidade de 50', 'Tragédia do Pacaembu'], 0, 'O Brasil precisava apenas de um empate e perdeu por 2 a 1.'],
    ['Qual clube paulista é conhecido como "Verdão"?', ['Corinthians', 'São Paulo', 'Palmeiras', 'Santos'], 2, 'Fundado em 1914 como Palestra Itália, por imigrantes italianos.'],
    ['Em qual clube Pelé passou quase toda a carreira?', ['Corinthians', 'Vasco da Gama', 'Flamengo', 'Santos'], 3, 'Ele defendeu o Santos de 1956 a 1974 antes de jogar nos Estados Unidos.'],
    ['Quem é o maior artilheiro brasileiro em Copas do Mundo?', ['Pelé', 'Ronaldo', 'Romário', 'Neymar'], 1, 'Ronaldo marcou 15 gols em Copas, entre 1998 e 2006.'],
    ['Qual seleção venceu a Copa do Mundo de 2018?', ['Alemanha', 'Argentina', 'França', 'Croácia'], 2, 'A França venceu a Croácia por 4 a 2 na final, em Moscou.'],
    ['Qual seleção europeia tem quatro títulos mundiais, assim como a Itália?', ['Alemanha', 'Espanha', 'Inglaterra', 'Holanda'], 0, 'Os títulos alemães vieram em 1954, 1974, 1990 e 2014.'],
    ['Qual é o nome do estádio do Corinthians, inaugurado em 2014?', ['Neo Química Arena', 'Allianz Parque', 'Morumbi', 'Vila Belmiro'], 0, 'O estádio sediou a abertura da Copa do Mundo de 2014.'],
    ['Qual craque brasileiro era chamado de "Anjo de Pernas Tortas"?', ['Zico', 'Romário', 'Garrincha', 'Rivelino'], 2, 'Garrincha foi campeão mundial em 1958 e 1962.'],
    ['Qual clube tem mais títulos do Campeonato Brasileiro?', ['Corinthians', 'Santos', 'Flamengo', 'Palmeiras'], 3, 'O Palmeiras soma doze conquistas na competição.'],
    ['Qual é a principal competição de clubes da Europa?', ['Copa da Uefa', 'Liga dos Campeões', 'Premier League', 'Supercopa Europeia'], 1, 'Antes de 1992, o torneio se chamava Copa dos Campeões Europeus.'],
    ['Com quantos jogadores, no mínimo, um time pode continuar em campo?', ['9', '8', '7', '6'], 2, 'Se um time fica com menos de sete jogadores, a partida é encerrada.'],
    ['Qual jogador brasileiro ganhou a Bola de Ouro em 2007?', ['Kaká', 'Ronaldinho Gaúcho', 'Ronaldo', 'Rivaldo'], 0, 'Ele foi o último jogador a vencer antes da era Messi e Cristiano Ronaldo.'],
    ['Qual clube brasileiro venceu a primeira Libertadores conquistada pelo país, em 1962?', ['Palmeiras', 'Santos', 'Cruzeiro', 'Flamengo'], 1, 'O time de Pelé repetiu o feito no ano seguinte.'],
    ['Como se chamava o troféu conquistado definitivamente pelo Brasil em 1970?', ['Taça FIFA', 'Taça de Prata', 'Copa América', 'Taça Jules Rimet'], 3, 'A regra dava o troféu em definitivo a quem vencesse três vezes.'],
    ['Qual seleção venceu a Copa do Mundo de 2010?', ['Holanda', 'Alemanha', 'Brasil', 'Espanha'], 3, 'Foi o primeiro e único título mundial da Espanha, na África do Sul.'],
    ['Qual é o apelido da seleção argentina?', ['La Roja', 'Albiceleste', 'La Celeste', 'Tricolor'], 1, 'O nome vem das cores branca e azul-celeste da camisa.'],
    ['Qual é o apelido da seleção do Uruguai?', ['Celeste', 'Albiceleste', 'Roja', 'Verdeamarela'], 0, 'O Uruguai foi campeão mundial em 1930 e 1950.'],
    ['Qual posição é responsável por organizar as jogadas no meio-campo?', ['lateral', 'zagueiro', 'meia-armador', 'centroavante'], 2, 'No Brasil, esse jogador também é chamado de camisa 10.'],
  ],
  3: [
    ['Qual jogador marcou seu milésimo gol no Maracanã, em 1969?', ['Pelé', 'Zico', 'Romário', 'Ronaldo'], 0, 'O gol foi de pênalti, contra o Vasco da Gama.'],
    ['Qual clube brasileiro venceu a Libertadores em 2019 e 2022?', ['Palmeiras', 'River Plate', 'Flamengo', 'Santos'], 2, 'Em 2019, a virada sobre o River Plate aconteceu nos minutos finais.'],
    ['Qual seleção sediou e venceu a Copa do Mundo de 1998?', ['Brasil', 'Itália', 'Alemanha', 'França'], 3, 'A França venceu o Brasil por 3 a 0 na final, com dois gols de Zidane.'],
    ['Quem marcou os dois gols da final da Copa de 2002 contra a Alemanha?', ['Rivaldo', 'Ronaldo', 'Ronaldinho Gaúcho', 'Kaká'], 1, 'Ele terminou o torneio como artilheiro, com oito gols.'],
    ['Quem foi o goleiro titular do Brasil no título da Copa de 1994?', ['Marcos', 'Dida', 'Taffarel', 'Zetti'], 2, 'Ele defendeu a cobrança de Massaro na decisão por pênaltis.'],
    ['Qual foi o placar da final da Copa de 1970 entre Brasil e Itália?', ['4 a 1', '3 a 1', '2 a 0', '5 a 2'], 0, 'O quarto gol, de Carlos Alberto Torres, é um dos mais famosos da história.'],
    ['Em que ano ocorreu o "Mineiraço", a derrota do Brasil por 7 a 1?', ['2010', '2014', '2018', '2006'], 1, 'Foi a semifinal da Copa disputada em casa, em Belo Horizonte.'],
    ['Qual seleção aplicou o 7 a 1 no Brasil?', ['Holanda', 'França', 'Argentina', 'Alemanha'], 3, 'Os alemães marcaram cinco gols nos primeiros 29 minutos.'],
    ['Qual clube tem mais títulos da Copa do Brasil?', ['Grêmio', 'Cruzeiro', 'Palmeiras', 'Flamengo'], 1, 'O Cruzeiro soma seis conquistas no torneio.'],
    ['Quem é o maior artilheiro da história do Campeonato Brasileiro?', ['Zico', 'Pelé', 'Romário', 'Roberto Dinamite'], 3, 'O ídolo do Vasco marcou 190 gols na competição.'],
    ['Qual técnico comandou o Brasil no título de 2002?', ['Mário Zagallo', 'Carlos Alberto Parreira', 'Luiz Felipe Scolari', 'Dunga'], 2, 'Felipão assumiu durante as eliminatórias, em meio a uma campanha ruim.'],
    ['Qual brasileiro foi campeão mundial como jogador e como treinador da seleção?', ['Mário Zagallo', 'Carlos Alberto Parreira', 'Telê Santana', 'Dunga'], 0, 'Zagallo venceu como jogador em 1958 e 1962 e como técnico em 1970.'],
    ['Qual estádio sediou a final da Copa do Mundo de 2014?', ['Mineirão', 'Arena Corinthians', 'Castelão', 'Maracanã'], 3, 'A Alemanha venceu a Argentina por 1 a 0 na prorrogação.'],
    ['Quem é o maior artilheiro da história das Copas do Mundo?', ['Ronaldo', 'Miroslav Klose', 'Pelé', 'Gerd Müller'], 1, 'O alemão marcou 16 gols em quatro edições do torneio.'],
    ['Qual país venceu a primeira Copa do Mundo, em 1930?', ['Uruguai', 'Brasil', 'Argentina', 'Itália'], 0, 'O torneio foi disputado em casa, no Estádio Centenário, em Montevidéu.'],
    ['Quantas vezes a Itália venceu a Copa do Mundo?', ['2', '3', '4', '5'], 2, 'Os títulos vieram em 1934, 1938, 1982 e 2006.'],
    ['Qual clube inglês é conhecido como "Red Devils"?', ['Liverpool', 'Arsenal', 'Manchester United', 'Chelsea'], 2, 'O apelido foi adotado nos anos 1960, inspirado em um time de rúgbi.'],
    ['Qual clube tem mais títulos da Liga dos Campeões da Europa?', ['Real Madrid', 'Barcelona', 'Milan', 'Bayern de Munique'], 0, 'O clube espanhol soma mais de uma dezena de conquistas na competição.'],
    ['Qual brasileiro foi eleito melhor jogador do mundo pela FIFA em 2004 e 2005?', ['Kaká', 'Ronaldo', 'Rivaldo', 'Ronaldinho Gaúcho'], 3, 'Ele brilhava no Barcelona quando recebeu os prêmios.'],
    ['Como se chama o sistema de arbitragem por vídeo adotado no futebol?', ['GLT', 'VAR', 'DRS', 'SAF'], 1, 'A sigla vem do inglês "video assistant referee".'],
  ],
  4: [
    ['Qual foi o primeiro clube brasileiro a conquistar o Mundial Interclubes?', ['Palmeiras', 'Cruzeiro', 'Flamengo', 'Santos'], 3, 'O Santos venceu o Benfica de Eusébio em 1962.'],
    ['Em que ano o Flamengo venceu o Mundial ao bater o Liverpool por 3 a 0?', ['1980', '1981', '1982', '1983'], 1, 'Zico foi eleito o melhor jogador da partida, em Tóquio.'],
    ['Quem cobrou o último pênalti brasileiro na final da Copa de 1994?', ['Romário', 'Branco', 'Dunga', 'Bebeto'], 2, 'A conversão de Dunga deixou a decisão nos pés de Roberto Baggio.'],
    ['Quem perdeu o pênalti decisivo para a Itália na final de 1994?', ['Roberto Baggio', 'Franco Baresi', 'Daniele Massaro', 'Demetrio Albertini'], 0, 'Ele chutou por cima do gol e o Brasil conquistou o tetracampeonato.'],
    ['Qual seleção venceu a Copa América de 2019, disputada no Brasil?', ['Peru', 'Brasil', 'Argentina', 'Uruguai'], 1, 'A seleção brasileira venceu o Peru por 3 a 1 na final, no Maracanã.'],
    ['Qual é o nome do estádio do Grêmio, inaugurado em 2012?', ['Beira-Rio', 'Olímpico Monumental', 'Arena do Grêmio', 'Couto Pereira'], 2, 'O Olímpico foi a casa do clube por mais de 50 anos antes da mudança.'],
    ['Qual clube mineiro conquistou a Libertadores em 2013?', ['Atlético Mineiro', 'Cruzeiro', 'América-MG', 'Villa Nova'], 0, 'Ronaldinho Gaúcho foi eleito o melhor jogador daquela edição.'],
    ['Quem é o maior artilheiro da história do Real Madrid?', ['Raúl', 'Alfredo Di Stéfano', 'Karim Benzema', 'Cristiano Ronaldo'], 3, 'Ele marcou mais de 450 gols em nove temporadas pelo clube.'],
    ['Quantos gols Pelé marcou pela seleção brasileira em jogos oficiais?', ['50', '65', '77', '90'], 2, 'A marca ficou de pé por mais de cinquenta anos.'],
    ['Qual jogador ultrapassou Pelé como maior artilheiro da seleção brasileira?', ['Neymar', 'Ronaldo', 'Romário', 'Zico'], 0, 'Ele superou a marca histórica em 2023.'],
    ['Qual clube gaúcho manda seus jogos no estádio Beira-Rio?', ['Grêmio', 'Internacional', 'Juventude', 'Caxias'], 1, 'O Internacional venceu a Libertadores em 2006 e 2010.'],
    ['Qual craque holandês ficou associado ao "carrossel holandês" dos anos 1970?', ['Ruud Gullit', 'Marco van Basten', 'Dennis Bergkamp', 'Johan Cruyff'], 3, 'Seu drible característico ganhou o nome de "Cruyff turn".'],
    ['Qual técnico é apontado como criador do "futebol total"?', ['Rinus Michels', 'Arrigo Sacchi', 'Pep Guardiola', 'Helenio Herrera'], 0, 'Ele comandou o Ajax e a Holanda na década de 1970.'],
    ['Qual seleção africana chegou às semifinais da Copa do Mundo de 2022?', ['Camarões', 'Senegal', 'Gana', 'Marrocos'], 3, 'Foi a primeira vez que um país africano alcançou essa fase.'],
    ['Quem marcou o gol conhecido como "La Mano de Dios"?', ['Pelé', 'Diego Maradona', 'Lionel Messi', 'Gabriel Batistuta'], 1, 'O gol de mão contra a Inglaterra não foi visto pelo árbitro.'],
    ['Em qual Copa Maradona marcou o chamado "gol do século"?', ['1982', '1990', '1986', '1994'], 2, 'Ele driblou meio time inglês em pouco mais de dez segundos, no México.'],
    ['Qual clube argentino é o maior campeão da Libertadores?', ['Boca Juniors', 'Independiente', 'River Plate', 'Estudiantes'], 1, 'O Independiente soma sete títulos continentais.'],
    ['Qual jogador brasileiro ficou conhecido como "o Fenômeno"?', ['Romário', 'Rivaldo', 'Adriano', 'Ronaldo'], 3, 'Ele voltou de duas graves lesões no joelho para ser campeão em 2002.'],
    ['Qual foi o primeiro país africano a sediar uma Copa do Mundo?', ['Egito', 'Marrocos', 'África do Sul', 'Nigéria'], 2, 'O torneio de 2010 popularizou a vuvuzela no mundo todo.'],
    ['Qual é a maior goleada da história das Copas do Mundo?', ['Hungria 10 a 1 sobre El Salvador', 'Brasil 7 a 1 sobre a Alemanha', 'Alemanha 8 a 0 sobre a Arábia Saudita', 'Iugoslávia 9 a 0 sobre o Zaire'], 0, 'O placar aconteceu na Copa da Espanha, em 1982.'],
  ],
  5: [
    ['Qual é considerado o clube de futebol mais antigo em atividade no Brasil?', ['Fluminense', 'Flamengo', 'Sport Club Rio Grande', 'Ponte Preta'], 2, 'O clube gaúcho foi fundado em 19 de julho de 1900.'],
    ['Quem é considerado o pai do futebol no Brasil?', ['Oscar Cox', 'Hans Nobiling', 'Guilherme de Aquino', 'Charles Miller'], 3, 'Ele voltou da Inglaterra em 1894 trazendo bolas e um livro de regras.'],
    ['Em que ano foi disputada a primeira Copa do Mundo?', ['1920', '1930', '1934', '1938'], 1, 'Apenas 13 seleções participaram daquela primeira edição.'],
    ['Qual seleção participou de todas as edições da Copa do Mundo?', ['Brasil', 'Alemanha', 'Itália', 'Argentina'], 0, 'O Brasil é o único país presente em todas as Copas desde 1930.'],
    ['Quem foi o capitão do Brasil no título da Copa de 2002?', ['Cafu', 'Roberto Carlos', 'Lúcio', 'Emerson'], 0, 'Ele é o único jogador a disputar três finais consecutivas de Copa do Mundo.'],
    ['Qual seleção já perdeu três finais de Copa do Mundo sem nunca ter vencido?', ['Hungria', 'Holanda', 'Tchecoslováquia', 'Suécia'], 1, 'As derrotas vieram em 1974, 1978 e 2010.'],
    ['Qual foi o placar da final da primeira Copa, entre Uruguai e Argentina?', ['2 a 1', '3 a 1', '4 a 1', '4 a 2'], 3, 'Cada tempo foi jogado com uma bola diferente, uma de cada seleção.'],
    ['Quem marcou o primeiro gol da história das Copas do Mundo?', ['Guillermo Stábile', 'Preguinho', 'Lucien Laurent', 'Bert Patenaude'], 2, 'O francês marcou contra o México, em 13 de julho de 1930.'],
    ['Quem marcou o primeiro hat-trick da história das Copas?', ['Lucien Laurent', 'Bert Patenaude', 'Guillermo Stábile', 'Leônidas da Silva'], 1, 'O americano fez três gols contra o Paraguai, em 1930.'],
    ['Qual craque brasileiro era chamado de "Diamante Negro"?', ['Domingos da Guia', 'Arthur Friedenreich', 'Leônidas da Silva', 'Zizinho'], 2, 'Ele foi artilheiro da Copa de 1938 e popularizou a bicicleta.'],
    ['Qual jogador é apontado como o primeiro grande craque negro do futebol brasileiro?', ['Arthur Friedenreich', 'Leônidas da Silva', 'Domingos da Guia', 'Fausto dos Santos'], 0, 'Filho de alemão com brasileira, ele alisava o cabelo para poder jogar nos anos 1910.'],
    ['Qual clube venceu a primeira edição do Campeonato Brasileiro, a Taça Brasil de 1959?', ['Santos', 'Palmeiras', 'Cruzeiro', 'Bahia'], 3, 'O Bahia venceu o Santos de Pelé na decisão.'],
    ['Qual partida detém o recorde de público da história do futebol?', ['A final da Copa de 1994', 'A final da Champions de 1960', 'Flamengo x Vasco de 1963', 'Brasil x Uruguai de 1950'], 3, 'O Maracanã recebeu quase 200 mil pessoas na decisão.'],
    ['Qual técnico comandou seleções em seis edições da Copa do Mundo?', ['Carlos Alberto Parreira', 'Mário Zagallo', 'Telê Santana', 'Luiz Felipe Scolari'], 0, 'Ele dirigiu Kuwait, Emirados Árabes, Brasil, Arábia Saudita e África do Sul.'],
    ['Qual jogador venceu mais vezes a Bola de Ouro?', ['Cristiano Ronaldo', 'Michel Platini', 'Lionel Messi', 'Johan Cruyff'], 2, 'O argentino soma oito troféus, recorde absoluto da premiação.'],
    ['Qual seleção venceu a Copa de 1954, no episódio chamado "Milagre de Berna"?', ['Hungria', 'Alemanha Ocidental', 'Áustria', 'Uruguai'], 1, 'Os alemães viraram sobre a Hungria, invicta havia quatro anos.'],
    ['Qual seleção ficou conhecida como "Laranja Mecânica"?', ['Holanda', 'Espanha', 'Itália', 'Brasil'], 0, 'O apelido veio do uniforme laranja e do futebol coletivo dos anos 1970.'],
    ['Qual clube italiano é chamado de "Vecchia Signora", a Velha Senhora?', ['Milan', 'Juventus', 'Internazionale', 'Roma'], 1, 'A Juventus é o clube com mais títulos do Campeonato Italiano.'],
    ['Qual é o maior clássico do futebol argentino?', ['Racing x Independiente', 'River x Racing', 'Boca Juniors x River Plate', 'San Lorenzo x Huracán'], 2, 'O duelo é conhecido como Superclásico.'],
    ['Qual é o nome do estádio do Boca Juniors?', ['El Monumental', 'Estádio Centenário', 'Arena Corinthians', 'La Bombonera'], 3, 'O formato estreito e as arquibancadas verticais deram origem ao apelido.'],
  ],
});
