import { montar } from './montar';

/** Geografia do Brasil — 100 perguntas (20 por nível). */
export const perguntasGeografiaBrasil = montar('geografia-brasil', {
  1: [
    ['Qual é a capital do Brasil?', ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Belo Horizonte'], 2, 'Brasília fica no Distrito Federal, no Planalto Central, e é capital desde 1960.'],
    ['Qual é o maior rio do Brasil em volume de água?', ['Rio Amazonas', 'Rio São Francisco', 'Rio Paraná', 'Rio Tietê'], 0, 'O Amazonas despeja cerca de um quinto de toda a água doce que chega aos oceanos.'],
    ['Quantos estados o Brasil possui?', ['25', '26', '27', '24'], 1, 'São 26 estados mais o Distrito Federal, totalizando 27 unidades federativas.'],
    ['Qual oceano banha todo o litoral brasileiro?', ['Pacífico', 'Índico', 'Ártico', 'Atlântico'], 3, 'A costa brasileira tem mais de 7.400 quilômetros banhados pelo Atlântico.'],
    ['Qual é o maior estado brasileiro em área?', ['Amazonas', 'Pará', 'Mato Grosso', 'Bahia'], 0, 'O Amazonas tem mais de 1,5 milhão de km², maior que muitos países europeus somados.'],
    ['Qual é a capital do estado da Bahia?', ['Recife', 'Fortaleza', 'Maceió', 'Salvador'], 3, 'Salvador foi a primeira capital do Brasil e é famosa pelo Pelourinho e pelo carnaval.'],
    ['Qual bioma brasileiro abriga a maior floresta tropical do mundo?', ['Cerrado', 'Caatinga', 'Amazônia', 'Pantanal'], 2, 'A Amazônia ocupa cerca de 49% do território brasileiro.'],
    ['Qual é a capital de Minas Gerais?', ['Ouro Preto', 'Belo Horizonte', 'Uberlândia', 'Juiz de Fora'], 1, 'Belo Horizonte foi a primeira cidade brasileira planejada, inaugurada em 1897.'],
    ['Em qual região do Brasil fica o estado do Ceará?', ['Sudeste', 'Sul', 'Centro-Oeste', 'Nordeste'], 3, 'O Ceará tem Fortaleza como capital e é conhecido por suas praias e pelo humor cearense.'],
    ['Qual é a cidade mais populosa do Brasil?', ['Rio de Janeiro', 'São Paulo', 'Brasília', 'Salvador'], 1, 'São Paulo tem mais de 11 milhões de habitantes e é a maior cidade da América do Sul.'],
    ['Em quantas regiões o Brasil é dividido?', ['Cinco', 'Quatro', 'Seis', 'Três'], 0, 'Norte, Nordeste, Centro-Oeste, Sudeste e Sul, segundo a divisão do IBGE.'],
    ['Qual é a capital do Rio Grande do Sul?', ['Curitiba', 'Florianópolis', 'Porto Alegre', 'Caxias do Sul'], 2, 'Porto Alegre fica às margens do lago Guaíba, no extremo sul do país.'],
    ['Com qual país o Brasil tem a maior fronteira terrestre?', ['Argentina', 'Bolívia', 'Peru', 'Venezuela'], 1, 'A fronteira com a Bolívia passa de 3.400 quilômetros.'],
    ['Qual bioma cobre o sertão semiárido do Nordeste?', ['Cerrado', 'Pampa', 'Caatinga', 'Mata Atlântica'], 2, 'A Caatinga é o único bioma exclusivamente brasileiro.'],
    ['Em qual cidade brasileira está o Cristo Redentor?', ['Salvador', 'São Paulo', 'Brasília', 'Rio de Janeiro'], 3, 'A estátua no morro do Corcovado foi inaugurada em 1931 e tem 38 metros de altura.'],
    ['Qual é o famoso ponto turístico natural de Foz do Iguaçu?', ['As Cataratas do Iguaçu', 'A Chapada Diamantina', 'Os Lençóis Maranhenses', 'A Serra do Mar'], 0, 'São cerca de 275 quedas d’água na fronteira do Paraná com a Argentina.'],
    ['Qual estado brasileiro tem Manaus como capital?', ['Amazonas', 'Pará', 'Acre', 'Roraima'], 0, 'Manaus enriqueceu com o ciclo da borracha e abriga o Teatro Amazonas.'],
    ['Qual é a região mais populosa do Brasil?', ['Nordeste', 'Sul', 'Sudeste', 'Norte'], 2, 'O Sudeste concentra cerca de 42% da população brasileira.'],
    ['Qual é a capital do Paraná?', ['Londrina', 'Curitiba', 'Foz do Iguaçu', 'Maringá'], 1, 'Curitiba é conhecida por seu sistema de transporte público e seus parques.'],
    ['Qual destes estados fica na região Sul do Brasil?', ['Mato Grosso do Sul', 'São Paulo', 'Goiás', 'Santa Catarina'], 3, 'A região Sul é formada por Paraná, Santa Catarina e Rio Grande do Sul.'],
  ],
  2: [
    ['Qual é o estado brasileiro mais populoso?', ['Minas Gerais', 'São Paulo', 'Rio de Janeiro', 'Bahia'], 1, 'São Paulo sozinho tem mais habitantes do que toda a região Norte.'],
    ['Qual é a capital de Pernambuco?', ['Maceió', 'João Pessoa', 'Natal', 'Recife'], 3, 'Recife é cortada por rios e pontes, o que lhe rendeu o apelido de "Veneza brasileira".'],
    ['Qual rio é chamado de "rio da integração nacional"?', ['São Francisco', 'Tocantins', 'Paraná', 'Doce'], 0, 'O Velho Chico nasce em Minas Gerais e atravessa o semiárido até o Atlântico.'],
    ['Qual é o menor estado brasileiro em área?', ['Alagoas', 'Espírito Santo', 'Sergipe', 'Rio de Janeiro'], 2, 'Sergipe tem pouco mais de 21 mil km², menor que o estado de Israel.'],
    ['Qual bioma brasileiro é a maior planície alagável do mundo?', ['Amazônia', 'Cerrado', 'Caatinga', 'Pantanal'], 3, 'O Pantanal alaga em boa parte do ano e concentra enorme diversidade de aves e jacarés.'],
    ['Qual é o ponto mais alto do Brasil?', ['Pico das Agulhas Negras', 'Pico da Neblina', 'Monte Roraima', 'Pico Paraná'], 1, 'O Pico da Neblina, em Roraima, tem 2.995 metros de altitude.'],
    ['Quantos países fazem fronteira com o Brasil?', ['Nove', 'Onze', 'Dez', 'Doze'], 2, 'São dez vizinhos: todos os países sul-americanos, exceto Chile e Equador.'],
    ['Quais países da América do Sul NÃO fazem fronteira com o Brasil?', ['Chile e Equador', 'Peru e Bolívia', 'Uruguai e Paraguai', 'Colômbia e Venezuela'], 0, 'A cordilheira dos Andes separa o Brasil desses dois países.'],
    ['Qual linha imaginária corta o norte do território brasileiro?', ['A linha do Equador', 'O Trópico de Capricórnio', 'O Meridiano de Greenwich', 'O Círculo Polar Ártico'], 0, 'O Equador passa por estados como Amazonas, Pará e Amapá.'],
    ['Qual é a capital de Santa Catarina?', ['Joinville', 'Blumenau', 'Florianópolis', 'Chapecó'], 2, 'Florianópolis fica majoritariamente em uma ilha e tem mais de 40 praias.'],
    ['Qual é a capital do estado do Pará?', ['São Luís', 'Macapá', 'Manaus', 'Belém'], 3, 'Belém é famosa pelo mercado Ver-o-Peso e pelo Círio de Nazaré.'],
    ['Qual clima predomina na maior parte do território brasileiro?', ['Temperado', 'Tropical', 'Desértico', 'Polar'], 1, 'O clima tropical traz temperaturas altas o ano todo e chuvas concentradas no verão.'],
    ['Qual é a maior usina hidrelétrica em território brasileiro?', ['Tucuruí', 'Belo Monte', 'Itaipu', 'Furnas'], 2, 'Itaipu é binacional e por décadas foi a maior geradora de energia do mundo.'],
    ['A usina de Itaipu fica na fronteira com qual país?', ['Paraguai', 'Argentina', 'Uruguai', 'Bolívia'], 0, 'A usina no rio Paraná é administrada em conjunto por Brasil e Paraguai.'],
    ['Qual estado brasileiro tem o litoral mais extenso?', ['Rio Grande do Sul', 'Bahia', 'São Paulo', 'Ceará'], 1, 'A costa baiana tem cerca de 1.180 quilômetros de praias.'],
    ['Qual capital brasileira foi planejada e inaugurada em 1960?', ['Palmas', 'Goiânia', 'Belo Horizonte', 'Brasília'], 3, 'O projeto urbanístico de Lucio Costa é Patrimônio Mundial da Unesco.'],
    ['Qual é a capital brasileira mais recente, inaugurada em 1990?', ['Brasília', 'Goiânia', 'Boa Vista', 'Palmas'], 3, 'Palmas foi erguida para ser a capital do então novo estado do Tocantins.'],
    ['Qual serra do Sudeste abriga o Pico das Agulhas Negras?', ['Serra do Espinhaço', 'Serra da Mantiqueira', 'Serra do Mar', 'Chapada Diamantina'], 1, 'A Mantiqueira se estende por São Paulo, Minas Gerais e Rio de Janeiro.'],
    ['Qual é o arquipélago oceânico brasileiro mais conhecido, em Pernambuco?', ['Fernando de Noronha', 'Abrolhos', 'Ilha de Marajó', 'Ilhabela'], 0, 'Noronha fica a 545 km da costa e é Patrimônio Natural da Humanidade.'],
    ['Qual é a maior ilha fluvial do mundo, localizada no rio Araguaia?', ['Ilha de Marajó', 'Ilha Grande', 'Ilha do Bananal', 'Ilha do Mel'], 2, 'A Ilha do Bananal, no Tocantins, tem cerca de 20 mil km².'],
  ],
  3: [
    ['Qual estado brasileiro tem o maior PIB?', ['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Paraná'], 0, 'São Paulo responde por cerca de um terço de toda a economia nacional.'],
    ['Qual é o rio mais extenso situado inteiramente em território brasileiro?', ['Rio Amazonas', 'Rio Paraná', 'Rio São Francisco', 'Rio Madeira'], 2, 'O São Francisco percorre cerca de 2.700 km, de Minas Gerais ao Atlântico.'],
    ['Qual estado é o maior produtor de café do Brasil?', ['Espírito Santo', 'São Paulo', 'Bahia', 'Minas Gerais'], 3, 'Minas Gerais responde por mais da metade da produção nacional de café.'],
    ['Qual bioma ocupa a maior parte da região Centro-Oeste?', ['Pantanal', 'Cerrado', 'Caatinga', 'Mata Atlântica'], 1, 'O Cerrado é considerado a savana mais biodiversa do planeta.'],
    ['Qual é o estado mais populoso do Nordeste?', ['Pernambuco', 'Ceará', 'Bahia', 'Maranhão'], 2, 'A Bahia tem cerca de 14 milhões de habitantes.'],
    ['Qual destas capitais brasileiras fica mais ao sul?', ['Porto Alegre', 'Florianópolis', 'Curitiba', 'São Paulo'], 0, 'Porto Alegre está a cerca de 30 graus de latitude sul.'],
    ['Qual é a única capital brasileira totalmente ao norte da linha do Equador?', ['Belém', 'Boa Vista', 'Manaus', 'Macapá'], 1, 'Boa Vista, capital de Roraima, é a única inteiramente no hemisfério norte.'],
    ['Qual estado brasileiro tem o menor litoral?', ['Sergipe', 'Alagoas', 'Espírito Santo', 'Piauí'], 3, 'O Piauí tem apenas cerca de 66 quilômetros de costa.'],
    ['Qual é o principal produto agrícola de exportação do Brasil?', ['Café', 'Soja', 'Milho', 'Açúcar'], 1, 'O Brasil disputa com os Estados Unidos a liderança mundial na produção de soja.'],
    ['Qual destes estados NÃO faz parte da região Centro-Oeste?', ['Goiás', 'Mato Grosso', 'Mato Grosso do Sul', 'Tocantins'], 3, 'O Tocantins integra a região Norte desde sua criação, em 1988.'],
    ['Qual é o maior porto da América Latina?', ['Porto de Paranaguá', 'Porto de Itajaí', 'Porto de Santos', 'Porto de Suape'], 2, 'Santos movimenta a maior parte do comércio exterior brasileiro.'],
    ['Qual fenômeno climático aquece as águas do Pacífico e altera as chuvas no Brasil?', ['El Niño', 'La Niña', 'Monção', 'Maré vermelha'], 0, 'O El Niño costuma trazer secas ao Nordeste e chuvas intensas ao Sul.'],
    ['Qual estado brasileiro tem o maior rebanho bovino?', ['Goiás', 'Minas Gerais', 'Pará', 'Mato Grosso'], 3, 'Mato Grosso lidera a pecuária de corte, com mais de 30 milhões de cabeças.'],
    ['Qual é a maior lagoa do Brasil?', ['Lagoa Mirim', 'Lagoa dos Patos', 'Lagoa Rodrigo de Freitas', 'Lagoa de Araruama'], 1, 'A Lagoa dos Patos, no Rio Grande do Sul, é a maior laguna da América do Sul.'],
    ['Qual destes estados é cortado pelo Trópico de Capricórnio?', ['São Paulo', 'Bahia', 'Amazonas', 'Ceará'], 0, 'O trópico passa também pelo Paraná e por Mato Grosso do Sul.'],
    ['Qual região brasileira tem o maior número de estados?', ['Norte', 'Sul', 'Nordeste', 'Sudeste'], 2, 'O Nordeste reúne nove estados, de Alagoas à Bahia.'],
    ['Qual é o principal minério exportado pelo Brasil?', ['Bauxita', 'Manganês', 'Minério de ferro', 'Ouro'], 2, 'O ferro brasileiro abastece principalmente a siderurgia chinesa.'],
    ['Em qual estado fica a serra de Carajás, maior província mineral do país?', ['Pará', 'Minas Gerais', 'Bahia', 'Goiás'], 0, 'Carajás tem uma das maiores reservas de minério de ferro de alto teor do mundo.'],
    ['Qual rio forma as Cataratas do Iguaçu, na divisa com a Argentina?', ['Rio Paraná', 'Rio Uruguai', 'Rio Paraguai', 'Rio Iguaçu'], 3, 'O rio Iguaçu deságua no Paraná poucos quilômetros depois das quedas.'],
    ['Qual bioma brasileiro é o mais devastado pela ocupação humana?', ['Cerrado', 'Mata Atlântica', 'Caatinga', 'Pampa'], 1, 'Restam cerca de 12% da cobertura original da Mata Atlântica, onde vive a maior parte dos brasileiros.'],
  ],
  4: [
    ['Qual é o ponto mais oriental do Brasil continental?', ['Cabo de Santo Agostinho', 'Ponta do Calcanhar', 'Cabo Orange', 'Ponta do Seixas'], 3, 'A Ponta do Seixas, na Paraíba, é também o ponto mais a leste das Américas.'],
    ['Qual é o maior estado da região Sudeste em área?', ['São Paulo', 'Minas Gerais', 'Rio de Janeiro', 'Espírito Santo'], 1, 'Minas Gerais tem quase 587 mil km² e faz divisa com seis estados.'],
    ['Qual é a capital do Tocantins?', ['Araguaína', 'Gurupi', 'Palmas', 'Porto Nacional'], 2, 'Palmas foi fundada em 1989, sendo a capital brasileira mais jovem.'],
    ['Qual é a capital de Rondônia?', ['Porto Velho', 'Rio Branco', 'Boa Vista', 'Macapá'], 0, 'Porto Velho cresceu com a construção da ferrovia Madeira-Mamoré.'],
    ['Qual é a capital do Acre?', ['Porto Velho', 'Rio Branco', 'Cruzeiro do Sul', 'Sena Madureira'], 1, 'Rio Branco fica às margens do rio Acre, na Amazônia ocidental.'],
    ['Qual é a capital do Maranhão?', ['Teresina', 'Imperatriz', 'São Luís', 'Caxias'], 2, 'São Luís foi fundada por franceses em 1612 e tem o maior conjunto de azulejos portugueses das Américas.'],
    ['Qual unidade de relevo predomina no território brasileiro?', ['Planaltos', 'Montanhas jovens', 'Depressões absolutas', 'Cordilheiras'], 0, 'O relevo brasileiro é antigo e desgastado, sem cadeias montanhosas recentes.'],
    ['Qual é a maior bacia hidrográfica do Brasil?', ['Bacia do Paraná', 'Bacia do São Francisco', 'Bacia do Tocantins-Araguaia', 'Bacia Amazônica'], 3, 'A bacia Amazônica é a maior do mundo e cobre cerca de 45% do território nacional.'],
    ['Qual estado brasileiro lidera a produção de soja?', ['Paraná', 'Goiás', 'Mato Grosso', 'Rio Grande do Sul'], 2, 'Mato Grosso sozinho produz cerca de um terço da soja brasileira.'],
    ['Quais rios se encontram em Manaus no chamado "encontro das águas"?', ['Negro e Solimões', 'Madeira e Tapajós', 'Xingu e Tocantins', 'Branco e Japurá'], 0, 'As águas escuras do Negro e barrentas do Solimões correm lado a lado por quilômetros.'],
    ['Qual estado abriga a maior parte da área do Pantanal?', ['Mato Grosso', 'Mato Grosso do Sul', 'Goiás', 'Rondônia'], 1, 'Cerca de 65% do Pantanal brasileiro fica em Mato Grosso do Sul.'],
    ['Qual é a capital de Sergipe?', ['Maceió', 'João Pessoa', 'Natal', 'Aracaju'], 3, 'Aracaju foi uma das primeiras cidades brasileiras planejadas, em 1855.'],
    ['Qual é a capital do Piauí?', ['Teresina', 'São Luís', 'Parnaíba', 'Floriano'], 0, 'Teresina é a única capital do Nordeste que não fica no litoral.'],
    ['Qual capital brasileira é banhada pelo lago Guaíba?', ['Curitiba', 'Florianópolis', 'Belo Horizonte', 'Porto Alegre'], 3, 'O pôr do sol no Guaíba é um dos cartões-postais de Porto Alegre.'],
    ['Qual é o grande campo de dunas e lagoas do litoral do Maranhão?', ['Jalapão', 'Lençóis Maranhenses', 'Chapada das Mesas', 'Delta do Parnaíba'], 1, 'As lagoas se formam entre as dunas na estação chuvosa, entre julho e setembro.'],
    ['Qual estado brasileiro tem o maior número de municípios?', ['São Paulo', 'Bahia', 'Minas Gerais', 'Rio Grande do Sul'], 2, 'Minas Gerais tem 853 municípios, seguido por São Paulo, com 645.'],
    ['Qual é a região metropolitana mais populosa do Brasil?', ['Rio de Janeiro', 'São Paulo', 'Belo Horizonte', 'Recife'], 1, 'A Grande São Paulo reúne 39 municípios e mais de 20 milhões de pessoas.'],
    ['Qual corrente marítima quente banha o litoral brasileiro?', ['Corrente das Malvinas', 'Corrente de Humboldt', 'Corrente do Golfo', 'Corrente do Brasil'], 3, 'Ela corre do norte para o sul e mantém as águas do litoral aquecidas.'],
    ['Qual vegetação litorânea cresce em áreas alagadas de água salobra?', ['Restinga', 'Caatinga', 'Manguezal', 'Cerradão'], 2, 'Os manguezais são berçários naturais de peixes, caranguejos e camarões.'],
    ['Qual é a maior terra indígena do Brasil em extensão?', ['Terra Indígena Yanomami', 'Parque Indígena do Xingu', 'Raposa Serra do Sol', 'Vale do Javari'], 0, 'A terra Yanomami tem cerca de 9,6 milhões de hectares entre Roraima e Amazonas.'],
  ],
  5: [
    ['Qual é o ponto extremo sul do Brasil?', ['Cabo Orange', 'Ponta do Seixas', 'Arroio Chuí', 'Serra do Divisor'], 2, 'O Arroio Chuí fica no Rio Grande do Sul, na divisa com o Uruguai.'],
    ['Qual é o ponto extremo oeste do Brasil?', ['Ponta do Seixas', 'Arroio Chuí', 'Monte Caburaí', 'Nascente do rio Moa, na Serra do Divisor'], 3, 'O extremo oeste fica no Acre, na fronteira com o Peru.'],
    ['Qual é o ponto extremo norte do Brasil?', ['Oiapoque', 'Monte Caburaí', 'Boa Vista', 'Cabo Orange'], 1, 'O Monte Caburaí, em Roraima, substituiu o Oiapoque como extremo norte oficial.'],
    ['Qual é o segundo maior estado brasileiro em área?', ['Pará', 'Amazonas', 'Mato Grosso', 'Minas Gerais'], 0, 'O Pará tem cerca de 1,2 milhão de km², atrás apenas do Amazonas.'],
    ['Qual é o estado brasileiro menos populoso?', ['Roraima', 'Acre', 'Amapá', 'Tocantins'], 0, 'Roraima tem pouco mais de 650 mil habitantes.'],
    ['Qual é o maior afluente do rio Amazonas em volume de água?', ['Rio Negro', 'Rio Madeira', 'Rio Tapajós', 'Rio Xingu'], 1, 'O Madeira nasce na Bolívia e no Peru e despeja enorme carga de sedimentos.'],
    ['Como é chamada a região mineradora de Minas Gerais rica em minério de ferro?', ['Serra dos Carajás', 'Chapada Diamantina', 'Vale do Aço', 'Quadrilátero Ferrífero'], 3, 'A área de cerca de 7 mil km² inclui cidades históricas como Ouro Preto e Mariana.'],
    ['Qual aquífero subterrâneo se estende pelo Brasil e países vizinhos?', ['Aquífero Alter do Chão', 'Aquífero Bauru', 'Aquífero Guarani', 'Aquífero Cabeças'], 2, 'O Guarani é uma das maiores reservas de água doce subterrânea do mundo.'],
    ['Qual foi o primeiro parque nacional criado no Brasil, em 1937?', ['Parque Nacional do Iguaçu', 'Parque Nacional de Itatiaia', 'Parque Nacional da Serra dos Órgãos', 'Parque Nacional da Tijuca'], 1, 'Itatiaia fica na Serra da Mantiqueira, entre Rio de Janeiro e Minas Gerais.'],
    ['Qual estado brasileiro foi criado em 1988 a partir do território de Goiás?', ['Rondônia', 'Mato Grosso do Sul', 'Tocantins', 'Amapá'], 2, 'A divisão foi definida pela Constituição de 1988 e o estado nasceu em 1989.'],
    ['Qual estado brasileiro foi desmembrado de Mato Grosso em 1977?', ['Mato Grosso do Sul', 'Goiás', 'Rondônia', 'Tocantins'], 0, 'Campo Grande tornou-se a capital do novo estado, instalado em 1979.'],
    ['Qual clima predomina no Sul do Brasil, com as quatro estações bem marcadas?', ['Tropical de altitude', 'Semiárido', 'Equatorial', 'Subtropical'], 3, 'É a única região brasileira onde ocorrem neve e geadas com regularidade.'],
    ['Qual escarpa separa o litoral do planalto na região Sudeste?', ['Chapada Diamantina', 'Serra do Espinhaço', 'Serra Geral', 'Serra do Mar'], 3, 'A Serra do Mar acompanha a costa do Rio de Janeiro a Santa Catarina.'],
    ['Qual foi a primeira vila fundada no Brasil, em 1532?', ['São Vicente', 'Salvador', 'Olinda', 'Santos'], 0, 'São Vicente, no litoral paulista, é chamada de "Cellula Mater" da nacionalidade.'],
    ['Qual é o único estado brasileiro cujo nome homenageia uma santa?', ['Espírito Santo', 'São Paulo', 'Santa Catarina', 'Sergipe'], 2, 'O nome vem de Santa Catarina de Alexandria, homenageada pelos navegadores.'],
    ['Quantos fusos horários existem no Brasil?', ['Dois', 'Quatro', 'Três', 'Cinco'], 1, 'São quatro fusos, de UTC-2, nas ilhas oceânicas, a UTC-5, no Acre.'],
    ['Qual é o segundo maior bioma brasileiro em extensão?', ['Cerrado', 'Mata Atlântica', 'Caatinga', 'Pampa'], 0, 'O Cerrado ocupa cerca de 24% do território, atrás apenas da Amazônia.'],
    ['Como é chamada a camada de petróleo situada sob uma espessa camada de sal no litoral brasileiro?', ['Pós-sal', 'Pré-sal', 'Sal-gema', 'Plataforma continental'], 1, 'As reservas do pré-sal estão a mais de 5 mil metros de profundidade.'],
    ['Qual estado brasileiro tem a maior extensão de fronteira internacional?', ['Acre', 'Roraima', 'Amazonas', 'Mato Grosso do Sul'], 2, 'O Amazonas faz fronteira com Colômbia, Peru e Venezuela.'],
    ['Como é chamada a nova fronteira agrícola formada por Maranhão, Tocantins, Piauí e Bahia?', ['Vale do São Francisco', 'Triângulo Mineiro', 'Oeste Baiano', 'MATOPIBA'], 3, 'A sigla reúne as iniciais dos quatro estados dessa região do Cerrado.'],
  ],
});
