import { montar } from './montar';

/** Geografia Mundial — 100 perguntas (20 por nível). */
export const perguntasGeografiaMundial = montar('geografia-mundial', {
  1: [
    ['Qual é o maior país do mundo em área?', ['China', 'Canadá', 'Rússia', 'Estados Unidos'], 2, 'A Rússia tem mais de 17 milhões de km² e se estende por dois continentes.'],
    ['Qual é o menor continente do mundo?', ['Oceania', 'Europa', 'Antártida', 'América do Sul'], 0, 'A Oceania reúne a Austrália e milhares de ilhas do Pacífico.'],
    ['Qual é a capital da França?', ['Lyon', 'Paris', 'Marselha', 'Nice'], 1, 'Paris é cortada pelo rio Sena e abriga a Torre Eiffel e o Museu do Louvre.'],
    ['Qual é o maior oceano do planeta?', ['Atlântico', 'Índico', 'Ártico', 'Pacífico'], 3, 'O Pacífico cobre cerca de um terço da superfície da Terra.'],
    ['Qual é o maior deserto quente do mundo?', ['Saara', 'Gobi', 'Atacama', 'Kalahari'], 0, 'O Saara cobre boa parte do norte da África, com mais de 9 milhões de km².'],
    ['Qual é a capital do Japão?', ['Osaka', 'Quioto', 'Nagoia', 'Tóquio'], 3, 'A região metropolitana de Tóquio é a mais populosa do mundo.'],
    ['Em qual continente fica o Egito?', ['Ásia', 'Europa', 'África', 'Oceania'], 2, 'O Egito fica no nordeste da África, com uma pequena porção asiática na península do Sinai.'],
    ['Qual é a montanha mais alta do mundo?', ['K2', 'Monte Everest', 'Kilimanjaro', 'Aconcágua'], 1, 'O Everest tem 8.849 metros e fica na fronteira entre Nepal e China.'],
    ['Qual é a capital da Argentina?', ['Córdoba', 'Rosário', 'Mendoza', 'Buenos Aires'], 3, 'Buenos Aires fica às margens do Rio da Prata e é famosa pelo tango.'],
    ['Qual é o continente mais populoso do mundo?', ['África', 'Ásia', 'Europa', 'América'], 1, 'A Ásia concentra cerca de 60% da população mundial.'],
    ['Qual é o maior país da América do Sul?', ['Brasil', 'Argentina', 'Peru', 'Colômbia'], 0, 'O Brasil ocupa quase metade do território sul-americano.'],
    ['Qual país tem o formato parecido com o de uma bota?', ['Grécia', 'Espanha', 'Itália', 'Portugal'], 2, 'A "bota" italiana avança pelo Mediterrâneo e quase toca a ilha da Sicília.'],
    ['Qual é a capital dos Estados Unidos?', ['Nova York', 'Washington, D.C.', 'Los Angeles', 'Chicago'], 1, 'A cidade não pertence a nenhum estado: fica no Distrito de Columbia.'],
    ['Qual continente é quase todo coberto de gelo e não tem população permanente?', ['Ásia', 'Europa', 'Antártida', 'Oceania'], 2, 'Apenas cientistas vivem lá temporariamente, em bases de pesquisa.'],
    ['Qual é o rio mais longo da África?', ['Congo', 'Zambeze', 'Níger', 'Nilo'], 3, 'O Nilo percorre cerca de 6.650 km e deságua no Mediterrâneo.'],
    ['Qual é a capital de Portugal?', ['Lisboa', 'Porto', 'Coimbra', 'Braga'], 0, 'Lisboa fica na foz do rio Tejo e é uma das capitais mais antigas da Europa.'],
    ['Quantos continentes existem, segundo o modelo ensinado no Brasil?', ['Seis', 'Cinco', 'Sete', 'Quatro'], 0, 'América, Europa, Ásia, África, Oceania e Antártida.'],
    ['Qual país é conhecido como "a terra do sol nascente"?', ['China', 'Coreia do Sul', 'Japão', 'Tailândia'], 2, 'O nome do país em japonês, Nippon, significa "origem do sol".'],
    ['Qual é a capital da Itália?', ['Milão', 'Roma', 'Nápoles', 'Veneza'], 1, 'Roma abriga o Coliseu e cerca o menor país do mundo, o Vaticano.'],
    ['Qual é o maior país da África em área?', ['Egito', 'África do Sul', 'Nigéria', 'Argélia'], 3, 'A Argélia tem cerca de 2,38 milhões de km², em boa parte no deserto do Saara.'],
  ],
  2: [
    ['Qual é a capital da Austrália?', ['Sydney', 'Canberra', 'Melbourne', 'Perth'], 1, 'Canberra foi construída como solução de compromisso entre Sydney e Melbourne.'],
    ['Qual é a capital do Canadá?', ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], 3, 'Ottawa fica na província de Ontário, perto da fronteira com Quebec.'],
    ['Qual cordilheira percorre a América do Sul de norte a sul?', ['Andes', 'Rochosas', 'Alpes', 'Himalaia'], 0, 'Os Andes têm cerca de 7 mil km e atravessam sete países.'],
    ['Qual estreito separa a Europa da África no Mediterrâneo?', ['Estreito de Bering', 'Canal da Mancha', 'Estreito de Gibraltar', 'Estreito de Bósforo'], 2, 'O estreito tem apenas 14 quilômetros em seu ponto mais estreito.'],
    ['Qual país é formado por mais de 17 mil ilhas?', ['Filipinas', 'Japão', 'Maldivas', 'Indonésia'], 3, 'A Indonésia é o maior arquipélago do mundo, com Java como ilha mais populosa.'],
    ['Qual é a capital da Rússia?', ['São Petersburgo', 'Moscou', 'Kiev', 'Minsk'], 1, 'Moscou abriga o Kremlin e a Praça Vermelha.'],
    ['Qual canal liga o oceano Atlântico ao Pacífico na América Central?', ['Canal de Suez', 'Canal da Mancha', 'Canal do Panamá', 'Canal de Corinto'], 2, 'Inaugurado em 1914, encurtou em milhares de quilômetros as rotas marítimas.'],
    ['Qual canal liga o Mediterrâneo ao Mar Vermelho?', ['Canal de Suez', 'Canal do Panamá', 'Canal de Kiel', 'Canal de Corinto'], 0, 'O canal egípcio, aberto em 1869, é uma das rotas comerciais mais movimentadas do mundo.'],
    ['Qual é o menor país do mundo em área?', ['Vaticano', 'Mônaco', 'San Marino', 'Malta'], 0, 'O Vaticano tem 0,44 km² e fica inteiramente dentro da cidade de Roma.'],
    ['Qual é a capital da Alemanha?', ['Munique', 'Frankfurt', 'Berlim', 'Hamburgo'], 2, 'Berlim voltou a ser capital após a reunificação alemã, em 1990.'],
    ['Qual é a capital da China?', ['Xangai', 'Hong Kong', 'Cantão', 'Pequim'], 3, 'Pequim abriga a Cidade Proibida e a Praça da Paz Celestial.'],
    ['Qual país sul-americano é longo e estreito, com mais de 4 mil km de norte a sul?', ['Peru', 'Chile', 'Argentina', 'Colômbia'], 1, 'O Chile tem em média apenas 180 km de largura.'],
    ['Qual é a maior ilha do mundo?', ['Madagascar', 'Nova Guiné', 'Groenlândia', 'Bornéu'], 2, 'A Groenlândia tem cerca de 2,1 milhões de km² e pertence à Dinamarca.'],
    ['Qual é o maior lago de água doce do mundo em área?', ['Lago Superior', 'Mar Cáspio', 'Lago Vitória', 'Lago Baikal'], 0, 'O Lago Superior fica na fronteira entre Estados Unidos e Canadá.'],
    ['Qual é a capital do Peru?', ['Cusco', 'Lima', 'Arequipa', 'Trujillo'], 1, 'Lima foi fundada por Francisco Pizarro em 1535 e fica no litoral do Pacífico.'],
    ['Em qual país fica Machu Picchu?', ['Bolívia', 'Chile', 'Equador', 'Peru'], 3, 'A cidadela inca fica a 2.430 metros de altitude, na região de Cusco.'],
    ['Qual é a capital do México?', ['Guadalajara', 'Monterrei', 'Cancún', 'Cidade do México'], 3, 'A capital foi erguida sobre as ruínas de Tenochtitlán, a capital asteca.'],
    ['Qual cordilheira tem os picos mais altos do mundo?', ['Andes', 'Himalaia', 'Alpes', 'Cáucaso'], 1, 'O Himalaia concentra as 14 montanhas com mais de 8 mil metros do planeta.'],
    ['Qual país tem Madri como capital?', ['Espanha', 'Portugal', 'Itália', 'França'], 0, 'Madri fica no centro geográfico da Península Ibérica.'],
    ['Qual é o mar mais salgado do mundo, entre Israel e Jordânia?', ['Mar Vermelho', 'Mar Cáspio', 'Mar Morto', 'Mar Negro'], 2, 'A alta salinidade faz o corpo humano boiar sem esforço.'],
  ],
  3: [
    ['Qual é o país mais visitado do mundo por turistas estrangeiros?', ['França', 'Espanha', 'Estados Unidos', 'Itália'], 0, 'A França recebe habitualmente mais de 80 milhões de visitantes por ano.'],
    ['Qual é a capital da Índia?', ['Mumbai', 'Calcutá', 'Nova Délhi', 'Bangalore'], 2, 'Nova Délhi foi planejada pelos britânicos e inaugurada como capital em 1931.'],
    ['Qual país africano tem a maior população?', ['Egito', 'África do Sul', 'Etiópia', 'Nigéria'], 3, 'A Nigéria tem mais de 200 milhões de habitantes.'],
    ['Qual estreito separa a Ásia da América do Norte?', ['Estreito de Magalhães', 'Estreito de Bering', 'Estreito de Ormuz', 'Estreito de Málaca'], 1, 'Rússia e Alasca ficam a apenas 82 quilômetros de distância.'],
    ['Qual vulcão italiano destruiu a cidade de Pompeia no ano 79?', ['Etna', 'Stromboli', 'Vesúvio', 'Vulcano'], 2, 'As cinzas preservaram a cidade, redescoberta no século XVIII.'],
    ['Qual cadeia de montanhas é usada como divisa entre Europa e Ásia?', ['Montes Urais', 'Alpes', 'Cárpatos', 'Pirineus'], 0, 'Os Urais cortam a Rússia de norte a sul por cerca de 2.500 km.'],
    ['Qual é o maior país inteiramente europeu em área?', ['Alemanha', 'Ucrânia', 'França', 'Espanha'], 1, 'A Ucrânia tem cerca de 603 mil km², sem contar a Rússia, que é transcontinental.'],
    ['Qual é a capital administrativa da África do Sul?', ['Cidade do Cabo', 'Joanesburgo', 'Bloemfontein', 'Pretória'], 3, 'O país tem três capitais: executiva em Pretória, legislativa na Cidade do Cabo e judiciária em Bloemfontein.'],
    ['Qual é o deserto mais árido do mundo, no Chile?', ['Kalahari', 'Atacama', 'Gobi', 'Mojave'], 1, 'Há regiões do Atacama onde nunca se registrou chuva.'],
    ['Qual é a maior queda d’água do mundo em altura?', ['Cataratas do Iguaçu', 'Cataratas Vitória', 'Cataratas do Niágara', 'Salto Angel'], 3, 'O Salto Angel despenca de quase mil metros de altura.'],
    ['Em que país fica o Salto Angel?', ['Colômbia', 'Peru', 'Venezuela', 'Guiana'], 2, 'A queda fica no Parque Nacional Canaima, no sudeste venezuelano.'],
    ['Qual é o maior corpo de água cercado por terra no mundo?', ['Mar Cáspio', 'Mar Negro', 'Mar Mediterrâneo', 'Mar Báltico'], 0, 'Apesar do nome de mar, o Cáspio é tecnicamente o maior lago do planeta.'],
    ['Qual é a capital da Turquia?', ['Istambul', 'Izmir', 'Antália', 'Ancara'], 3, 'Ancara substituiu Istambul como capital em 1923, com a fundação da república.'],
    ['Qual cidade é cortada pelo estreito de Bósforo, ficando em dois continentes?', ['Atenas', 'Istambul', 'Cairo', 'Jerusalém'], 1, 'Istambul tem um lado europeu e outro asiático, ligados por pontes.'],
    ['Qual país tem o maior número de vulcões ativos?', ['Indonésia', 'Japão', 'Chile', 'Islândia'], 0, 'O arquipélago fica sobre o encontro de várias placas tectônicas.'],
    ['Como é chamada a faixa de vulcões e terremotos que cerca o oceano Pacífico?', ['Falha de San Andreas', 'Dorsal Mesoatlântica', 'Círculo de Fogo do Pacífico', 'Placa de Nazca'], 2, 'Cerca de 75% dos vulcões ativos do mundo estão nessa região.'],
    ['Qual é a capital da Noruega?', ['Estocolmo', 'Copenhague', 'Oslo', 'Helsinque'], 2, 'Oslo fica no fim de um longo fiorde, no sudeste do país.'],
    ['Qual país nórdico tem Helsinque como capital?', ['Finlândia', 'Suécia', 'Noruega', 'Dinamarca'], 0, 'A Finlândia é conhecida como o país dos mil lagos — na verdade, são quase 188 mil.'],
    ['Qual é a maior floresta de coníferas do mundo?', ['Floresta Negra', 'Floresta Amazônica', 'Floresta do Congo', 'Taiga'], 3, 'A taiga cobre o norte da Rússia, do Canadá e da Escandinávia.'],
    ['Qual é o maior país da América Central em área?', ['Costa Rica', 'Nicarágua', 'Honduras', 'Guatemala'], 1, 'A Nicarágua tem cerca de 130 mil km² e abriga o maior lago da região.'],
  ],
  4: [
    ['Qual é a capital da Coreia do Sul?', ['Busan', 'Incheon', 'Pyongyang', 'Seul'], 3, 'A região metropolitana de Seul concentra metade da população sul-coreana.'],
    ['Qual é o lago mais profundo do mundo?', ['Lago Superior', 'Lago Baikal', 'Lago Tanganica', 'Mar Cáspio'], 1, 'O Baikal, na Sibéria, tem 1.642 metros de profundidade e guarda 20% da água doce líquida do planeta.'],
    ['Qual país insular fica ao sul da Índia?', ['Maldivas', 'Mianmar', 'Sri Lanka', 'Bangladesh'], 2, 'O Sri Lanka é separado da Índia pelo estreito de Palk.'],
    ['Qual é o maior arquipélago do mundo?', ['Indonésia', 'Filipinas', 'Japão', 'Nova Zelândia'], 0, 'São mais de 17 mil ilhas espalhadas entre os oceanos Índico e Pacífico.'],
    ['Quais países são separados pela cordilheira dos Pirineus?', ['Itália e Suíça', 'Espanha e França', 'Portugal e Espanha', 'França e Alemanha'], 1, 'Entre os dois fica Andorra, um pequeno principado encravado nas montanhas.'],
    ['Qual era o nome do supercontinente que existiu há cerca de 200 milhões de anos?', ['Gondwana', 'Laurásia', 'Pangeia', 'Rodínia'], 2, 'A Pangeia se fragmentou e deu origem aos continentes atuais.'],
    ['Qual é a capital da Etiópia, sede da União Africana?', ['Adis Abeba', 'Nairóbi', 'Cartum', 'Acra'], 0, 'Adis Abeba fica a mais de 2.300 metros de altitude.'],
    ['Qual país tem as maiores reservas de petróleo comprovadas do mundo?', ['Arábia Saudita', 'Irã', 'Rússia', 'Venezuela'], 3, 'A faixa do Orinoco concentra reservas gigantescas de petróleo pesado.'],
    ['Qual é a capital da Nova Zelândia?', ['Auckland', 'Christchurch', 'Wellington', 'Hamilton'], 2, 'Wellington é a capital mais austral do mundo entre países soberanos.'],
    ['Qual rio corta a cidade de Londres?', ['Tâmisa', 'Sena', 'Reno', 'Danúbio'], 0, 'O Tâmisa é atravessado por pontes famosas como a Tower Bridge.'],
    ['Qual rio atravessa dez países europeus e deságua no Mar Negro?', ['Reno', 'Danúbio', 'Volga', 'Elba'], 1, 'O Danúbio passa por capitais como Viena, Bratislava, Budapeste e Belgrado.'],
    ['Qual é o rio mais longo da Europa?', ['Danúbio', 'Reno', 'Dnieper', 'Volga'], 3, 'O Volga percorre 3.530 km em território russo e deságua no Mar Cáspio.'],
    ['Qual é o único país que ocupa sozinho um continente inteiro?', ['Austrália', 'Canadá', 'Rússia', 'Groenlândia'], 0, 'A Austrália é ao mesmo tempo país, continente e a maior ilha habitada do mundo.'],
    ['Qual é a capital do Egito?', ['Alexandria', 'Luxor', 'Assuã', 'Cairo'], 3, 'O Cairo fica às margens do Nilo, perto das pirâmides de Gizé.'],
    ['Qual país tem uma folha de bordo em sua bandeira?', ['Estados Unidos', 'Canadá', 'Suíça', 'Líbano'], 1, 'A bandeira canadense atual foi adotada em 1965.'],
    ['Qual oceano banha a costa oeste do continente africano?', ['Índico', 'Pacífico', 'Atlântico', 'Ártico'], 2, 'O Atlântico separa a África das Américas.'],
    ['Qual é a capital da Arábia Saudita?', ['Meca', 'Riad', 'Jidá', 'Medina'], 1, 'Riad fica no interior desértico do país e concentra o poder político.'],
    ['Além do Paraguai, qual país sul-americano não tem saída para o mar?', ['Equador', 'Uruguai', 'Guiana', 'Bolívia'], 3, 'A Bolívia perdeu seu litoral para o Chile na Guerra do Pacífico, no século XIX.'],
    ['Qual é a cidade mais populosa da Oceania?', ['Melbourne', 'Auckland', 'Sydney', 'Brisbane'], 2, 'Sydney tem mais de 5 milhões de habitantes e é famosa por sua Opera House.'],
    ['Qual é a capital do Chile?', ['Santiago', 'Valparaíso', 'Concepción', 'Antofagasta'], 0, 'Santiago fica em um vale cercado pelos Andes, a cerca de 100 km do Pacífico.'],
  ],
  5: [
    ['Qual é o país mais recente reconhecido pela ONU?', ['Kosovo', 'Timor-Leste', 'Sudão do Sul', 'Montenegro'], 2, 'O Sudão do Sul tornou-se independente em julho de 2011.'],
    ['Qual é o único país que faz fronteira terrestre com Portugal?', ['França', 'Marrocos', 'Andorra', 'Espanha'], 3, 'A fronteira luso-espanhola tem cerca de 1.200 km e é uma das mais antigas da Europa.'],
    ['Qual é o ponto mais baixo em terra firme do planeta?', ['Vale da Morte', 'As margens do Mar Morto', 'Depressão de Danakil', 'Lago Assal'], 1, 'As margens do Mar Morto estão a cerca de 430 metros abaixo do nível do mar.'],
    ['Qual é a fossa oceânica mais profunda do planeta?', ['Fossa das Marianas', 'Fossa do Japão', 'Fossa de Porto Rico', 'Fossa de Tonga'], 0, 'O Abismo Challenger, nas Marianas, chega a quase 11 mil metros de profundidade.'],
    ['Qual estreito liga o Golfo Pérsico ao Golfo de Omã?', ['Estreito de Ormuz', 'Estreito de Málaca', 'Bab-el-Mandeb', 'Estreito de Bósforo'], 0, 'Por ali passa cerca de um quinto de todo o petróleo consumido no mundo.'],
    ['Qual cidade é a sede do governo da Bolívia?', ['Sucre', 'La Paz', 'Santa Cruz de la Sierra', 'Cochabamba'], 1, 'Sucre é a capital constitucional, mas o governo funciona em La Paz.'],
    ['Considerando também os desertos frios, qual é o maior deserto do mundo?', ['Saara', 'Gobi', 'Ártico', 'Antártida'], 3, 'A Antártida é um deserto polar: quase não chove ou neva no interior do continente.'],
    ['Qual país tem o litoral mais extenso do mundo?', ['Rússia', 'Austrália', 'Canadá', 'Indonésia'], 2, 'Somadas as ilhas do Ártico, a costa canadense passa de 200 mil quilômetros.'],
    ['Qual é o ponto mais alto do continente africano?', ['Monte Quênia', 'Kilimanjaro', 'Monte Stanley', 'Ras Dashen'], 1, 'O Kilimanjaro, na Tanzânia, tem 5.895 metros e é um vulcão adormecido.'],
    ['Qual é o maior país do mundo sem saída para o mar?', ['Mongólia', 'Etiópia', 'Cazaquistão', 'Chade'], 2, 'O Cazaquistão tem 2,7 milhões de km² e faz fronteira apenas com mares interiores.'],
    ['Qual é a capital constitucional dos Países Baixos, mesmo sem sediar o governo?', ['Amsterdã', 'Haia', 'Roterdã', 'Utrecht'], 0, 'O governo e a família real ficam em Haia, mas a capital oficial é Amsterdã.'],
    ['Qual é o único país que faz fronteira terrestre com a Dinamarca?', ['Suécia', 'Noruega', 'Países Baixos', 'Alemanha'], 3, 'A fronteira fica na península da Jutlândia, ao sul do país.'],
    ['Qual arquipélago português fica no Atlântico, a oeste de Portugal continental?', ['Canárias', 'Baleares', 'Cabo Verde', 'Açores'], 3, 'São nove ilhas vulcânicas a cerca de 1.400 km do continente.'],
    ['Qual mar banha o litoral da Croácia?', ['Mar Adriático', 'Mar Egeu', 'Mar Jônico', 'Mar Tirreno'], 0, 'O Adriático separa a península Itálica dos Bálcãs.'],
    ['Qual é o menor país independente da América do Sul em área?', ['Guiana', 'Uruguai', 'Suriname', 'Equador'], 2, 'O Suriname tem cerca de 163 mil km² e foi colônia holandesa.'],
    ['Qual é a capital do Quênia?', ['Mombaça', 'Nairóbi', 'Kisumu', 'Nakuru'], 1, 'Nairóbi tem um parque nacional com animais selvagens dentro da área urbana.'],
    ['Qual é o maior país insular do mundo em área?', ['Indonésia', 'Madagascar', 'Japão', 'Reino Unido'], 0, 'A Indonésia soma cerca de 1,9 milhão de km² espalhados por milhares de ilhas.'],
    ['Qual cidade sedia a Corte Internacional de Justiça?', ['Genebra', 'Haia', 'Bruxelas', 'Viena'], 1, 'O tribunal funciona no Palácio da Paz, em Haia, desde 1946.'],
    ['Qual corrente marítima fria banha a costa do Peru e do Chile?', ['Corrente do Golfo', 'Corrente do Brasil', 'Corrente de Humboldt', 'Corrente do Labrador'], 2, 'Ela torna o litoral extremamente seco e é responsável pela riqueza pesqueira da região.'],
    ['O que provoca as auroras polares?', ['O reflexo da luz no gelo', 'A refração da luz solar nas nuvens', 'A poluição luminosa das cidades', 'O vento solar atingindo a atmosfera'], 3, 'Partículas do Sol colidem com gases da alta atmosfera e produzem luz colorida.'],
  ],
});
