import { montar } from './montar';

/** História Geral — 100 perguntas (20 por nível). */
export const perguntasHistoriaGeral = montar('historia-geral', {
  1: [
    ['Qual civilização antiga construiu as pirâmides de Gizé?', ['A grega', 'A romana', 'A egípcia', 'A persa'], 2, 'As pirâmides foram erguidas por volta de 2500 a.C. como túmulos dos faraós.'],
    ['Quem liderou a Alemanha durante o regime nazista?', ['Adolf Hitler', 'Benito Mussolini', 'Joseph Stalin', 'Winston Churchill'], 0, 'Hitler chegou ao poder em 1933 e governou até sua morte, em abril de 1945.'],
    ['Em que ano terminou a Segunda Guerra Mundial?', ['1939', '1945', '1918', '1950'], 1, 'A guerra acabou na Europa em maio e no Pacífico em setembro de 1945.'],
    ['Qual muro dividiu a Alemanha até 1989?', ['Muro da China', 'Muro das Lamentações', 'Muro de Adriano', 'Muro de Berlim'], 3, 'Erguido em 1961, o muro separou Berlim Oriental e Ocidental por 28 anos.'],
    ['Quem chegou à América em 1492 a serviço da Espanha?', ['Cristóvão Colombo', 'Fernão de Magalhães', 'Vasco da Gama', 'Marco Polo'], 0, 'Colombo buscava uma rota para as Índias e morreu acreditando ter chegado à Ásia.'],
    ['Qual império tinha Roma como capital?', ['Império Persa', 'Império Otomano', 'Império Chinês', 'Império Romano'], 3, 'O Império Romano chegou a dominar todo o entorno do Mar Mediterrâneo.'],
    ['Em que ano começou a Primeira Guerra Mundial?', ['1905', '1912', '1914', '1920'], 2, 'O conflito começou em julho de 1914 e se estendeu até novembro de 1918.'],
    ['Qual imperador francês foi derrotado na batalha de Waterloo?', ['Luís XIV', 'Napoleão Bonaparte', 'Carlos Magno', 'Robespierre'], 1, 'Após Waterloo, em 1815, Napoleão foi exilado na ilha de Santa Helena.'],
    ['Qual revolução iniciada em 1789 derrubou a monarquia francesa?', ['Revolução Industrial', 'Revolução Russa', 'Revolução Americana', 'Revolução Francesa'], 3, 'Seu lema, "liberdade, igualdade e fraternidade", inspirou movimentos no mundo todo.'],
    ['Qual civilização antiga criou os Jogos Olímpicos?', ['A romana', 'A grega', 'A egípcia', 'A maia'], 1, 'Os jogos aconteciam em Olímpia em honra a Zeus, a partir de 776 a.C.'],
    ['Quem liderou a independência da Índia pregando a não violência?', ['Mahatma Gandhi', 'Nelson Mandela', 'Martin Luther King', 'Che Guevara'], 0, 'Gandhi defendia a desobediência civil pacífica; a Índia tornou-se independente em 1947.'],
    ['Qual país lançou bombas atômicas sobre Hiroshima e Nagasaki?', ['Alemanha', 'União Soviética', 'Estados Unidos', 'Reino Unido'], 2, 'Os ataques de agosto de 1945 precipitaram a rendição do Japão.'],
    ['Qual conflito opôs Estados Unidos e União Soviética sem confronto militar direto?', ['Guerra do Vietnã', 'Guerra Fria', 'Guerra da Coreia', 'Guerra dos Cem Anos'], 1, 'A disputa ideológica durou de 1947 a 1991 e incluiu corrida armamentista e espacial.'],
    ['Quem foi o primeiro ser humano a pisar na Lua?', ['Yuri Gagarin', 'Buzz Aldrin', 'Neil Armstrong', 'Michael Collins'], 2, 'Armstrong desceu do módulo lunar em 20 de julho de 1969.'],
    ['Qual documento os Estados Unidos assinaram em 4 de julho de 1776?', ['A Constituição dos EUA', 'A Carta Magna', 'A Declaração dos Direitos Humanos', 'A Declaração de Independência'], 3, 'O texto foi redigido principalmente por Thomas Jefferson.'],
    ['Qual líder sul-africano ficou 27 anos preso e depois se tornou presidente?', ['Nelson Mandela', 'Desmond Tutu', 'Kofi Annan', 'Patrice Lumumba'], 0, 'Mandela foi eleito em 1994, na primeira eleição multirracial da África do Sul.'],
    ['Qual povo da Mesopotâmia criou a escrita cuneiforme?', ['Os sumérios', 'Os egípcios', 'Os fenícios', 'Os hebreus'], 0, 'A escrita surgiu por volta de 3200 a.C. para registrar contas e estoques.'],
    ['Em que ano caiu o Muro de Berlim?', ['1961', '1975', '1989', '1991'], 2, 'A queda, em 9 de novembro de 1989, simbolizou o fim da Guerra Fria.'],
    ['Qual grande muralha foi construída para proteger um país asiático de invasores?', ['Muralha de Adriano', 'Muralha da China', 'Muralha de Constantinopla', 'Muralha de Jericó'], 1, 'Suas seções somam mais de 20 mil quilômetros, erguidos ao longo de séculos.'],
    ['Quem comandou a União Soviética durante a Segunda Guerra Mundial?', ['Lenin', 'Trótski', 'Gorbachev', 'Stalin'], 3, 'Stalin governou a URSS com mão de ferro de 1924 até sua morte, em 1953.'],
  ],
  2: [
    ['Qual império foi dividido em Ocidente e Oriente em 395 d.C.?', ['Império Persa', 'Império Romano', 'Império Macedônico', 'Império Otomano'], 1, 'A divisão foi decidida por Teodósio; o Oriente sobreviveria por mais mil anos como Império Bizantino.'],
    ['Quem unificou a Macedônia e conquistou o Império Persa?', ['Júlio César', 'Péricles', 'Dario', 'Alexandre, o Grande'], 3, 'Alexandre criou um império da Grécia à Índia antes de morrer aos 32 anos.'],
    ['Qual movimento cultural marcou a Europa dos séculos XV e XVI?', ['O Renascimento', 'O Iluminismo', 'O Romantismo', 'O Barroco'], 0, 'O Renascimento retomou os valores da Antiguidade clássica e valorizou o ser humano.'],
    ['Qual invenção de Gutenberg revolucionou a difusão do conhecimento?', ['A bússola', 'O telescópio', 'A prensa de tipos móveis', 'O papel'], 2, 'Por volta de 1450, a prensa barateou os livros e acelerou a circulação de ideias.'],
    ['Qual revolução começou na Inglaterra do século XVIII com as máquinas a vapor?', ['Revolução Francesa', 'Revolução Gloriosa', 'Revolução Russa', 'Revolução Industrial'], 3, 'A mecanização transformou a produção, as cidades e as relações de trabalho.'],
    ['Em que ano os bolcheviques tomaram o poder na Rússia?', ['1905', '1917', '1922', '1929'], 1, 'A Revolução de Outubro de 1917 derrubou o governo provisório e criou o Estado soviético.'],
    ['Quem liderou os bolcheviques na Revolução Russa?', ['Stalin', 'Trótski', 'Lenin', 'Gorbachev'], 2, 'Vladimir Lenin chefiou o novo governo até sua morte, em 1924.'],
    ['Qual conflito entre 1936 e 1939 levou Francisco Franco ao poder?', ['A Guerra Civil Espanhola', 'A Guerra dos Bôeres', 'A Guerra da Crimeia', 'A Guerra Civil Grega'], 0, 'Franco governaria a Espanha como ditador por quase 40 anos.'],
    ['Qual tratado encerrou formalmente a Primeira Guerra Mundial, em 1919?', ['Tratado de Versalhes', 'Tratado de Tordesilhas', 'Tratado de Viena', 'Tratado de Paris'], 0, 'As duras reparações impostas à Alemanha ajudaram a criar o ambiente para a Segunda Guerra.'],
    ['Qual organização internacional foi criada em 1945 para preservar a paz?', ['Liga das Nações', 'OTAN', 'ONU', 'União Europeia'], 2, 'A Organização das Nações Unidas substituiu a fracassada Liga das Nações.'],
    ['Qual era o nome do regime de segregação racial da África do Sul?', ['Jim Crow', 'Gueto', 'Colonialismo', 'Apartheid'], 3, 'O apartheid vigorou oficialmente de 1948 a 1994.'],
    ['Em que ano os Estados Unidos entraram na Segunda Guerra Mundial?', ['1939', '1941', '1943', '1945'], 1, 'A entrada ocorreu em dezembro de 1941, logo após o ataque a Pearl Harbor.'],
    ['Qual ataque japonês levou os Estados Unidos à Segunda Guerra Mundial?', ['A Batalha de Midway', 'A Batalha de Okinawa', 'O ataque a Pearl Harbor', 'A Batalha do Mar de Coral'], 2, 'A base naval no Havaí foi bombardeada em 7 de dezembro de 1941.'],
    ['Qual civilização pré-colombiana dominava o México quando os espanhóis chegaram?', ['Os astecas', 'Os incas', 'Os maias', 'Os olmecas'], 0, 'A capital asteca, Tenochtitlán, foi conquistada por Hernán Cortés em 1521.'],
    ['Qual civilização pré-colombiana tinha Cusco como capital?', ['Os astecas', 'Os incas', 'Os maias', 'Os toltecas'], 1, 'O império inca se estendia pelos Andes, do sul da Colômbia ao norte do Chile.'],
    ['Qual conquistador espanhol derrotou o Império Inca?', ['Hernán Cortés', 'Diego de Almagro', 'Pedro de Valdivia', 'Francisco Pizarro'], 3, 'Pizarro capturou o imperador Atahualpa em 1532 com pouco mais de 160 homens.'],
    ['Qual epidemia matou cerca de um terço da população europeia no século XIV?', ['A cólera', 'A varíola', 'O tifo', 'A Peste Negra'], 3, 'A peste bubônica chegou pelos portos e devastou a Europa entre 1347 e 1351.'],
    ['Qual religião foi fundada por Maomé no século VII?', ['Judaísmo', 'Islamismo', 'Budismo', 'Hinduísmo'], 1, 'A Hégira, fuga de Maomé para Medina em 622, marca o início do calendário islâmico.'],
    ['Em que data ocorreu o Dia D, o desembarque aliado na Normandia?', ['6 de junho de 1944', '1º de setembro de 1939', '8 de maio de 1945', '7 de dezembro de 1941'], 0, 'Foi a maior operação anfíbia da história, com mais de 150 mil soldados aliados.'],
    ['Qual imperador romano legalizou o cristianismo no Império?', ['Nero', 'Calígula', 'Constantino', 'Trajano'], 2, 'O Édito de Milão, de 313, garantiu liberdade de culto aos cristãos.'],
  ],
  3: [
    ['Qual documento inglês de 1215 limitou os poderes do rei?', ['A Magna Carta', 'O Bill of Rights', 'O Ato de Supremacia', 'A Petição de Direitos'], 0, 'Imposta a João Sem-Terra pelos barões, é considerada base do constitucionalismo.'],
    ['Qual rei inglês rompeu com Roma e criou a Igreja Anglicana?', ['Ricardo Coração de Leão', 'Jorge III', 'Henrique VIII', 'Eduardo VI'], 2, 'A ruptura veio em 1534, depois que o papa negou a anulação de seu casamento.'],
    ['Quem deu início à Reforma Protestante, em 1517?', ['João Calvino', 'Henrique VIII', 'Erasmo de Roterdã', 'Martinho Lutero'], 3, 'Lutero divulgou 95 teses criticando a venda de indulgências pela Igreja Católica.'],
    ['Qual concílio organizou a resposta católica à Reforma Protestante?', ['Concílio de Niceia', 'Concílio de Trento', 'Concílio Vaticano I', 'Concílio de Éfeso'], 1, 'Reunido entre 1545 e 1563, reafirmou dogmas e criou o Index de livros proibidos.'],
    ['Qual guerra entre França e Inglaterra durou de 1337 a 1453?', ['Guerra das Rosas', 'Guerra dos Trinta Anos', 'Guerra dos Cem Anos', 'Guerra da Sucessão Espanhola'], 2, 'Apesar do nome, o conflito durou 116 anos, com longas tréguas.'],
    ['Qual camponesa francesa liderou tropas e foi queimada como herege em 1431?', ['Joana d’Arc', 'Maria Antonieta', 'Catarina de Médici', 'Isabel de Castela'], 0, 'Joana foi reabilitada pela Igreja em 1456 e canonizada em 1920.'],
    ['Como ficou conhecida a fase mais violenta da Revolução Francesa, sob Robespierre?', ['Diretório', 'O Terror', 'Termidor', 'Consulado'], 1, 'Entre 1793 e 1794, milhares foram guilhotinados — inclusive o próprio Robespierre.'],
    ['Quem foi o primeiro presidente dos Estados Unidos?', ['Thomas Jefferson', 'Abraham Lincoln', 'Benjamin Franklin', 'George Washington'], 3, 'Washington comandou o exército revolucionário e governou de 1789 a 1797.'],
    ['Qual presidente americano aboliu a escravidão durante a Guerra Civil?', ['George Washington', 'Abraham Lincoln', 'Theodore Roosevelt', 'Andrew Jackson'], 1, 'A Proclamação de Emancipação é de 1863; Lincoln foi assassinado em 1865.'],
    ['Qual crise econômica começou com a quebra da Bolsa de Nova York em 1929?', ['A Crise do Petróleo', 'A crise do subprime', 'A crise das tulipas', 'A Grande Depressão'], 3, 'O desemprego chegou a um quarto da força de trabalho americana.'],
    ['Qual líder proclamou a República Popular da China, em 1949?', ['Chiang Kai-shek', 'Deng Xiaoping', 'Mao Tsé-Tung', 'Sun Yat-sen'], 2, 'Mao venceu a guerra civil contra os nacionalistas, que se refugiaram em Taiwan.'],
    ['Qual guerra dividiu a península coreana em dois países na década de 1950?', ['A Guerra da Coreia', 'A Guerra do Vietnã', 'A Guerra do Golfo', 'A Guerra da Indochina'], 0, 'O conflito de 1950 a 1953 terminou em armistício — tecnicamente, nunca houve tratado de paz.'],
    ['Qual crise de 1962 quase provocou uma guerra nuclear entre EUA e URSS?', ['Guerra dos Seis Dias', 'Crise do Canal de Suez', 'Bloqueio de Berlim', 'Crise dos Mísseis de Cuba'], 3, 'Os soviéticos instalaram mísseis em Cuba e recuaram após 13 dias de tensão.'],
    ['Quem liderou a Revolução Cubana de 1959?', ['Che Guevara', 'Fidel Castro', 'Camilo Cienfuegos', 'Fulgencio Batista'], 1, 'Fidel derrubou o ditador Batista e governou Cuba por quase meio século.'],
    ['Em que ano a União Soviética deixou de existir?', ['1991', '1989', '1985', '1993'], 0, 'A dissolução foi oficializada em dezembro de 1991, dando origem a 15 países.'],
    ['Qual líder soviético promoveu a perestroika e a glasnost?', ['Nikita Kruschev', 'Leonid Brejnev', 'Mikhail Gorbachev', 'Boris Yeltsin'], 2, 'As reformas de reestruturação e transparência aceleraram o fim da URSS.'],
    ['Qual império conquistou Constantinopla em 1453?', ['Império Romano', 'Império Persa', 'Império Otomano', 'Império Mongol'], 2, 'A queda da cidade, sob Mehmed II, é usada para marcar o fim da Idade Média.'],
    ['Quem criou o maior império contíguo da história, no século XIII?', ['Gengis Khan', 'Kublai Khan', 'Tamerlão', 'Átila'], 0, 'O império mongol ia da China à Europa Oriental.'],
    ['Qual movimento intelectual do século XVIII defendeu a razão e a liberdade?', ['Renascimento', 'Romantismo', 'Positivismo', 'Iluminismo'], 3, 'As ideias iluministas inspiraram as revoluções Americana e Francesa.'],
    ['Quem escreveu "O Contrato Social", obra central do Iluminismo?', ['Montesquieu', 'Jean-Jacques Rousseau', 'Voltaire', 'John Locke'], 1, 'Rousseau defendeu que a soberania pertence ao povo, e não ao rei.'],
  ],
  4: [
    ['Qual dinastia unificou a China em 221 a.C.?', ['Dinastia Han', 'Dinastia Ming', 'Dinastia Tang', 'Dinastia Qin'], 3, 'O imperador Qin Shi Huang também iniciou a Grande Muralha e o exército de terracota.'],
    ['Qual batalha, em 1815, encerrou definitivamente o domínio de Napoleão?', ['Austerlitz', 'Waterloo', 'Trafalgar', 'Leipzig'], 1, 'A derrota para britânicos e prussianos na Bélgica selou o fim do Império Napoleônico.'],
    ['Qual congresso reorganizou a Europa após a queda de Napoleão?', ['Congresso de Berlim', 'Congresso de Paris', 'Congresso de Viena', 'Congresso de Vestfália'], 2, 'Entre 1814 e 1815, as potências redesenharam fronteiras e restauraram monarquias.'],
    ['Qual acordo de 1648 encerrou a Guerra dos Trinta Anos?', ['A Paz de Vestfália', 'A Paz de Augsburgo', 'O Tratado de Utrecht', 'O Tratado de Versalhes'], 0, 'É considerada a origem do conceito moderno de Estado soberano.'],
    ['Qual chanceler conduziu a unificação da Alemanha, concluída em 1871?', ['Guilherme I', 'Otto von Bismarck', 'Frederico, o Grande', 'Konrad Adenauer'], 1, 'Bismarck ficou conhecido como o "Chanceler de Ferro" por sua política de "sangue e ferro".'],
    ['Quem liderou os "camisas vermelhas" na unificação da Itália?', ['Camillo Cavour', 'Vítor Emanuel II', 'Giuseppe Garibaldi', 'Giuseppe Mazzini'], 2, 'Garibaldi lutou também na América do Sul, inclusive na Revolução Farroupilha.'],
    ['Qual conferência de 1884 e 1885 repartiu a África entre potências europeias?', ['Conferência de Berlim', 'Conferência de Yalta', 'Conferência de Bandung', 'Congresso de Viena'], 0, 'As fronteiras traçadas ignoraram etnias e ainda geram conflitos no continente.'],
    ['Qual assassinato em Sarajevo desencadeou a Primeira Guerra Mundial?', ['Do czar Nicolau II', 'De Jean Jaurès', 'Do rei Alberto da Bélgica', 'Do arquiduque Francisco Ferdinando'], 3, 'O herdeiro do trono austro-húngaro foi morto em 28 de junho de 1914.'],
    ['Qual plano americano financiou a reconstrução da Europa após 1945?', ['Plano Schuman', 'Doutrina Truman', 'Plano Marshall', 'Plano Dawes'], 2, 'Foram cerca de 13 bilhões de dólares investidos entre 1948 e 1952.'],
    ['Qual conferência de 1945 definiu a divisão da Europa entre os aliados?', ['Conferência de Yalta', 'Conferência de Paris', 'Conferência de Munique', 'Conferência de Bandung'], 0, 'Roosevelt, Churchill e Stalin se reuniram na Crimeia em fevereiro de 1945.'],
    ['Como é chamado o genocídio de judeus promovido pelo regime nazista?', ['Pogrom', 'Holocausto', 'Kristallnacht', 'Diáspora'], 1, 'Cerca de seis milhões de judeus foram assassinados, além de ciganos, eslavos e outros grupos.'],
    ['Quem foi o primeiro-ministro da Índia após a independência, em 1947?', ['Mahatma Gandhi', 'Indira Gandhi', 'B. R. Ambedkar', 'Jawaharlal Nehru'], 3, 'Nehru governou por 17 anos e foi pai de Indira Gandhi, futura primeira-ministra.'],
    ['Qual país se separou da Índia em 1947 para formar um Estado de maioria muçulmana?', ['Paquistão', 'Bangladesh', 'Sri Lanka', 'Afeganistão'], 0, 'A Partilha provocou o deslocamento de milhões de pessoas e violência em massa.'],
    ['Em que ano foi fundado o Estado de Israel?', ['1918', '1939', '1945', '1948'], 3, 'A proclamação ocorreu em 14 de maio de 1948, após a partilha aprovada pela ONU.'],
    ['Qual política econômica Lenin adotou em 1921 para recuperar a Rússia?', ['Comunismo de guerra', 'Nova Política Econômica (NEP)', 'Planos Quinquenais', 'Coletivização forçada'], 1, 'A NEP permitiu pequenos negócios privados e a volta parcial do mercado.'],
    ['Quem popularizou a expressão "Cortina de Ferro"?', ['Harry Truman', 'Franklin Roosevelt', 'Winston Churchill', 'Charles de Gaulle'], 2, 'Churchill usou a expressão em um discurso nos Estados Unidos, em 1946.'],
    ['Qual revolução de 1979 transformou o Irã em uma república islâmica?', ['Revolução Verde', 'Revolução Islâmica', 'Revolução Branca', 'Primavera Árabe'], 1, 'O aiatolá Khomeini voltou do exílio e derrubou o xá Reza Pahlevi.'],
    ['Qual missão espacial levou os primeiros humanos à Lua, em 1969?', ['Soyuz 11', 'Gemini 8', 'Vostok 1', 'Apollo 11'], 3, 'A missão da Nasa levou Armstrong, Aldrin e Collins; os dois primeiros desceram na Lua.'],
    ['Quem foi o primeiro ser humano a viajar ao espaço?', ['Neil Armstrong', 'Alan Shepard', 'Yuri Gagarin', 'Valentina Tereshkova'], 2, 'O soviético orbitou a Terra em 12 de abril de 1961, a bordo da Vostok 1.'],
    ['Qual tratado de 1957 criou a Comunidade Econômica Europeia?', ['Tratado de Roma', 'Tratado de Maastricht', 'Tratado de Lisboa', 'Tratado de Paris'], 0, 'Seis países assinaram o acordo que daria origem à atual União Europeia.'],
  ],
  5: [
    ['Qual código de leis da Babilônia é um dos mais antigos já encontrados?', ['Código de Justiniano', 'Lei das Doze Tábuas', 'Código de Hamurabi', 'Código de Napoleão'], 2, 'Gravado em uma estela de pedra por volta de 1750 a.C., trazia a lei de talião.'],
    ['Qual faraó tentou impor no Egito o culto a um único deus, Aton?', ['Tutancâmon', 'Ramsés II', 'Quéops', 'Akhenaton'], 3, 'A reforma religiosa foi abandonada logo após sua morte, no século XIV a.C.'],
    ['Em qual batalha, em 490 a.C., os atenienses derrotaram os persas?', ['Termópilas', 'Maratona', 'Salamina', 'Plateias'], 1, 'A corrida de maratona homenageia o soldado que teria levado a notícia da vitória a Atenas.'],
    ['Qual general cartaginês cruzou os Alpes com elefantes para atacar Roma?', ['Aníbal', 'Cipião', 'Asdrúbal', 'Amílcar'], 0, 'A travessia ocorreu em 218 a.C., durante a Segunda Guerra Púnica.'],
    ['Qual imperador dividiu o poder romano no sistema de tetrarquia?', ['Diocleciano', 'Augusto', 'Nero', 'Adriano'], 0, 'A partir de 293, o império passou a ser governado por dois augustos e dois césares.'],
    ['Em que ano caiu o Império Romano do Ocidente?', ['410 d.C.', '476 d.C.', '395 d.C.', '1453 d.C.'], 1, 'O último imperador, Rômulo Augústulo, foi deposto pelo germânico Odoacro.'],
    ['Quem foi coroado imperador do Ocidente no Natal do ano 800?', ['Otto I', 'Clóvis', 'Pepino, o Breve', 'Carlos Magno'], 3, 'O papa Leão III coroou Carlos Magno, unindo poder político e autoridade religiosa.'],
    ['Qual dinastia francesa foi fundada por Hugo Capeto, em 987?', ['Merovíngia', 'Carolíngia', 'Capetíngia', 'Bourbon'], 2, 'Os capetíngios e seus ramos governaram a França por mais de oito séculos.'],
    ['Qual cidade italiana é considerada o berço do Renascimento?', ['Veneza', 'Florença', 'Roma', 'Milão'], 1, 'O mecenato da família Médici financiou artistas como Botticelli e Michelangelo.'],
    ['Quem comandou a expedição que realizou a primeira volta ao mundo?', ['Vasco da Gama', 'Bartolomeu Dias', 'Fernão de Magalhães', 'Francis Drake'], 2, 'Magalhães morreu nas Filipinas em 1521; Juan Sebastián Elcano concluiu a viagem.'],
    ['Qual rei francês ficou conhecido como o "Rei Sol"?', ['Luís XIV', 'Luís XVI', 'Francisco I', 'Henrique IV'], 0, 'Luís XIV reinou por 72 anos e construiu o Palácio de Versalhes.'],
    ['Qual revolução inglesa de 1688 consolidou a monarquia parlamentar?', ['Revolução Puritana', 'Revolução Industrial', 'Restauração', 'Revolução Gloriosa'], 3, 'O novo rei aceitou a Declaração de Direitos, submetendo a coroa ao Parlamento.'],
    ['Qual czar modernizou a Rússia e fundou São Petersburgo?', ['Ivan, o Terrível', 'Nicolau II', 'Catarina, a Grande', 'Pedro, o Grande'], 3, 'Pedro I criou a nova capital em 1703 para aproximar a Rússia da Europa Ocidental.'],
    ['Quem liderou a revolução que tornou o Haiti independente em 1804?', ['Toussaint Louverture', 'Simón Bolívar', 'José de San Martín', 'Miguel Hidalgo'], 0, 'Foi a única revolução de pessoas escravizadas que resultou na fundação de um Estado.'],
    ['Quem é chamado de "O Libertador" na independência da América espanhola?', ['José de San Martín', 'Bernardo O’Higgins', 'Simón Bolívar', 'Antonio José de Sucre'], 2, 'Bolívar libertou os atuais Venezuela, Colômbia, Equador, Peru e Bolívia.'],
    ['Qual guerra de 1899 a 1902 opôs britânicos e colonos de origem holandesa na África?', ['Guerra do Ópio', 'Guerra dos Bôeres', 'Guerra Zulu', 'Guerra da Crimeia'], 1, 'O conflito na África do Sul ficou marcado pelo uso de campos de concentração britânicos.'],
    ['Quais guerras do século XIX forçaram a China a abrir seus portos aos britânicos?', ['As Guerras do Ópio', 'A Revolta dos Boxers', 'As Guerras Sino-Japonesas', 'A Revolta Taiping'], 0, 'Após a derrota, a China cedeu Hong Kong ao Reino Unido em 1842.'],
    ['Qual tribunal julgou os líderes nazistas após a Segunda Guerra Mundial?', ['Tribunal de Haia', 'Tribunal de Nuremberg', 'Tribunal de Tóquio', 'Comissão de Yalta'], 1, 'Os julgamentos de 1945 e 1946 criaram o conceito jurídico de crime contra a humanidade.'],
    ['Qual país foi dividido pelo paralelo 17 após os acordos de 1954?', ['Coreia', 'Alemanha', 'Vietnã', 'Iêmen'], 2, 'A divisão entre Norte comunista e Sul pró-ocidente levou à Guerra do Vietnã.'],
    ['Qual movimento sindical polonês foi liderado por Lech Walesa?', ['Carta 77', 'Primavera de Praga', 'Perestroika', 'Solidariedade'], 3, 'O Solidariedade nasceu nos estaleiros de Gdansk em 1980 e abalou o bloco soviético.'],
  ],
});
