import { montar } from './montar';

/** Língua Portuguesa — 100 perguntas (20 por nível). */
export const perguntasLinguaPortuguesa = montar('lingua-portuguesa', {
  1: [
    ['Qual é o plural de "cidadão"?', ['cidadães', 'cidadans', 'cidadãos', 'cidadões'], 2, 'Palavras terminadas em "-ão" fazem o plural de três formas; nesta, é "-ãos".'],
    ['Qual destas palavras está escrita corretamente?', ['exceção', 'esceção', 'excessão', 'eceção'], 0, 'A palavra vem do latim "exceptio" e mantém o grupo "xc".'],
    ['Qual é o feminino de "ator"?', ['atora', 'atriz', 'atoresa', 'atriza'], 1, 'É um caso de feminino irregular, herdado do latim.'],
    ['Quantas letras tem o alfabeto da língua portuguesa?', ['23', '24', '25', '26'], 3, 'K, W e Y foram oficialmente reincorporadas pelo Acordo Ortográfico.'],
    ['Qual destas palavras é um verbo?', ['correr', 'bonito', 'mesa', 'rápido'], 0, 'Verbos indicam ação, estado ou fenômeno.'],
    ['Qual é o substantivo coletivo de estrelas?', ['bando', 'cardume', 'matilha', 'constelação'], 3, 'Cardume é de peixes, matilha de cães e bando de aves.'],
    ['Qual palavra é sinônimo de "belo"?', ['feio', 'triste', 'bonito', 'grande'], 2, 'Sinônimos são palavras de sentido parecido.'],
    ['Qual é o antônimo de "alegre"?', ['feliz', 'triste', 'contente', 'animado'], 1, 'Antônimos expressam ideias opostas.'],
    ['Qual é o plural de "pão"?', ['pãos', 'pãoes', 'pans', 'pães'], 3, 'Assim como "cão" faz "cães" e "alemão" faz "alemães".'],
    ['Na frase "O menino correu", qual é o sujeito?', ['correu', 'O menino', 'O', 'menino correu'], 1, 'O sujeito é quem pratica a ação expressa pelo verbo.'],
    ['Qual destas palavras está acentuada corretamente?', ['café', 'cafe', 'cafê', 'cáfe'], 0, 'Oxítonas terminadas em "e" recebem acento agudo.'],
    ['Qual é a classe gramatical da palavra "rapidamente"?', ['substantivo', 'adjetivo', 'advérbio', 'pronome'], 2, 'Advérbios terminados em "-mente" costumam indicar modo.'],
    ['Qual é o diminutivo de "casa"?', ['casona', 'casinha', 'casebre', 'casarão'], 1, 'Casarão e casona são aumentativos.'],
    ['Qual destas palavras é um substantivo próprio?', ['cidade', 'rio', 'Brasil', 'país'], 2, 'Substantivos próprios nomeiam seres específicos e vão com inicial maiúscula.'],
    ['Qual frase está escrita corretamente?', ['Mais eu não vou', 'Mas eu não vô', 'Más eu não vou', 'Mas eu não vou'], 3, '"Mas" é conjunção adversativa; "mais" indica quantidade.'],
    ['Quantas sílabas tem a palavra "borboleta"?', ['4', '3', '5', '2'], 0, 'A separação é bor-bo-le-ta.'],
    ['Qual é o masculino correspondente a "mulher"?', ['homem', 'moço', 'senhor', 'rapaz'], 0, 'É um par de palavras de radicais diferentes, como "boi" e "vaca".'],
    ['Qual sinal de pontuação encerra uma pergunta?', ['ponto final', 'vírgula', 'ponto de interrogação', 'dois-pontos'], 2, 'O ponto de exclamação, por sua vez, marca surpresa ou emoção.'],
    ['Qual é o aumentativo de "livro"?', ['livrinho', 'livrão', 'livraria', 'livreto'], 1, 'Livreto e livrinho são diminutivos; livraria é o lugar onde se vendem livros.'],
    ['Qual frase está correta?', ['Eu fazi o bolo', 'Eu fez o bolo', 'Eu fizi o bolo', 'Eu fiz o bolo'], 3, 'O verbo fazer é irregular no pretérito perfeito: eu fiz, tu fizeste, ele fez.'],
  ],
  2: [
    ['Qual destas palavras é proparoxítona?', ['menino', 'médico', 'cafés', 'papel'], 1, 'Proparoxítonas têm a sílaba tônica na antepenúltima e são todas acentuadas.'],
    ['Qual é a função da vírgula em "João, venha aqui"?', ['separar sujeito do verbo', 'indicar pausa longa', 'marcar o aposto', 'isolar o vocativo'], 3, 'O vocativo é o termo usado para chamar ou interpelar alguém.'],
    ['Qual é o sujeito da frase "Choveu muito ontem"?', ['Oração sem sujeito', 'Muito', 'Ontem', 'Choveu'], 0, 'Verbos que indicam fenômenos da natureza são impessoais.'],
    ['Qual é o antônimo de "efêmero"?', ['passageiro', 'breve', 'duradouro', 'rápido'], 2, 'Efêmero é o que dura pouco tempo.'],
    ['O que é um substantivo coletivo?', ['Palavra que indica ação', 'Palavra que qualifica um ser', 'Palavra que substitui o nome', 'Palavra que designa um conjunto de seres'], 3, 'Exemplos: cardume, alcateia, biblioteca e constelação.'],
    ['Em "Ele é muito inteligente", qual é a classe da palavra "muito"?', ['adjetivo', 'advérbio', 'substantivo', 'preposição'], 1, 'Aqui "muito" é advérbio de intensidade, modificando o adjetivo.'],
    ['Qual é o plural de "capitão"?', ['capitãos', 'capitões', 'capitães', 'capitans'], 2, 'Segue o mesmo padrão de "cão" e "pão".'],
    ['Qual figura de linguagem aparece na expressão "morri de rir"?', ['hipérbole', 'metáfora', 'ironia', 'eufemismo'], 0, 'A hipérbole é o exagero intencional.'],
    ['Qual figura de linguagem compara sem usar conectivo, como em "meu amor é fogo"?', ['metáfora', 'comparação', 'metonímia', 'antítese'], 0, 'Na comparação apareceria um "como": "meu amor é como fogo".'],
    ['O que significa a expressão latina "ipsis litteris"?', ['de bom grado', 'por acaso', 'exatamente nas mesmas palavras', 'ao contrário'], 2, 'Usa-se quando algo é citado literalmente, letra por letra.'],
    ['Qual é a forma correta?', ['As duas formas estão corretas', 'Haviam muitas pessoas', 'Nenhuma está correta', 'Havia muitas pessoas'], 3, 'No sentido de existir, o verbo haver é impessoal e fica sempre no singular.'],
    ['Qual é o feminino de "cônsul"?', ['consula', 'consulesa', 'cônsula', 'consulisa'], 1, 'Assim como "duque" faz "duquesa".'],
    ['Qual destas palavras é escrita com "s", e não com "z"?', ['beleza', 'riqueza', 'análise', 'natureza'], 2, 'Substantivos formados a partir de adjetivos costumam usar "-eza".'],
    ['O que o prefixo "in-" indica na palavra "infeliz"?', ['negação', 'repetição', 'intensidade', 'direção'], 0, 'O mesmo prefixo aparece em "inútil" e "incapaz".'],
    ['Em "Ele agiu mal", qual é a classe da palavra "mal"?', ['substantivo', 'advérbio', 'adjetivo', 'conjunção'], 1, 'Como advérbio, "mal" é o oposto de "bem" e se escreve sem "u".'],
    ['Qual é o tempo verbal da forma "eu estudarei"?', ['presente', 'pretérito perfeito', 'pretérito imperfeito', 'futuro do presente'], 3, 'Indica uma ação que ainda vai acontecer.'],
    ['Qual é a função sintática de "um bolo" em "Comi um bolo"?', ['sujeito', 'predicativo do sujeito', 'adjunto adverbial', 'objeto direto'], 3, 'Complementa um verbo transitivo direto, sem preposição.'],
    ['Qual é a diferença entre "onde" e "aonde"?', ['Não há diferença', '"Aonde" indica movimento, e "onde", permanência', '"Onde" indica movimento', '"Aonde" está sempre errado'], 1, 'Diz-se "aonde você vai?" e "onde você está?".'],
    ['Qual destas palavras é oxítona?', ['urubu', 'mesa', 'lâmpada', 'cadeira'], 0, 'A sílaba tônica de "urubu" é a última, mas ela não recebe acento.'],
    ['Qual é o plural de "guarda-chuva"?', ['guardas-chuva', 'guardas-chuvas', 'guarda-chuvas', 'guarda-chuvases'], 2, 'Quando o primeiro elemento é verbo, só o segundo vai para o plural.'],
  ],
  3: [
    ['Qual é a função sintática de "do aluno" em "O livro do aluno sumiu"?', ['adjunto adnominal', 'complemento nominal', 'objeto indireto', 'agente da passiva'], 0, 'Ele restringe o sentido do substantivo "livro", indicando posse.'],
    ['O que caracteriza uma oração subordinada substantiva?', ['Qualifica um substantivo', 'Indica circunstância', 'Exerce a função de um substantivo na oração principal', 'É sintaticamente independente'], 2, 'Exemplo: "Quero que você venha" — a segunda oração faz o papel de objeto direto.'],
    ['Qual é o plural de "guarda-noturno"?', ['guarda-noturnos', 'guarda-noturno', 'guardas-noturno', 'guardas-noturnos'], 3, 'Aqui "guarda" é substantivo, então os dois elementos vão para o plural.'],
    ['Qual figura aparece em "A cidade inteira falava do caso"?', ['hipérbole', 'metonímia', 'prosopopeia', 'eufemismo'], 1, 'Usa-se o lugar no lugar das pessoas que o habitam.'],
    ['Qual figura de linguagem dá características humanas a seres inanimados?', ['metáfora', 'hipérbole', 'prosopopeia', 'sinestesia'], 2, 'Também chamada de personificação: "o vento sussurrava".'],
    ['Em "Precisa-se de vendedores", qual é a análise do "se"?', ['índice de indeterminação do sujeito', 'objeto direto', 'partícula apassivadora', 'conjunção integrante'], 0, 'O verbo é transitivo indireto, então o sujeito fica indeterminado.'],
    ['Qual é o valor da conjunção "porém"?', ['explicativo', 'adversativo', 'conclusivo', 'aditivo'], 1, 'Assim como "mas", "contudo" e "entretanto", ela marca oposição.'],
    ['Qual destas palavras é acentuada por ser proparoxítona?', ['até', 'você', 'avô', 'câmera'], 3, 'Todas as proparoxítonas da língua portuguesa são acentuadas, sem exceção.'],
    ['Qual é o sujeito de "Fizeram-se muitos comentários"?', ['Indeterminado', 'muitos comentários', 'Oração sem sujeito', 'se'], 1, 'É uma voz passiva sintética: muitos comentários foram feitos.'],
    ['Qual é a diferença entre "afim" e "a fim"?', ['"Afim" indica finalidade', 'São sinônimos', '"A fim" está sempre errado', '"Afim" significa semelhante; "a fim de" indica finalidade'], 3, 'Pessoas com gostos afins podem sair a fim de se divertir.'],
    ['Qual é a regência correta do verbo "assistir" no sentido de ver?', ['assistir o filme', 'assistir no filme', 'assistir ao filme', 'assistir do filme'], 2, 'Nesse sentido, o verbo é transitivo indireto e pede a preposição "a".'],
    ['Quando se usa a crase?', ['Na fusão da preposição "a" com o artigo feminino "a"', 'Antes de qualquer palavra feminina', 'Antes de verbos', 'Antes de pronomes pessoais'], 0, 'Por isso não há crase antes de palavras masculinas nem de verbos.'],
    ['Qual é o particípio irregular do verbo "pagar"?', ['pagado', 'pagando', 'pague', 'pago'], 3, 'Usa-se "tinha pagado" com ter e haver, e "foi pago" com ser e estar.'],
    ['Qual é a função do "se" em "Ele se feriu"?', ['índice de indeterminação', 'pronome reflexivo', 'partícula apassivadora', 'conjunção'], 1, 'A ação praticada pelo sujeito recai sobre ele mesmo.'],
    ['Qual é a diferença entre "mas" e "mais"?', ['"Mas" é conjunção adversativa; "mais" indica quantidade', 'São sinônimos', '"Mais" é conjunção', '"Mas" indica quantidade'], 0, 'Uma dica: "mas" pode ser trocado por "porém".'],
    ['Qual é o substantivo coletivo de cães?', ['rebanho', 'alcateia', 'matilha', 'ninhada'], 2, 'Alcateia é de lobos; rebanho, de ovelhas.'],
    ['O que significa "perspicaz"?', ['teimoso', 'preguiçoso', 'astuto e observador', 'generoso'], 2, 'Vem do latim e remete a quem enxerga além das aparências.'],
    ['Em "Comprei um carro novo", qual é a função de "novo"?', ['adjunto adnominal', 'predicativo do objeto', 'objeto direto', 'aposto'], 0, 'O adjetivo caracteriza diretamente o substantivo "carro".'],
    ['Qual é a forma correta do verbo "intervir" no pretérito perfeito?', ['interviu', 'intervinha', 'intervirá', 'interveio'], 3, 'O verbo intervir se conjuga como "vir": ele veio, ele interveio.'],
    ['Qual é o antônimo de "sucinto"?', ['breve', 'prolixo', 'curto', 'objetivo'], 1, 'Prolixo é quem se alonga demais ao falar ou escrever.'],
  ],
  4: [
    ['Qual figura de linguagem aparece em "silêncio ensurdecedor"?', ['metonímia', 'eufemismo', 'hipérbato', 'paradoxo'], 3, 'O paradoxo, ou oximoro, une ideias contraditórias na mesma expressão.'],
    ['Qual é a função sintática de "de ouro" em "anel de ouro"?', ['complemento nominal', 'adjunto adnominal', 'objeto indireto', 'adjunto adverbial'], 1, 'Ele especifica o substantivo, indicando matéria.'],
    ['Como se chama a inversão da ordem natural das palavras, comum na poesia?', ['elipse', 'zeugma', 'hipérbato', 'pleonasmo'], 2, 'O Hino Nacional começa com um hipérbato: "Ouviram do Ipiranga as margens plácidas".'],
    ['Qual figura de linguagem há em "ouvi uma cor quente"?', ['sinestesia', 'metáfora', 'catacrese', 'antítese'], 0, 'A sinestesia mistura sensações de sentidos diferentes.'],
    ['Como se chama o uso de uma palavra por falta de termo específico, como em "braço da cadeira"?', ['pleonasmo', 'catacrese', 'metonímia', 'silepse'], 1, 'Outros exemplos são "pé da mesa" e "dente de alho".'],
    ['Em "Os brasileiros somos apaixonados por futebol", qual figura ocorre?', ['zeugma', 'anacoluto', 'silepse de pessoa', 'elipse'], 2, 'A concordância se faz com a ideia, não com a forma gramatical.'],
    ['Qual é a diferença entre "senão" e "se não"?', ['"Senão" equivale a "caso contrário"; "se não" introduz condição negativa', 'São sempre intercambiáveis', '"Se não" é sempre erro', '"Senão" é sempre substantivo'], 0, 'Estude, senão será reprovado. Se não estudar, será reprovado.'],
    ['Como se classifica a oração destacada em "Quero que você venha"?', ['subordinada adverbial', 'coordenada assindética', 'subordinada adjetiva', 'subordinada substantiva objetiva direta'], 3, 'Ela completa o verbo "querer", funcionando como objeto direto.'],
    ['Qual é a regência correta do verbo "obedecer"?', ['obedecer o pai', 'obedecer no pai', 'obedecer ao pai', 'obedecer do pai'], 2, 'Obedecer e desobedecer são transitivos indiretos e pedem a preposição "a".'],
    ['Em qual situação NÃO se usa crase?', ['Antes de palavras masculinas', 'Antes de "aquela"', 'Na locução "à moda de"', 'Antes de horas determinadas'], 0, 'A exceção é quando está subentendida a expressão "à moda de".'],
    ['Qual é o plural de "vice-presidente"?', ['vices-presidentes', 'vice-presidentes', 'vice-presidente', 'vices-presidente'], 1, 'Prefixos como "vice", "ex" e "grã" ficam invariáveis.'],
    ['Qual é o feminino de "czar"?', ['czara', 'czari', 'czarisa', 'czarina'], 3, 'Assim como se diz "czarina Catarina, a Grande".'],
    ['Qual é a classe da palavra "que" em "Ele disse que viria"?', ['conjunção integrante', 'pronome relativo', 'advérbio', 'preposição'], 0, 'Pode ser substituída por "isso": ele disse isso.'],
    ['Como se chama a omissão de um termo facilmente subentendido?', ['pleonasmo', 'anáfora', 'polissíndeto', 'elipse'], 3, 'Em "Na sala, apenas quatro ou cinco convidados", omite-se o verbo "havia".'],
    ['Como se chama a repetição de conjunções, como em "e corre, e pula, e grita"?', ['assíndeto', 'polissíndeto', 'anáfora', 'aliteração'], 1, 'O assíndeto é o contrário: a ausência de conectivos.'],
    ['Como se classifica a oração destacada em "Não sei se ele virá"?', ['subordinada adjetiva', 'coordenada explicativa', 'subordinada substantiva objetiva direta', 'subordinada adverbial condicional'], 2, 'Aqui o "se" é conjunção integrante, e não condicional.'],
    ['Qual é a diferença entre "há" e "a" em expressões de tempo?', ['"Há" indica futuro', '"Há" indica tempo passado; "a", tempo futuro ou distância', 'São intercambiáveis', '"A" indica passado'], 1, 'Estudo há dois anos. Estarei lá daqui a dois anos.'],
    ['Qual é o aposto em "Machado de Assis, o autor de Dom Casmurro, nasceu no Rio"?', ['Machado de Assis', 'nasceu no Rio', 'Dom Casmurro', 'o autor de Dom Casmurro'], 3, 'O aposto explica ou especifica um termo anterior.'],
    ['Por que o verbo fica no singular em "Havia muitos problemas"?', ['Porque está na voz passiva', 'Porque o sujeito é indeterminado', 'Porque o verbo haver, no sentido de existir, é impessoal', 'Porque concorda com "muitos"'], 2, 'Se trocarmos por "existir", o verbo vai para o plural: existiam muitos problemas.'],
    ['Como se chama a concordância feita com a ideia, como em "São Paulo é movimentada"?', ['silepse de gênero', 'anacoluto', 'hipérbato', 'zeugma'], 0, 'A concordância se dá com "cidade", palavra subentendida.'],
  ],
  5: [
    ['Como se chama a quebra da construção sintática iniciada, como em "A vida, tudo nela é passageiro"?', ['elipse', 'zeugma', 'anacoluto', 'pleonasmo'], 2, 'O termo inicial fica solto, sem função sintática na oração seguinte.'],
    ['Qual é o modo verbal de "Se eu fosse rico"?', ['indicativo', 'imperativo', 'infinitivo', 'subjuntivo'], 3, 'O subjuntivo expressa hipótese, desejo ou possibilidade.'],
    ['Qual é a classe da palavra "porquê" em "Não sei o porquê disso"?', ['conjunção', 'substantivo', 'advérbio', 'pronome'], 1, 'Acompanhado de artigo, "porquê" é substantivo e significa "motivo".'],
    ['Qual é o processo de formação da palavra "guarda-roupa"?', ['composição por justaposição', 'composição por aglutinação', 'derivação prefixal', 'hibridismo'], 0, 'Na justaposição, as palavras se unem sem perder nenhuma letra.'],
    ['Qual é o processo de formação da palavra "planalto"?', ['composição por aglutinação', 'composição por justaposição', 'derivação sufixal', 'parassíntese'], 0, 'Na aglutinação há perda de elementos: plano + alto vira planalto.'],
    ['Qual é o processo de formação da palavra "entristecer"?', ['derivação prefixal', 'parassíntese', 'derivação regressiva', 'derivação imprópria'], 1, 'Na parassíntese, prefixo e sufixo se acrescentam ao mesmo tempo.'],
    ['Que processo explica a palavra "jantar" usada como substantivo, em "o jantar"?', ['parassíntese', 'derivação regressiva', 'composição', 'derivação imprópria'], 3, 'Na derivação imprópria, a palavra muda de classe sem mudar de forma.'],
    ['Qual é o plural de "sem-vergonha"?', ['sens-vergonhas', 'sem-vergonha', 'sem-vergonhas', 'sens-vergonha'], 2, 'A preposição permanece invariável no composto.'],
    ['Como se chama a variação linguística ligada à região do falante?', ['diacrônica', 'diatópica', 'diastrática', 'diafásica'], 1, 'É a que explica por que se diz "mandioca", "macaxeira" ou "aipim".'],
    ['Como se chama a variação linguística ligada ao grupo social do falante?', ['diatópica', 'diacrônica', 'diastrática', 'diamésica'], 2, 'A variação diacrônica, por sua vez, ocorre ao longo do tempo.'],
    ['Na palavra "casa", qual é o som da letra "s"?', ['som de z', 'som de ss', 'som de x', 'som de ch'], 0, 'Entre vogais, o "s" costuma ter som de "z".'],
    ['Quantos fonemas tem a palavra "chuva"?', ['6', '3', '5', '4'], 3, 'O dígrafo "ch" representa um único som, então são quatro fonemas para cinco letras.'],
    ['Qual é a classe da palavra "a" em "Ele começou a chorar"?', ['artigo', 'pronome', 'crase', 'preposição'], 3, 'Antes de verbo no infinitivo, é preposição — e nunca leva crase.'],
    ['Como se chama o encontro de vogais em sílabas separadas, como em "sa-í-da"?', ['hiato', 'ditongo', 'tritongo', 'dígrafo'], 0, 'No ditongo, as duas vogais ficam na mesma sílaba.'],
    ['Como se chama o par de letras que representa um só som, como "ch" e "lh"?', ['ditongo', 'hiato', 'dígrafo', 'tritongo'], 2, 'Outros dígrafos são "nh", "rr", "ss", "qu" e "gu".'],
    ['De qual língua o português se originou diretamente?', ['grego', 'latim vulgar', 'árabe', 'celta'], 1, 'O latim falado pelos soldados e colonos deu origem às línguas românicas.'],
    ['Qual acordo unificou regras de escrita entre os países de língua portuguesa?', ['Acordo Ortográfico da Língua Portuguesa', 'Convenção de Lisboa', 'Tratado de Coimbra', 'Reforma de 1943'], 0, 'Assinado em 1990, passou a vigorar no Brasil a partir de 2009.'],
    ['Quais letras foram oficialmente reincorporadas ao alfabeto pelo Acordo Ortográfico?', ['J, V e Z', 'K, W e Y', 'Q, X e H', 'B, C e D'], 1, 'Elas já eram usadas em nomes próprios e siglas antes da mudança.'],
    ['Como se chamam palavras de mesma grafia e sentidos diferentes, como "manga"?', ['sinônimos', 'antônimos', 'homônimos', 'parônimos'], 2, 'A manga da camisa e a manga que se come são homônimos perfeitos.'],
    ['Como se chamam palavras parecidas na escrita, mas de sentidos distintos, como "eminente" e "iminente"?', ['homônimos perfeitos', 'sinônimos', 'hipônimos', 'parônimos'], 3, 'Eminente é ilustre; iminente é o que está prestes a acontecer.'],
  ],
});
