import { montar } from './montar';

/** Literatura — 100 perguntas (20 por nível). */
export const perguntasLiteratura = montar('literatura', {
  1: [
    ['Quem escreveu "Dom Casmurro"?', ['José de Alencar', 'Jorge Amado', 'Machado de Assis', 'Monteiro Lobato'], 2, 'Publicado em 1899, o romance deixou em aberto se Capitu traiu ou não Bentinho.'],
    ['Quem criou o Sítio do Picapau Amarelo?', ['Monteiro Lobato', 'Machado de Assis', 'Érico Veríssimo', 'Vinícius de Moraes'], 0, 'Lobato é considerado o pai da literatura infantil brasileira.'],
    ['Qual é a personagem mais famosa de "Dom Casmurro"?', ['Iracema', 'Capitu', 'Lucíola', 'Gabriela'], 1, 'Seus "olhos de ressaca" estão entre as imagens mais citadas da literatura brasileira.'],
    ['Quem escreveu "O Pequeno Príncipe"?', ['Júlio Verne', 'Victor Hugo', 'Charles Perrault', 'Antoine de Saint-Exupéry'], 3, 'O autor era piloto e desapareceu em um voo durante a Segunda Guerra Mundial.'],
    ['Qual autor brasileiro escreveu "Vidas Secas"?', ['Graciliano Ramos', 'Jorge Amado', 'José Lins do Rego', 'Rachel de Queiroz'], 0, 'O romance de 1938 acompanha uma família de retirantes e a cachorra Baleia.'],
    ['Quem escreveu a peça "Romeu e Julieta"?', ['Molière', 'Dante Alighieri', 'Luís de Camões', 'William Shakespeare'], 3, 'A tragédia foi escrita por volta de 1595 e se passa em Verona, na Itália.'],
    ['Qual é o nome da boneca de pano criada por Monteiro Lobato?', ['Narizinho', 'Dona Benta', 'Emília', 'Cuca'], 2, 'Emília ganhou fala depois de tomar a pílula falante do Doutor Caramujo.'],
    ['Quem escreveu "Os Lusíadas"?', ['Fernando Pessoa', 'Luís de Camões', 'Eça de Queirós', 'José Saramago'], 1, 'A epopeia de 1572 narra as grandes navegações portuguesas.'],
    ['Quem escreveu "Capitães da Areia"?', ['Machado de Assis', 'Graciliano Ramos', 'Guimarães Rosa', 'Jorge Amado'], 3, 'O livro acompanha meninos de rua em Salvador e foi queimado em praça pública em 1937.'],
    ['Qual gênero literário é escrito em versos?', ['romance', 'poesia', 'crônica', 'ensaio'], 1, 'A poesia trabalha ritmo, sonoridade e imagens.'],
    ['Quem escreveu "Iracema" e "O Guarani"?', ['José de Alencar', 'Castro Alves', 'Gonçalves Dias', 'Álvares de Azevedo'], 0, 'Alencar é o principal romancista indianista do Romantismo brasileiro.'],
    ['Qual poema começa com "Minha terra tem palmeiras, onde canta o sabiá"?', ['Os Lusíadas', 'I-Juca-Pirama', 'Canção do Exílio', 'O Navio Negreiro'], 2, 'Dois versos do poema foram incorporados ao Hino Nacional Brasileiro.'],
    ['Quem escreveu a "Canção do Exílio"?', ['Castro Alves', 'Gonçalves Dias', 'Olavo Bilac', 'Casimiro de Abreu'], 1, 'Ele escreveu o poema em 1843, quando estudava em Coimbra, com saudades do Brasil.'],
    ['Qual autora escreveu a série "Harry Potter"?', ['Stephen King', 'J. R. R. Tolkien', 'J. K. Rowling', 'C. S. Lewis'], 2, 'O primeiro livro foi recusado por mais de dez editoras antes de ser publicado.'],
    ['Quem escreveu "Memórias Póstumas de Brás Cubas"?', ['José de Alencar', 'Aluísio Azevedo', 'Lima Barreto', 'Machado de Assis'], 3, 'O narrador do livro é um "defunto autor" que conta a própria vida depois de morto.'],
    ['O que é uma fábula?', ['História curta, geralmente com animais, que ensina uma lição', 'Poema longo e heroico', 'Relato histórico detalhado', 'Peça de teatro em três atos'], 0, 'Esopo e La Fontaine são os fabulistas mais conhecidos.'],
    ['Quem escreveu "A Moreninha"?', ['Joaquim Manuel de Macedo', 'José de Alencar', 'Machado de Assis', 'Manuel Antônio de Almeida'], 0, 'Publicado em 1844, é um dos primeiros romances de sucesso do Brasil.'],
    ['Qual personagem ficou famoso por lutar contra moinhos de vento?', ['Robinson Crusoé', 'Ulisses', 'Dom Quixote', 'Gulliver'], 2, 'Ele confundia os moinhos com gigantes por excesso de leitura de romances de cavalaria.'],
    ['Quem escreveu "Dom Quixote"?', ['Luís de Camões', 'Miguel de Cervantes', 'Dante Alighieri', 'Molière'], 1, 'A obra, de 1605, é considerada o primeiro romance moderno.'],
    ['Qual gênero narra histórias longas em prosa?', ['poema', 'soneto', 'crônica', 'romance'], 3, 'O romance permite desenvolver muitos personagens e tramas paralelas.'],
  ],
  2: [
    ['Qual movimento literário brasileiro começou com a Semana de Arte Moderna de 1922?', ['Romantismo', 'Modernismo', 'Parnasianismo', 'Realismo'], 1, 'Os modernistas romperam com a rigidez formal e valorizaram a fala brasileira.'],
    ['Quem escreveu "Grande Sertão: Veredas"?', ['Jorge Amado', 'Érico Veríssimo', 'Clarice Lispector', 'Guimarães Rosa'], 3, 'A obra de 1956 inventa palavras e recria a fala do sertão mineiro.'],
    ['Quem escreveu "A Hora da Estrela"?', ['Clarice Lispector', 'Rachel de Queiroz', 'Cecília Meireles', 'Lygia Fagundes Telles'], 0, 'O romance, sobre a nordestina Macabéa, foi publicado no ano da morte da autora, em 1977.'],
    ['Qual é o narrador e protagonista de "Grande Sertão: Veredas"?', ['Fabiano', 'Macunaíma', 'Riobaldo', 'Paulo Honório'], 2, 'O ex-jagunço narra sua história a um interlocutor que nunca fala.'],
    ['Quem escreveu "Macunaíma"?', ['Oswald de Andrade', 'Manuel Bandeira', 'Menotti del Picchia', 'Mário de Andrade'], 3, 'O "herói sem nenhum caráter" foi criado em 1928 como síntese do povo brasileiro.'],
    ['Qual poeta escreveu "No meio do caminho tinha uma pedra"?', ['Manuel Bandeira', 'Carlos Drummond de Andrade', 'Vinícius de Moraes', 'João Cabral de Melo Neto'], 1, 'O poema causou escândalo em 1928 pela repetição e pela linguagem coloquial.'],
    ['Quem escreveu "Morte e Vida Severina"?', ['Carlos Drummond de Andrade', 'Manuel Bandeira', 'João Cabral de Melo Neto', 'Ferreira Gullar'], 2, 'O auto de Natal pernambucano acompanha um retirante rumo ao litoral.'],
    ['Qual poeta brasileiro é conhecido como "o poeta dos escravos"?', ['Castro Alves', 'Gonçalves Dias', 'Cruz e Sousa', 'Casimiro de Abreu'], 0, 'Sua poesia abolicionista inclui o célebre "O Navio Negreiro".'],
    ['Quem escreveu "O Cortiço"?', ['Aluísio Azevedo', 'Machado de Assis', 'Raul Pompeia', 'Lima Barreto'], 0, 'O romance naturalista de 1890 trata a habitação coletiva quase como um organismo vivo.'],
    ['Qual é o protagonista do conto "O Alienista", de Machado de Assis?', ['Brás Cubas', 'Bentinho', 'Simão Bacamarte', 'Quincas Borba'], 2, 'O médico interna quase toda a cidade de Itaguaí em nome da ciência.'],
    ['Quem escreveu "Triste Fim de Policarpo Quaresma"?', ['Machado de Assis', 'Aluísio Azevedo', 'Euclides da Cunha', 'Lima Barreto'], 3, 'O romance ironiza o nacionalismo ingênuo na Primeira República.'],
    ['Quem escreveu "Os Sertões"?', ['Graciliano Ramos', 'Euclides da Cunha', 'Gilberto Freyre', 'Monteiro Lobato'], 1, 'O livro nasceu da cobertura jornalística da Guerra de Canudos.'],
    ['Qual autor de língua portuguesa ganhou o Nobel de Literatura em 1998?', ['Fernando Pessoa', 'Eça de Queirós', 'José Saramago', 'António Lobo Antunes'], 2, 'Saramago é o único escritor de língua portuguesa a receber o prêmio.'],
    ['Quem escreveu "Cem Anos de Solidão"?', ['Gabriel García Márquez', 'Mario Vargas Llosa', 'Jorge Luis Borges', 'Julio Cortázar'], 0, 'O romance de 1967 consagrou o realismo fantástico latino-americano.'],
    ['Qual poeta português criou heterônimos como Álvaro de Campos?', ['Luís de Camões', 'Fernando Pessoa', 'Florbela Espanca', 'Cesário Verde'], 1, 'Cada heterônimo tinha biografia, estilo e até signo astrológico próprios.'],
    ['Quem escreveu "O Senhor dos Anéis"?', ['C. S. Lewis', 'George R. R. Martin', 'Ursula K. Le Guin', 'J. R. R. Tolkien'], 3, 'Tolkien era professor de literatura medieval e criou idiomas completos para sua obra.'],
    ['Qual autor brasileiro escreveu "O Alquimista"?', ['Jorge Amado', 'Rubem Fonseca', 'Luis Fernando Verissimo', 'Paulo Coelho'], 3, 'É um dos livros mais traduzidos da história, com edições em mais de 80 idiomas.'],
    ['Qual poeta brasileiro escreveu a letra de "Garota de Ipanema"?', ['Chico Buarque', 'Vinícius de Moraes', 'Caetano Veloso', 'Tom Jobim'], 1, 'A melodia é de Tom Jobim; Vinícius era poeta e também diplomata.'],
    ['Quem escreveu "Memórias de um Sargento de Milícias"?', ['Manuel Antônio de Almeida', 'Joaquim Manuel de Macedo', 'José de Alencar', 'Bernardo Guimarães'], 0, 'O romance de 1852 retrata o Rio de Janeiro com humor e malandragem.'],
    ['Qual livro de Machado de Assis é narrado por um defunto?', ['Quincas Borba', 'Dom Casmurro', 'Memórias Póstumas de Brás Cubas', 'Esaú e Jacó'], 2, 'A dedicatória é "ao verme que primeiro roeu as frias carnes do meu cadáver".'],
  ],
  3: [
    ['Qual escola literária defendia a "arte pela arte" e a perfeição formal?', ['Parnasianismo', 'Romantismo', 'Modernismo', 'Barroco'], 0, 'Olavo Bilac é o nome mais conhecido do Parnasianismo brasileiro.'],
    ['Quem escreveu "Sagarana"?', ['Jorge Amado', 'Érico Veríssimo', 'Guimarães Rosa', 'Graciliano Ramos'], 2, 'O livro de contos de 1946 apresentou ao Brasil a linguagem inventiva do autor.'],
    ['Qual romance de Érico Veríssimo narra a saga da família Terra Cambará?', ['Clarissa', 'Olhai os Lírios do Campo', 'Incidente em Antares', 'O Tempo e o Vento'], 3, 'A trilogia cobre dois séculos de história do Rio Grande do Sul.'],
    ['Quem escreveu "São Bernardo"?', ['José Lins do Rego', 'Graciliano Ramos', 'Jorge Amado', 'Rachel de Queiroz'], 1, 'O narrador Paulo Honório é um fazendeiro seco e autoritário.'],
    ['Qual poeta escreveu "Vou-me embora pra Pasárgada"?', ['Carlos Drummond de Andrade', 'Mário de Andrade', 'Manuel Bandeira', 'Oswald de Andrade'], 2, 'Pasárgada era a cidade imaginária onde o poeta seria "amigo do rei".'],
    ['Qual movimento literário retratou a sociedade com crítica e objetividade no século XIX?', ['Realismo', 'Romantismo', 'Simbolismo', 'Arcadismo'], 0, 'O Realismo reagiu ao idealismo e ao sentimentalismo românticos.'],
    ['Quem escreveu "O Quinze"?', ['Cecília Meireles', 'Rachel de Queiroz', 'Clarice Lispector', 'Lygia Fagundes Telles'], 1, 'Publicado em 1930, o romance retrata a seca de 1915 no Ceará.'],
    ['Qual poeta simbolista brasileiro é conhecido como "Cisne Negro"?', ['Olavo Bilac', 'Alphonsus de Guimaraens', 'Augusto dos Anjos', 'Cruz e Sousa'], 3, 'Filho de pais escravizados, tornou-se o maior nome do Simbolismo no Brasil.'],
    ['Quem escreveu "Menino de Engenho"?', ['Graciliano Ramos', 'José Lins do Rego', 'Jorge Amado', 'Euclides da Cunha'], 1, 'Abre o chamado ciclo da cana-de-açúcar do autor paraibano.'],
    ['Qual obra inaugurou o Realismo no Brasil, em 1881?', ['O Cortiço', 'O Ateneu', 'O Mulato', 'Memórias Póstumas de Brás Cubas'], 3, 'O romance de Machado de Assis rompeu de vez com o estilo romântico.'],
    ['Quem escreveu "O Ateneu"?', ['Aluísio Azevedo', 'Lima Barreto', 'Raul Pompeia', 'Machado de Assis'], 2, 'O romance de 1888 retrata a crueldade da vida em um internato.'],
    ['Quem escreveu "A Metamorfose", sobre um homem que acorda transformado em inseto?', ['Franz Kafka', 'Albert Camus', 'Thomas Mann', 'James Joyce'], 0, 'A novela foi publicada em 1915 e deu origem ao adjetivo "kafkiano".'],
    ['Quem escreveu "Crime e Castigo"?', ['Liev Tolstói', 'Anton Tchékhov', 'Nikolai Gógol', 'Fiódor Dostoiévski'], 3, 'O romance acompanha a culpa do estudante Raskólnikov após um assassinato.'],
    ['Quem escreveu "Guerra e Paz"?', ['Fiódor Dostoiévski', 'Liev Tolstói', 'Ivan Turguêniev', 'Alexandre Púchkin'], 1, 'A obra tem mais de 500 personagens e se passa durante as invasões napoleônicas.'],
    ['Qual é a obra-prima de Dante Alighieri?', ['A Divina Comédia', 'Decamerão', 'Orlando Furioso', 'A Eneida'], 0, 'O poema descreve uma viagem pelo Inferno, Purgatório e Paraíso.'],
    ['Quem escreveu "1984"?', ['Aldous Huxley', 'Ray Bradbury', 'George Orwell', 'H. G. Wells'], 2, 'O romance de 1949 criou expressões como "Grande Irmão" e "novafala".'],
    ['Qual autora escreveu "Laços de Família"?', ['Rachel de Queiroz', 'Cecília Meireles', 'Clarice Lispector', 'Adélia Prado'], 2, 'A coletânea de contos de 1960 inclui "Amor" e "Feliz Aniversário".'],
    ['Quem escreveu "Casa-Grande & Senzala"?', ['Gilberto Freyre', 'Sérgio Buarque de Holanda', 'Caio Prado Júnior', 'Darcy Ribeiro'], 0, 'O ensaio de 1933 analisa a formação da sociedade brasileira.'],
    ['Quem escreveu "O Auto da Compadecida"?', ['Nelson Rodrigues', 'Jorge Andrade', 'Dias Gomes', 'Ariano Suassuna'], 3, 'A peça de 1955 mistura teatro popular nordestino e tradição medieval ibérica.'],
    ['Quem escreveu "Vestido de Noiva", marco do teatro moderno brasileiro?', ['Ariano Suassuna', 'Nelson Rodrigues', 'Plínio Marcos', 'Dias Gomes'], 1, 'A peça de 1943 se passa em três planos: realidade, memória e alucinação.'],
  ],
  4: [
    ['Qual heterônimo de Fernando Pessoa é o poeta bucólico, "guardador de rebanhos"?', ['Álvaro de Campos', 'Ricardo Reis', 'Bernardo Soares', 'Alberto Caeiro'], 3, 'Pessoa o chamava de "mestre" dos outros heterônimos.'],
    ['Qual heterônimo de Fernando Pessoa era médico e escrevia odes clássicas?', ['Alberto Caeiro', 'Ricardo Reis', 'Álvaro de Campos', 'Bernardo Soares'], 1, 'Seus versos remetem a Horácio e ao epicurismo antigo.'],
    ['Em qual romance de Machado de Assis aparece a filosofia do Humanitismo?', ['Dom Casmurro', 'Esaú e Jacó', 'Quincas Borba', 'Iaiá Garcia'], 2, 'A máxima "ao vencedor, as batatas" resume a doutrina inventada no livro.'],
    ['Qual poeta brasileiro escreveu "O Navio Negreiro"?', ['Castro Alves', 'Gonçalves Dias', 'Fagundes Varela', 'Álvares de Azevedo'], 0, 'O poema denuncia o horror dos navios de tráfico de pessoas escravizadas.'],
    ['Qual é o nome do companheiro de Riobaldo por quem ele se apaixona em "Grande Sertão: Veredas"?', ['Otacília', 'Diadorim', 'Nhorinhá', 'Ana Duarte'], 1, 'O segredo de Diadorim só é revelado nas últimas páginas do livro.'],
    ['Qual movimento literário português tem Camões como principal nome?', ['Romantismo', 'Barroco', 'Classicismo', 'Realismo'], 2, 'O Classicismo retomou modelos greco-latinos durante o Renascimento.'],
    ['Qual poeta árcade brasileiro escreveu "Marília de Dirceu"?', ['Tomás Antônio Gonzaga', 'Cláudio Manuel da Costa', 'Basílio da Gama', 'Santa Rita Durão'], 0, 'Ele participou da Inconfidência Mineira e foi degredado para a África.'],
    ['Qual poeta barroco baiano ficou conhecido como "Boca do Inferno"?', ['Bento Teixeira', 'Botelho de Oliveira', 'Padre Antônio Vieira', 'Gregório de Matos'], 3, 'Seus versos satíricos atacavam autoridades e costumes da Bahia colonial.'],
    ['Qual poema de Gonçalves Dias narra o drama de um guerreiro tupi prisioneiro?', ['Os Timbiras', 'Canção do Exílio', 'I-Juca-Pirama', 'Marabá'], 2, 'O título significa, em tupi, "aquele que deve morrer, que é digno de ser morto".'],
    ['Quem escreveu "Ulisses", marco do romance moderno?', ['James Joyce', 'Marcel Proust', 'Virginia Woolf', 'William Faulkner'], 0, 'O livro narra um único dia em Dublin, 16 de junho de 1904.'],
    ['Quem escreveu "Em Busca do Tempo Perdido"?', ['James Joyce', 'Marcel Proust', 'Gustave Flaubert', 'Stendhal'], 1, 'A obra tem sete volumes e começa com a célebre cena da madeleine.'],
    ['Quem escreveu "Madame Bovary"?', ['Honoré de Balzac', 'Émile Zola', 'Guy de Maupassant', 'Gustave Flaubert'], 3, 'O autor foi processado por ofensa à moral quando o livro saiu, em 1857.'],
    ['Qual escritor francês reuniu seus romances sob o título "A Comédia Humana"?', ['Honoré de Balzac', 'Victor Hugo', 'Émile Zola', 'Alexandre Dumas'], 0, 'São quase cem obras que retratam a sociedade francesa do século XIX.'],
    ['Qual romance de Jorge Amado se passa em Ilhéus e tem uma cozinheira como protagonista?', ['Tenda dos Milagres', 'Dona Flor e Seus Dois Maridos', 'Tieta do Agreste', 'Gabriela, Cravo e Canela'], 3, 'A personagem virou novela e sinônimo do imaginário sensual do cacau baiano.'],
    ['Qual modernista escreveu o "Manifesto Antropófago"?', ['Mário de Andrade', 'Oswald de Andrade', 'Manuel Bandeira', 'Raul Bopp'], 1, 'O texto de 1928 propunha "devorar" a cultura estrangeira para criar algo brasileiro.'],
    ['Qual poeta escreveu "A Rosa do Povo"?', ['Manuel Bandeira', 'João Cabral de Melo Neto', 'Carlos Drummond de Andrade', 'Murilo Mendes'], 2, 'Publicado em 1945, é o livro mais político do poeta itabirano.'],
    ['Qual poeta brasileiro escreveu o livro "Eu", marcado por imagens da morte e da ciência?', ['Cruz e Sousa', 'Augusto dos Anjos', 'Alphonsus de Guimaraens', 'Raul Pompeia'], 1, 'Foi o único livro que publicou em vida, em 1912.'],
    ['Qual romance de José de Alencar se passa no Ceará e tem uma indígena tabajara como protagonista?', ['O Guarani', 'Ubirajara', 'Lucíola', 'Iracema'], 3, 'A obra conta o encontro entre a indígena e o colonizador português Martim.'],
    ['De qual palavra "Iracema" é anagrama?', ['Cearense', 'Mar e terra', 'América', 'Amor e cera'], 2, 'A coincidência reforça a leitura do romance como mito de fundação do Brasil.'],
    ['Qual escritora brasileira escreveu "As Meninas"?', ['Lygia Fagundes Telles', 'Clarice Lispector', 'Hilda Hilst', 'Nélida Piñon'], 0, 'O romance de 1973 acompanha três jovens durante a ditadura militar.'],
  ],
  5: [
    ['Qual texto é considerado o marco inicial da literatura no Brasil?', ['Prosopopeia', 'O Uraguai', 'A Carta de Pero Vaz de Caminha', 'Diálogo das Grandezas do Brasil'], 2, 'Escrita em 1500, só foi publicada integralmente mais de 300 anos depois.'],
    ['Qual poema de Bento Teixeira inaugurou o Barroco no Brasil?', ['O Uraguai', 'Caramuru', 'Marília de Dirceu', 'Prosopopeia'], 3, 'Publicado em 1601, imita a estrutura de "Os Lusíadas".'],
    ['Quem escreveu o "Sermão da Sexagésima"?', ['Gregório de Matos', 'Padre Antônio Vieira', 'Padre José de Anchieta', 'Bento Teixeira'], 1, 'Vieira é considerado o maior orador sacro da língua portuguesa.'],
    ['Qual período literário brasileiro reúne Euclides da Cunha e Lima Barreto?', ['Pré-Modernismo', 'Simbolismo', 'Parnasianismo', 'Naturalismo'], 0, 'O Pré-Modernismo antecipou temas sociais que o Modernismo desenvolveria.'],
    ['Qual foi o romance de estreia de Clarice Lispector?', ['Perto do Coração Selvagem', 'A Paixão Segundo G.H.', 'Laços de Família', 'A Hora da Estrela'], 0, 'Publicado em 1943, quando a autora tinha 23 anos, surpreendeu a crítica.'],
    ['Qual foi o último romance publicado por Machado de Assis?', ['Quincas Borba', 'Memorial de Aires', 'Esaú e Jacó', 'Dom Casmurro'], 1, 'Saiu em 1908, ano da morte do escritor.'],
    ['Qual poeta fundou o movimento concretista ao lado de Décio Pignatari?', ['Ferreira Gullar', 'Manoel de Barros', 'Mário Quintana', 'Haroldo de Campos'], 3, 'O grupo Noigandres propunha a poesia como objeto visual.'],
    ['Qual escritor moçambicano é autor de "Terra Sonâmbula"?', ['José Craveirinha', 'Pepetela', 'Mia Couto', 'Luandino Vieira'], 2, 'O romance se passa durante a guerra civil de Moçambique.'],
    ['Qual escritor angolano recebeu o Prêmio Camões em 1997?', ['Mia Couto', 'Pepetela', 'José Eduardo Agualusa', 'José Craveirinha'], 1, 'Seu nome de batismo é Artur Carlos Maurício Pestana dos Santos.'],
    ['Qual autor ultrarromântico escreveu "Noite na Taverna"?', ['Casimiro de Abreu', 'Fagundes Varela', 'Álvares de Azevedo', 'Junqueira Freire'], 2, 'O livro reúne contos macabros narrados por jovens boêmios.'],
    ['Como é chamada a segunda geração romântica brasileira, marcada pelo pessimismo?', ['Mal do século', 'Condoreirismo', 'Indianismo', 'Geração de 45'], 0, 'Também chamada byroniana, por influência do poeta inglês Lord Byron.'],
    ['Qual geração romântica brasileira é chamada de condoreira?', ['A primeira', 'A segunda', 'A quarta', 'A terceira'], 3, 'O nome vem do condor, ave que voa alto — símbolo da poesia social e abolicionista.'],
    ['Quem escreveu "O Processo"?', ['Albert Camus', 'Thomas Mann', 'Hermann Hesse', 'Franz Kafka'], 3, 'O protagonista é preso sem nunca saber de que é acusado.'],
    ['Qual escritor colombiano criou a cidade fictícia de Macondo?', ['Gabriel García Márquez', 'Juan Rulfo', 'Isabel Allende', 'Alejo Carpentier'], 0, 'Macondo é o cenário de "Cem Anos de Solidão".'],
    ['Qual autor argentino escreveu "Ficções"?', ['Julio Cortázar', 'Ernesto Sábato', 'Jorge Luis Borges', 'Adolfo Bioy Casares'], 2, 'Seus contos exploram labirintos, espelhos e bibliotecas infinitas.'],
    ['Qual escritora inglesa escreveu "Orgulho e Preconceito"?', ['Emily Brontë', 'Jane Austen', 'Virginia Woolf', 'Mary Shelley'], 1, 'O romance foi publicado em 1813, inicialmente de forma anônima.'],
    ['Quem criou o personagem Frankenstein?', ['Mary Shelley', 'Bram Stoker', 'Emily Brontë', 'Ann Radcliffe'], 0, 'Ela tinha apenas 18 anos quando começou a escrever a obra, em 1816.'],
    ['Qual autor russo escreveu "Os Irmãos Karamázov"?', ['Liev Tolstói', 'Fiódor Dostoiévski', 'Nikolai Gógol', 'Ivan Turguêniev'], 1, 'Foi seu último romance, publicado poucos meses antes de sua morte.'],
    ['Qual é o mais importante prêmio literário da língua portuguesa?', ['Prêmio Jabuti', 'Prêmio Cervantes', 'Prêmio Camões', 'Prêmio Machado de Assis'], 2, 'Criado em 1988, é concedido por Brasil e Portugal em conjunto.'],
    ['Qual é o principal prêmio literário do Brasil?', ['Prêmio Camões', 'Prêmio Cervantes', 'Prêmio Oceanos', 'Prêmio Jabuti'], 3, 'O Jabuti é entregue desde 1959 pela Câmara Brasileira do Livro.'],
  ],
});
