import { montar } from './montar';

/** Matemática e Lógica — 100 perguntas (20 por nível). */
export const perguntasMatematicaLogica = montar('matematica-logica', {
  1: [
    ['Quanto é 7 × 8?', ['54', '52', '56', '58'], 2, 'A tabuada do 7 costuma ser a que mais assusta, mas 7 × 8 dá 56.'],
    ['Quantos lados tem um triângulo?', ['3', '4', '5', '6'], 0, 'O prefixo "tri" já indica os três lados e os três ângulos da figura.'],
    ['Quanto é 100 dividido por 4?', ['20', '25', '30', '50'], 1, 'Dividir por 4 é o mesmo que tirar a metade duas vezes.'],
    ['Qual é o resultado de 15 + 27?', ['32', '52', '45', '42'], 3, 'Somando as dezenas (10 + 20) e as unidades (5 + 7), chega-se a 42.'],
    ['Quantos minutos tem uma hora?', ['60', '100', '30', '24'], 0, 'A divisão do tempo em 60 partes vem dos babilônios, que usavam base 60.'],
    ['Qual figura tem quatro lados iguais e quatro ângulos retos?', ['Retângulo', 'Losango', 'Trapézio', 'Quadrado'], 3, 'Todo quadrado é um retângulo e também um losango.'],
    ['Quanto é a metade de 90?', ['30', '40', '45', '50'], 2, 'Um ângulo de 45 graus é exatamente metade de um ângulo reto.'],
    ['Quantos lados tem um hexágono?', ['5', '6', '7', '8'], 1, 'As abelhas constroem favos hexagonais porque essa forma economiza cera.'],
    ['Qual número vem imediatamente depois de 999?', ['990', '9990', '99', '1000'], 3, 'O 1000 é o primeiro número de quatro algarismos.'],
    ['Quanto é 9 × 9?', ['72', '81', '90', '99'], 1, 'Na tabuada do 9, a soma dos algarismos do resultado sempre dá 9.'],
    ['Quantos dias tem um ano bissexto?', ['366', '365', '364', '367'], 0, 'O dia extra, 29 de fevereiro, acerta o calendário a cada quatro anos.'],
    ['Qual é o dobro de 250?', ['400', '450', '500', '550'], 2, 'Dobrar é multiplicar por dois: 250 + 250 = 500.'],
    ['Quantos centímetros tem um metro?', ['10', '100', '1000', '50'], 1, 'O prefixo "centi" significa a centésima parte.'],
    ['Qual destes números é primo?', ['4', '6', '7', '9'], 2, 'O 7 só é divisível por 1 e por ele mesmo.'],
    ['Quanto é 3 elevado ao quadrado?', ['6', '12', '27', '9'], 3, 'Elevar ao quadrado é multiplicar o número por ele mesmo: 3 × 3 = 9.'],
    ['Quantas horas tem um dia?', ['24', '12', '36', '48'], 0, 'É o tempo aproximado de uma volta completa da Terra sobre seu eixo.'],
    ['Quanto é a metade de um real, em centavos?', ['50 centavos', '25 centavos', '10 centavos', '75 centavos'], 0, 'Um real equivale a 100 centavos.'],
    ['Qual é o resultado de 12 × 12?', ['124', '134', '144', '154'], 2, 'Uma dúzia de dúzias é chamada de grosa: 144 unidades.'],
    ['Quantos meses tem um semestre?', ['4', '6', '3', '12'], 1, '"Semestre" vem do latim e significa "seis meses".'],
    ['Qual destes números é o maior?', ['0,5', '0,05', '0,45', '0,55'], 3, 'Comparando casa a casa, 0,55 é maior que 0,5, que vale 0,50.'],
  ],
  2: [
    ['Quanto é 20% de 200?', ['20', '40', '60', '80'], 1, 'Calcular 20% é dividir por 5 — ou achar 10% e dobrar.'],
    ['Qual é a raiz quadrada de 144?', ['10', '11', '13', '12'], 3, 'Doze ao quadrado é 144, resultado conhecido como "uma grosa".'],
    ['Quanto vale a soma dos ângulos internos de um triângulo?', ['180°', '360°', '90°', '270°'], 0, 'Vale para qualquer triângulo na geometria plana.'],
    ['Qual é o valor aproximado do número π?', ['2,14', '3,41', '3,14', '4,13'], 2, 'Pi é a razão entre a circunferência e o diâmetro de qualquer círculo.'],
    ['Quanto é 5! (cinco fatorial)?', ['25', '60', '100', '120'], 3, 'Fatorial é o produto de todos os inteiros até o número: 5 × 4 × 3 × 2 × 1.'],
    ['Qual é a fórmula da área de um retângulo?', ['base + altura', 'base × altura', '(base × altura) / 2', '2 × (base + altura)'], 1, 'A última opção é a fórmula do perímetro, não da área.'],
    ['Quanto é 2 elevado a 10?', ['512', '1000', '1024', '2048'], 2, 'É por isso que um kilobyte equivale a 1.024 bytes.'],
    ['Quantos lados tem um decágono?', ['10', '12', '8', '9'], 0, 'O prefixo grego "deca" significa dez.'],
    ['Qual é o resultado de 7 × 6 − 12?', ['30', '32', '34', '42'], 0, 'A multiplicação vem antes da subtração: 42 − 12 = 30.'],
    ['Quanto vale a soma dos ângulos internos de um quadrilátero?', ['180°', '270°', '360°', '540°'], 2, 'Um quadrilátero pode ser dividido em dois triângulos de 180 graus cada.'],
    ['Qual algarismo romano representa o número 50?', ['X', 'C', 'D', 'L'], 3, 'X vale 10, L vale 50, C vale 100 e D vale 500.'],
    ['Qual é a média aritmética entre 10, 20 e 30?', ['15', '20', '25', '30'], 1, 'Soma-se tudo (60) e divide-se pela quantidade de números (3).'],
    ['Qual fração equivale a 0,25?', ['1/5', '1/3', '1/4', '2/5'], 2, 'Um quarto é o mesmo que 25 centésimos.'],
    ['Qual é o perímetro de um quadrado de lado 5?', ['20', '25', '10', '15'], 0, 'O perímetro é a soma dos quatro lados: 5 × 4 = 20.'],
    ['Um produto custa R$ 80 e tem 25% de desconto. Quanto você paga?', ['R$ 55', 'R$ 60', 'R$ 65', 'R$ 70'], 1, '25% de 80 são 20 reais de desconto.'],
    ['Qual é o próximo número da sequência 2, 4, 8, 16?', ['18', '20', '24', '32'], 3, 'Cada termo é o dobro do anterior — uma progressão geométrica de razão 2.'],
    ['Quantos minutos há em uma hora e 45 minutos?', ['85', '95', '100', '105'], 3, 'Sessenta minutos da hora mais os 45 restantes.'],
    ['Que número o algarismo romano MMXXIV representa?', ['2014', '2024', '2034', '1924'], 1, 'MM vale 2000, XX vale 20 e IV vale 4.'],
    ['Qual é a área de um triângulo de base 10 e altura 6?', ['30', '60', '16', '26'], 0, 'A área é base vezes altura dividido por dois.'],
    ['Qual é o mínimo múltiplo comum entre 4 e 6?', ['8', '10', '12', '24'], 2, 'O 12 é o menor número que aparece nas duas tabuadas.'],
  ],
  3: [
    ['Qual é o valor de x na equação 3x + 6 = 21?', ['5', '7', '9', '3'], 0, 'Subtraindo 6 dos dois lados e dividindo por 3, chega-se a x = 5.'],
    ['Em um triângulo retângulo de catetos 3 e 4, quanto mede a hipotenusa?', ['6', '7', '5', '12'], 2, 'É o famoso triângulo 3-4-5, caso clássico do teorema de Pitágoras.'],
    ['Qual teorema relaciona os lados de um triângulo retângulo?', ['Teorema de Tales', 'Teorema de Euler', 'Teorema de Fermat', 'Teorema de Pitágoras'], 3, 'O quadrado da hipotenusa é igual à soma dos quadrados dos catetos.'],
    ['Qual é a fórmula da área do círculo?', ['2πr', 'πr²', 'πd', 'πr³'], 1, 'A fórmula 2πr corresponde ao comprimento da circunferência.'],
    ['Quanto é 15% de 300?', ['30', '40', '45', '50'], 2, 'Dez por cento são 30; mais metade disso (15) resulta em 45.'],
    ['Qual é o resultado de (−5) × (−4)?', ['20', '−20', '9', '−9'], 0, 'O produto de dois números negativos é sempre positivo.'],
    ['Qual é o máximo divisor comum entre 12 e 18?', ['3', '6', '9', '12'], 1, 'Os divisores comuns são 1, 2, 3 e 6 — o maior deles é 6.'],
    ['Quantos números primos existem entre 1 e 10?', ['2', '3', '5', '4'], 3, 'São eles: 2, 3, 5 e 7. O número 1 não é considerado primo.'],
    ['Quanto vale a soma dos ângulos internos de um pentágono?', ['360°', '540°', '720°', '450°'], 1, 'A fórmula é (n − 2) × 180, com n igual ao número de lados.'],
    ['Qual é o volume de um cubo de aresta 3?', ['9', '12', '18', '27'], 3, 'O volume é a aresta elevada ao cubo: 3 × 3 × 3.'],
    ['Qual é o próximo número da sequência 1, 1, 2, 3, 5, 8?', ['11', '12', '13', '16'], 2, 'Na sequência de Fibonacci, cada termo é a soma dos dois anteriores.'],
    ['Qual é a raiz cúbica de 64?', ['4', '6', '8', '16'], 0, 'Quatro elevado ao cubo resulta em 64.'],
    ['Se 3 está para 6 assim como 5 está para x, quanto vale x?', ['8', '9', '12', '10'], 3, 'A razão é de 1 para 2, então x é o dobro de 5.'],
    ['Quantas diagonais tem um quadrado?', ['1', '2', '4', '6'], 1, 'As duas diagonais de um quadrado se cruzam no centro em ângulo reto.'],
    ['Qual é o resultado de 2³ × 2²?', ['32', '16', '64', '25'], 0, 'Na multiplicação de potências de mesma base, somam-se os expoentes.'],
    ['Qual é a probabilidade de sair cara ao lançar uma moeda honesta?', ['25%', '33%', '50%', '75%'], 2, 'São dois resultados possíveis e igualmente prováveis.'],
    ['Qual é a probabilidade de sair um número par em um dado comum?', ['1/6', '1/3', '1/2', '2/3'], 2, 'Três resultados pares (2, 4 e 6) entre seis possíveis.'],
    ['Qual é o número decimal equivalente à fração 3/8?', ['0,375', '0,325', '0,38', '0,83'], 0, 'Basta dividir 3 por 8.'],
    ['Um carro percorre 240 km em 3 horas. Qual é sua velocidade média?', ['60 km/h', '70 km/h', '75 km/h', '80 km/h'], 3, 'Velocidade média é distância dividida pelo tempo.'],
    ['Quanto é 1/2 + 1/3?', ['2/5', '5/6', '3/5', '1/6'], 1, 'Igualando os denominadores: 3/6 + 2/6 = 5/6.'],
  ],
  4: [
    ['Qual é o valor de log 1000 na base 10?', ['10', '100', '2', '3'], 3, 'O logaritmo pergunta a que expoente elevar a base: 10³ = 1000.'],
    ['Qual é a derivada da função x²?', ['x', '2x', 'x²/2', '2'], 1, 'Pela regra do tombo, o expoente desce multiplicando e diminui uma unidade.'],
    ['Quantos anagramas diferentes tem a palavra AMOR?', ['12', '16', '24', '36'], 2, 'São quatro letras distintas, então o total é 4! = 24.'],
    ['Qual é a soma de todos os números de 1 a 100?', ['5050', '5000', '4950', '10000'], 0, 'Gauss resolveu isso ainda criança somando pares que davam 101.'],
    ['Quais são as raízes da equação x² − 9 = 0?', ['Apenas 3', '3 e −3', 'Apenas −3', '9 e −9'], 1, 'Toda equação do segundo grau pode ter até duas raízes reais.'],
    ['Qual é a área de um círculo de raio 5, usando π igual a 3,14?', ['31,4', '62,8', '78,5', '157'], 2, 'A conta é 3,14 × 5², ou seja, 3,14 × 25.'],
    ['Quanto vale a soma dos ângulos internos de um octógono?', ['1080°', '900°', '1260°', '720°'], 0, 'Aplicando (n − 2) × 180 com n = 8, o resultado é 1080 graus.'],
    ['Qual é a razão da progressão geométrica 3, 12, 48, 192?', ['2', '3', '6', '4'], 3, 'Cada termo é quatro vezes o anterior.'],
    ['Quantos subconjuntos tem um conjunto de 4 elementos?', ['8', '12', '16', '24'], 2, 'São 2 elevado ao número de elementos: 2⁴ = 16.'],
    ['Qual é o valor do seno de 30 graus?', ['0,5', '0,75', '1', '0,866'], 0, 'O valor 0,866 corresponde ao seno de 60 graus.'],
    ['Qual é o valor do cosseno de 60 graus?', ['0,866', '0,5', '1', '0'], 1, 'Seno de 30 e cosseno de 60 têm o mesmo valor: são ângulos complementares.'],
    ['Quantos anagramas diferentes tem a palavra BANANA?', ['120', '720', '30', '60'], 3, 'São 6! divididos pelas repetições: três letras A e duas N.'],
    ['Qual é a probabilidade de tirar dois números 6 seguidos em um dado honesto?', ['1/36', '1/12', '1/6', '1/18'], 0, 'Multiplicam-se as probabilidades independentes: 1/6 × 1/6.'],
    ['Qual é a fórmula do volume de uma esfera?', ['4πr²', 'πr²h', '(πr³)/3', '(4/3)πr³'], 3, 'A fórmula 4πr² corresponde à área da superfície da esfera.'],
    ['Quanto vale 0! (zero fatorial)?', ['0', '1', 'É indefinido', 'Infinito'], 1, 'A definição de 1 mantém coerentes as fórmulas de combinatória.'],
    ['Qual é a soma dos termos da sequência 2, 5, 8, 11, 14?', ['30', '35', '40', '45'], 2, 'É uma progressão aritmética de razão 3, cuja soma vale 40.'],
    ['Quanto mede cada ângulo interno de um triângulo equilátero?', ['45°', '60°', '90°', '120°'], 1, 'Os três ângulos são iguais e somam 180 graus.'],
    ['Qual é o resultado de 5 elevado a zero?', ['0', '5', 'É indefinido', '1'], 3, 'Qualquer número diferente de zero elevado a zero resulta em 1.'],
    ['Quantas diagonais tem um hexágono?', ['6', '8', '9', '12'], 2, 'A fórmula n(n − 3)/2 dá 9 diagonais para seis lados.'],
    ['Se 3 pintores pintam uma casa em 8 dias, quantos dias levam 6 pintores?', ['4 dias', '6 dias', '12 dias', '16 dias'], 0, 'É uma regra de três inversa: dobrando os pintores, cai pela metade o tempo.'],
  ],
  5: [
    ['Qual número irracional vale aproximadamente 2,718?', ['Pi', 'Raiz de 2', 'Número de Euler', 'Número de ouro'], 2, 'O número e é a base dos logaritmos naturais.'],
    ['Qual é o valor aproximado do número de ouro?', ['1,414', '2,718', '3,141', '1,618'], 3, 'A proporção áurea aparece em obras de arte, na arquitetura e na natureza.'],
    ['Qual matemático grego escreveu "Os Elementos"?', ['Pitágoras', 'Euclides', 'Arquimedes', 'Tales de Mileto'], 1, 'A obra organizou a geometria em axiomas e foi usada como livro-texto por 2 mil anos.'],
    ['Qual teorema afirma não haver soluções inteiras para xⁿ + yⁿ = zⁿ quando n é maior que 2?', ['Último Teorema de Fermat', 'Teorema de Pitágoras', 'Conjectura de Goldbach', 'Hipótese de Riemann'], 0, 'Fermat anotou em 1637 que tinha uma prova que não cabia na margem do livro.'],
    ['Quem demonstrou o Último Teorema de Fermat, em 1994?', ['Andrew Wiles', 'Grigori Perelman', 'Terence Tao', 'Paul Erdős'], 0, 'A demonstração levou sete anos de trabalho quase secreto.'],
    ['Qual é a integral de 1/x?', ['x²/2', 'ln|x|', '1/x²', '−1/x'], 1, 'É o logaritmo natural do módulo de x, somado a uma constante.'],
    ['Para que valor tende (1 + 1/n)ⁿ quando n cresce indefinidamente?', ['1', '0', 'Infinito', 'O número e'], 3, 'Esse limite aparece no cálculo de juros compostos contínuos.'],
    ['Qual matemático brasileiro ganhou a Medalha Fields, em 2014?', ['Fernando Codá Marques', 'Jacob Palis', 'Artur Avila', 'Marcelo Viana'], 2, 'Avila foi o primeiro latino-americano a receber a honraria.'],
    ['Qual conjectura afirma que todo número par maior que 2 é soma de dois primos?', ['Conjectura de Collatz', 'Conjectura de Goldbach', 'Hipótese de Riemann', 'Conjectura de Poincaré'], 1, 'Proposta em 1742, segue sem demonstração até hoje.'],
    ['Quantos poliedros regulares, ou sólidos de Platão, existem?', ['3', '4', '5', '6'], 2, 'Tetraedro, cubo, octaedro, dodecaedro e icosaedro.'],
    ['Qual relação de Euler vale para todo poliedro convexo?', ['V − A + F = 2', 'V + A + F = 2', 'V × F = A', 'A = V + F'], 0, 'Vértices menos arestas mais faces resulta sempre em 2.'],
    ['Qual matemático e filósofo criou o plano cartesiano?', ['Isaac Newton', 'Gottfried Leibniz', 'Blaise Pascal', 'René Descartes'], 3, 'O nome "cartesiano" vem da forma latina de seu sobrenome, Cartesius.'],
    ['Qual é aproximadamente a chance de acertar a Mega-Sena com um jogo de seis dezenas?', ['1 em 1 milhão', '1 em 10 milhões', '1 em 25 milhões', '1 em 50 milhões'], 3, 'A probabilidade exata é de 1 em 50.063.860.'],
    ['Qual problema clássico deu origem à teoria dos grafos?', ['As pontes de Königsberg', 'O caixeiro-viajante', 'O paradoxo de Zenão', 'A torre de Hanói'], 0, 'Euler provou em 1736 que não havia caminho percorrendo as sete pontes uma só vez.'],
    ['Em qual problema famoso trocar de porta aumenta a chance de ganhar o prêmio?', ['Paradoxo de Russell', 'Paradoxo de Zenão', 'Problema de Monty Hall', 'Paradoxo do aniversário'], 2, 'Trocar eleva a probabilidade de acerto de 1/3 para 2/3.'],
    ['Em um grupo de 23 pessoas, qual é aproximadamente a chance de duas fazerem aniversário no mesmo dia?', ['10%', '50%', '25%', '90%'], 1, 'O resultado é tão contraintuitivo que ficou conhecido como paradoxo do aniversário.'],
    ['Como são chamados os números iguais à soma de seus divisores próprios, como 6 e 28?', ['Números perfeitos', 'Números primos', 'Números amigos', 'Números triangulares'], 0, 'No caso do 6: 1 + 2 + 3 resulta no próprio 6.'],
    ['Comparando os conjuntos dos números naturais e dos reais, o que se pode afirmar?', ['Têm o mesmo tamanho', 'O dos reais é maior e não enumerável', 'O dos naturais é maior', 'Ambos são finitos'], 1, 'Georg Cantor provou isso com o argumento da diagonal, no fim do século XIX.'],
    ['Qual matemático provou que todo sistema formal consistente tem afirmações indemonstráveis?', ['Georg Cantor', 'David Hilbert', 'Kurt Gödel', 'Alan Turing'], 2, 'Os teoremas da incompletude, de 1931, abalaram os fundamentos da matemática.'],
    ['Em qual sequência cada termo é a soma dos dois anteriores?', ['Sequência de Collatz', 'Progressão geométrica', 'Triângulo de Pascal', 'Sequência de Fibonacci'], 3, 'Ela aparece na disposição de sementes, conchas e pétalas na natureza.'],
  ],
});
