import { montar } from './montar';

/** Música — 100 perguntas (20 por nível). */
export const perguntasMusica = montar('musica', {
  1: [
    ['Qual cantor brasileiro é conhecido como "o Rei"?', ['Caetano Veloso', 'Chico Buarque', 'Roberto Carlos', 'Erasmo Carlos'], 2, 'Roberto Carlos ganhou o apelido ainda nos tempos da Jovem Guarda, nos anos 1960.'],
    ['Qual instrumento tem teclas brancas e pretas?', ['piano', 'violão', 'bateria', 'flauta'], 0, 'Um piano tradicional tem 88 teclas, sendo 52 brancas e 36 pretas.'],
    ['Qual ritmo é o mais associado ao carnaval do Rio de Janeiro?', ['forró', 'samba', 'sertanejo', 'frevo'], 1, 'O samba-enredo é cantado pelas escolas durante o desfile na Sapucaí.'],
    ['Qual banda britânica teve John Lennon e Paul McCartney?', ['Rolling Stones', 'Queen', 'Pink Floyd', 'The Beatles'], 3, 'A banda de Liverpool se separou em 1970, após menos de dez anos de carreira.'],
    ['Qual instrumento de quatro cordas é típico do samba?', ['cavaquinho', 'violino', 'viola caipira', 'contrabaixo'], 0, 'Ele também é essencial nos conjuntos de choro.'],
    ['Qual cantor é conhecido como o "Rei do Pop"?', ['Elvis Presley', 'Prince', 'James Brown', 'Michael Jackson'], 3, 'Seu álbum "Thriller" é o mais vendido da história da música.'],
    ['Qual ritmo é típico das festas juninas do Nordeste?', ['samba', 'axé', 'forró', 'maracatu'], 2, 'O trio de sanfona, zabumba e triângulo é a formação clássica do forró.'],
    ['Quantas cordas tem um violão comum?', ['4', '6', '8', '12'], 1, 'Existem violões de sete cordas, muito usados no samba e no choro.'],
    ['Qual artista brasileira ficou famosa no mundo com frutas na cabeça?', ['Elis Regina', 'Gal Costa', 'Rita Lee', 'Carmen Miranda'], 3, 'Ela nasceu em Portugal, foi criada no Brasil e virou estrela de Hollywood nos anos 1940.'],
    ['Qual destes instrumentos é tocado com um arco?', ['flauta', 'violino', 'piano', 'bateria'], 1, 'O arco tradicional é feito com crinas de cavalo.'],
    ['Qual gênero brasileiro é marcado por duplas e temas do campo?', ['sertanejo', 'rock', 'jazz', 'bossa nova'], 0, 'A música caipira deu origem ao sertanejo, hoje o gênero mais tocado no país.'],
    ['Quem compôs "Asa Branca"?', ['Dominguinhos', 'Jackson do Pandeiro', 'Luiz Gonzaga', 'Alceu Valença'], 2, 'A canção de 1947, feita com Humberto Teixeira, virou hino da seca nordestina.'],
    ['Como se chama o grande conjunto que toca música clássica?', ['banda', 'orquestra', 'coral', 'trio'], 1, 'Uma orquestra sinfônica pode reunir mais de cem músicos.'],
    ['Qual instrumento de percussão marca o som grave do samba?', ['pandeiro', 'tamborim', 'surdo', 'reco-reco'], 2, 'O surdo é o instrumento que dá a pulsação da bateria da escola de samba.'],
    ['Qual cantora é conhecida como a "Rainha do Pop"?', ['Beyoncé', 'Lady Gaga', 'Whitney Houston', 'Madonna'], 3, 'Ela é a artista feminina com maior número de discos vendidos na história.'],
    ['Como se chama quem escreve a letra de uma canção?', ['letrista', 'maestro', 'intérprete', 'produtor'], 0, 'Quando a pessoa faz letra e melodia, é chamada de compositor.'],
    ['Quantas notas musicais formam a escala básica?', ['7', '5', '8', '12'], 0, 'Dó, ré, mi, fá, sol, lá e si.'],
    ['Qual gênero nasceu no Brasil misturando samba e influências do jazz?', ['choro', 'frevo', 'bossa nova', 'maracatu'], 2, 'Surgiu no fim dos anos 1950, na zona sul do Rio de Janeiro.'],
    ['Quem é conhecido como o "Rei do Baião"?', ['Dominguinhos', 'Luiz Gonzaga', 'Gonzaguinha', 'Sivuca'], 1, 'Gonzagão levou a sanfona e o chapéu de cangaceiro aos palcos de todo o país.'],
    ['Qual destes é um instrumento de sopro?', ['violão', 'bateria', 'piano', 'saxofone'], 3, 'O saxofone foi inventado pelo belga Adolphe Sax por volta de 1840.'],
  ],
  2: [
    ['Quem compôs a melodia de "Garota de Ipanema"?', ['Vinícius de Moraes', 'Tom Jobim', 'João Gilberto', 'Baden Powell'], 1, 'É uma das canções mais gravadas da história, com centenas de versões.'],
    ['Qual cantor americano é chamado de "Rei do Rock"?', ['Chuck Berry', 'Little Richard', 'Buddy Holly', 'Elvis Presley'], 3, 'Elvis estourou em 1956 com "Heartbreak Hotel".'],
    ['Qual movimento musical brasileiro surgiu no fim dos anos 1960 com Caetano Veloso e Gilberto Gil?', ['Tropicália', 'Jovem Guarda', 'Bossa Nova', 'Clube da Esquina'], 0, 'O movimento misturava guitarra elétrica, cultura pop e tradição brasileira.'],
    ['Qual cantora brasileira era chamada de "Pimentinha"?', ['Gal Costa', 'Maria Bethânia', 'Elis Regina', 'Nara Leão'], 2, 'O apelido veio de seu temperamento forte e de sua intensidade no palco.'],
    ['Qual banda brasileira gravou "Faroeste Caboclo"?', ['Titãs', 'Os Paralamas do Sucesso', 'Barão Vermelho', 'Legião Urbana'], 3, 'A música tem quase nove minutos e 159 versos, sem refrão.'],
    ['Quem foi o vocalista da Legião Urbana?', ['Cazuza', 'Renato Russo', 'Herbert Vianna', 'Arnaldo Antunes'], 1, 'Renato Russo também traduzia e cantava em inglês no início da carreira.'],
    ['Qual banda britânica lançou "The Dark Side of the Moon"?', ['Led Zeppelin', 'The Who', 'Pink Floyd', 'Queen'], 2, 'O disco de 1973 ficou mais de 900 semanas na parada americana.'],
    ['Quem foi o vocalista do Queen?', ['Freddie Mercury', 'Brian May', 'Roger Taylor', 'John Deacon'], 0, 'Seu nome de nascimento era Farrokh Bulsara, nascido em Zanzibar.'],
    ['Qual instrumento de sopro é tradicional nos conjuntos de choro?', ['flauta', 'trompete', 'trombone', 'clarinete baixo'], 0, 'O trio clássico do choro reúne flauta, cavaquinho e violão.'],
    ['Quem compôs "Construção"?', ['Caetano Veloso', 'Gilberto Gil', 'Chico Buarque', 'Milton Nascimento'], 2, 'Todos os versos da canção terminam em palavras proparoxítonas.'],
    ['Qual artista baiano é autor de "Alegria, Alegria"?', ['Gilberto Gil', 'Tom Zé', 'Jorge Ben Jor', 'Caetano Veloso'], 3, 'A canção foi apresentada em um festival de 1967 e virou marco da Tropicália.'],
    ['Qual movimento musical mineiro reuniu Milton Nascimento e Lô Borges?', ['Tropicália', 'Clube da Esquina', 'Vanguarda Paulista', 'Jovem Guarda'], 1, 'O disco homônimo, de 1972, é considerado um dos melhores da música brasileira.'],
    ['Qual cantora brasileira é chamada de "rainha do rock nacional"?', ['Cássia Eller', 'Marina Lima', 'Rita Lee', 'Pitty'], 2, 'Rita Lee começou nos Mutantes antes da carreira solo.'],
    ['Qual banda dos anos 1980 teve Cazuza como vocalista?', ['Barão Vermelho', 'Titãs', 'Ultraje a Rigor', 'Engenheiros do Hawaii'], 0, 'Ele deixou o grupo em 1985 para seguir carreira solo.'],
    ['Qual dupla sertaneja gravou o sucesso "Evidências"?', ['Zezé Di Camargo & Luciano', 'Chitãozinho & Xororó', 'Leandro & Leonardo', 'Bruno & Marrone'], 1, 'A canção, de 1990, é obrigatória em qualquer karaokê brasileiro.'],
    ['Qual gênero musical nasceu em Nova Orleans no início do século XX?', ['blues', 'soul', 'funk', 'jazz'], 3, 'O jazz misturou tradições africanas, marchas militares e harmonias europeias.'],
    ['Para qual instrumento Beethoven compôs "Para Elisa"?', ['violino', 'violoncelo', 'órgão', 'piano'], 3, 'A peça só foi publicada 40 anos depois da morte do compositor.'],
    ['Quem compôs a Nona Sinfonia, que inclui a "Ode à Alegria"?', ['Mozart', 'Beethoven', 'Bach', 'Brahms'], 1, 'Ele já estava completamente surdo quando a obra estreou, em 1824.'],
    ['Qual músico jamaicano popularizou o reggae no mundo?', ['Bob Marley', 'Jimmy Cliff', 'Peter Tosh', 'Burning Spear'], 0, 'Seu disco "Legend" é um dos mais vendidos de todos os tempos.'],
    ['Qual ritmo pernambucano é dançado com pequenas sombrinhas coloridas?', ['maracatu', 'ciranda', 'frevo', 'coco'], 2, 'O frevo foi reconhecido pela Unesco como patrimônio imaterial da humanidade.'],
  ],
  3: [
    ['Com qual cantora Tom Jobim gravou um disco clássico em 1974?', ['Elis Regina', 'Gal Costa', 'Nara Leão', 'Maysa'], 0, 'O álbum "Elis & Tom" traz a versão definitiva de "Águas de Março".'],
    ['Qual álbum dos Beatles traz "Lucy in the Sky with Diamonds"?', ['Abbey Road', 'Revolver', 'Sgt. Pepper’s Lonely Hearts Club Band', 'Let It Be'], 2, 'O disco de 1967 é apontado como o primeiro álbum conceitual do rock.'],
    ['Quem compôs "Aquarela do Brasil"?', ['Dorival Caymmi', 'Noel Rosa', 'Pixinguinha', 'Ary Barroso'], 3, 'A canção de 1939 ficou conhecida no exterior simplesmente como "Brazil".'],
    ['Quem é considerado o maior nome do choro brasileiro?', ['Jacob do Bandolim', 'Pixinguinha', 'Waldir Azevedo', 'Ernesto Nazareth'], 1, 'Flautista e compositor, ele é autor de "Carinhoso" e "Lamentos".'],
    ['Qual sambista carioca compôs "Feitiço da Vila" e morreu aos 26 anos?', ['Cartola', 'Ismael Silva', 'Noel Rosa', 'Wilson Batista'], 2, 'Noel Rosa é chamado de "poeta da Vila", em referência a Vila Isabel.'],
    ['Qual compositor da Mangueira é autor de "As Rosas Não Falam"?', ['Cartola', 'Nelson Cavaquinho', 'Zé Keti', 'Paulinho da Viola'], 0, 'Cartola só gravou seu primeiro disco solo aos 65 anos.'],
    ['Quem compôs "Trem das Onze"?', ['Paulinho da Viola', 'Adoniran Barbosa', 'Noel Rosa', 'Cartola'], 1, 'O samba paulistano foi eternizado na voz dos Demônios da Garoa.'],
    ['Qual compositor brasileiro escreveu as "Bachianas Brasileiras"?', ['Carlos Gomes', 'Ernesto Nazareth', 'Chiquinha Gonzaga', 'Heitor Villa-Lobos'], 3, 'A obra funde o estilo de Bach com melodias populares brasileiras.'],
    ['Quem compôs a ópera "O Guarani"?', ['Heitor Villa-Lobos', 'Carlos Gomes', 'Francisco Mignone', 'Alberto Nepomuceno'], 1, 'A abertura da ópera abria o programa "A Voz do Brasil" no rádio.'],
    ['Quem compôs a marchinha "Ó Abre Alas" e foi a primeira maestrina do Brasil?', ['Clementina de Jesus', 'Dolores Duran', 'Maysa', 'Chiquinha Gonzaga'], 3, 'Ela também lutou pela abolição da escravidão e pela República.'],
    ['Qual banda brasileira gravou "Pais e Filhos"?', ['Titãs', 'Os Paralamas do Sucesso', 'Legião Urbana', 'Capital Inicial'], 2, 'A canção está no álbum "As Quatro Estações", de 1989.'],
    ['Qual banda brasileira lançou "Sonífera Ilha"?', ['Titãs', 'Legião Urbana', 'Barão Vermelho', 'Kid Abelha'], 0, 'A música está no primeiro disco do grupo, de 1984.'],
    ['Qual é o álbum mais vendido da história da música?', ['Bad', 'Off the Wall', 'Dangerous', 'Thriller'], 3, 'O disco de Michael Jackson, de 1982, passou de 60 milhões de cópias.'],
    ['Qual banda gravou "Stairway to Heaven"?', ['Deep Purple', 'Led Zeppelin', 'Black Sabbath', 'The Doors'], 1, 'A música de oito minutos nunca foi lançada como single no Reino Unido.'],
    ['Qual compositor austríaco escreveu a ópera "A Flauta Mágica"?', ['Mozart', 'Beethoven', 'Haydn', 'Schubert'], 0, 'Foi uma das últimas obras de Mozart, estreada no ano de sua morte, 1791.'],
    ['Qual compositor barroco alemão escreveu as "Variações Goldberg"?', ['Georg Friedrich Handel', 'Antonio Vivaldi', 'Johann Sebastian Bach', 'Georg Philipp Telemann'], 2, 'A obra teria sido encomendada para ajudar um conde a dormir.'],
    ['Quem compôs "As Quatro Estações"?', ['Bach', 'Mozart', 'Vivaldi', 'Handel'], 2, 'São quatro concertos para violino, cada um representando uma estação do ano.'],
    ['Qual cantora americana é chamada de "Rainha do Soul"?', ['Aretha Franklin', 'Tina Turner', 'Diana Ross', 'Etta James'], 0, 'Sua versão de "Respect", de 1967, virou hino de direitos civis.'],
    ['Qual gênero musical surgiu no Bronx nos anos 1970, com DJs e MCs?', ['funk', 'disco', 'reggae', 'hip-hop'], 3, 'Os quatro elementos originais são o rap, o DJ, o break e o grafite.'],
    ['Quem compôs "Cálice" junto com Chico Buarque?', ['Caetano Veloso', 'Gilberto Gil', 'Milton Nascimento', 'Toquinho'], 1, 'A canção foi censurada em 1973 pelo trocadilho com "cale-se".'],
  ],
  4: [
    ['Qual álbum de João Gilberto, de 1959, é considerado o marco inicial da bossa nova?', ['Getz/Gilberto', 'Canção do Amor Demais', 'O Amor, o Sorriso e a Flor', 'Chega de Saudade'], 3, 'A batida de violão do disco mudou a forma de tocar samba.'],
    ['Qual disco levou a bossa nova ao Grammy, em parceria com o saxofonista Stan Getz?', ['Jazz Samba', 'Getz/Gilberto', 'Bossa Nova USA', 'Big Band Bossa Nova'], 1, 'O álbum de 1964 venceu o Grammy de disco do ano.'],
    ['Quem compôs "Chega de Saudade" com Vinícius de Moraes?', ['Baden Powell', 'Carlos Lyra', 'Tom Jobim', 'Roberto Menescal'], 2, 'A parceria entre os dois rendeu dezenas de clássicos.'],
    ['Quais são as cores da escola de samba Estação Primeira de Mangueira?', ['Verde e rosa', 'Azul e branco', 'Vermelho e branco', 'Azul e amarelo'], 0, 'A Mangueira foi fundada em 1928 e é uma das mais tradicionais do Rio.'],
    ['Qual escola de samba carioca tem a águia como símbolo?', ['Mangueira', 'Portela', 'Império Serrano', 'Unidos de Vila Isabel'], 1, 'A Portela é a escola com mais títulos no carnaval carioca.'],
    ['Qual sanfoneiro pernambucano compôs "Eu Só Quero um Xodó"?', ['Sivuca', 'Oswaldinho do Acordeon', 'Dominguinhos', 'Waldonys'], 2, 'Ele começou a carreira acompanhando Luiz Gonzaga ainda adolescente.'],
    ['Qual cantora gravou com Tom Jobim a versão mais célebre de "Águas de Março"?', ['Elis Regina', 'Gal Costa', 'Maria Bethânia', 'Nara Leão'], 0, 'A gravação de 1974 é famosa pelos sorrisos trocados durante a tomada.'],
    ['Qual banda brasileira lançou o álbum "Selvagem"?', ['Legião Urbana', 'Titãs', 'Capital Inicial', 'Os Paralamas do Sucesso'], 3, 'O disco de 1986 traz "Alagados" e "Melô do Marinheiro".'],
    ['Em que ano aconteceu a primeira edição do Rock in Rio?', ['1980', '1983', '1985', '1991'], 2, 'O festival reuniu cerca de 1,4 milhão de pessoas na Barra da Tijuca.'],
    ['Qual gênero musical baiano se popularizou nos anos 1980 com os trios elétricos?', ['axé', 'samba-reggae', 'pagode', 'arrocha'], 0, 'O nome vem de uma saudação iorubá usada nos terreiros de candomblé.'],
    ['Qual grupo percussivo do Pelourinho ficou famoso com "Faraó Divindade do Egito"?', ['Timbalada', 'Olodum', 'Ilê Aiyê', 'Araketu'], 1, 'O Olodum chegou a gravar com Paul Simon e Michael Jackson.'],
    ['Quem canta e compôs "Chão de Giz"?', ['Belchior', 'Raul Seixas', 'Fagner', 'Zé Ramalho'], 3, 'O paraibano também é autor de "Avôhai" e "Admirável Gado Novo".'],
    ['Quem foi o principal parceiro de Raul Seixas em letras como "Gita"?', ['Paulo Coelho', 'Marcelo Nova', 'Rita Lee', 'Cláudio Roberto'], 0, 'Antes de virar escritor de sucesso, Paulo Coelho era letrista de rock.'],
    ['Quem compôs "Flor de Lis" e "Oceano"?', ['Lulu Santos', 'Ivan Lins', 'Gilberto Gil', 'Djavan'], 3, 'O alagoano estreou em 1976 e é conhecido pelas harmonias sofisticadas.'],
    ['Quem compôs "Coração de Estudante"?', ['Chico Buarque', 'Milton Nascimento', 'Gonzaguinha', 'Ivan Lins'], 1, 'A canção virou hino da campanha das Diretas Já, em 1984.'],
    ['Qual álbum Caetano Veloso gravou durante o exílio em Londres?', ['Araçá Azul', 'Jóia', 'Transa', 'Bicho'], 2, 'Lançado em 1972, mistura português e inglês na mesma faixa.'],
    ['Qual multi-instrumentista alagoano é chamado de "o bruxo" da música brasileira?', ['Egberto Gismonti', 'Hermeto Pascoal', 'Naná Vasconcelos', 'Airto Moreira'], 1, 'Ele faz música com chaleiras, porcos e até com a água de um lago.'],
    ['Qual nota musical corresponde à letra A na notação americana?', ['dó', 'ré', 'mi', 'lá'], 3, 'Na cifra, A é lá, B é si, C é dó, e assim por diante.'],
    ['Quantas teclas tem um piano padrão?', ['76', '61', '88', '96'], 2, 'São sete oitavas completas mais algumas notas extras nos extremos.'],
    ['Qual compositor clássico continuou compondo mesmo depois de ficar surdo?', ['Ludwig van Beethoven', 'Johann Sebastian Bach', 'Richard Wagner', 'Robert Schumann'], 0, 'Ele começou a perder a audição por volta dos 26 anos.'],
  ],
  5: [
    ['Qual é considerado o primeiro samba gravado no Brasil, em 1917?', ['Aquarela do Brasil', 'Carinhoso', 'Pelo Telefone', 'Cidade Maravilhosa'], 2, 'A autoria foi registrada por Donga, mas a criação é atribuída a um grupo da casa da Tia Ciata.'],
    ['Quem compôs "Carinhoso"?', ['Noel Rosa', 'Ary Barroso', 'Ataulfo Alves', 'Pixinguinha'], 3, 'A melodia é de 1917, mas a letra, de Braguinha, só veio nos anos 1930.'],
    ['Qual compositor brasileiro escreveu "Odeon" e "Apanhei-te, Cavaquinho"?', ['Chiquinha Gonzaga', 'Ernesto Nazareth', 'Zequinha de Abreu', 'Pixinguinha'], 1, 'Ele tocava piano nas salas de espera dos cinemas do Rio de Janeiro.'],
    ['Quem compôs "Tico-Tico no Fubá"?', ['Zequinha de Abreu', 'Ernesto Nazareth', 'Pixinguinha', 'Jacob do Bandolim'], 0, 'O choro de 1917 virou sucesso internacional com Carmen Miranda.'],
    ['Quem compôs a ópera "Aida"?', ['Giuseppe Verdi', 'Giacomo Puccini', 'Gioachino Rossini', 'Vincenzo Bellini'], 0, 'A obra estreou no Cairo em 1871, encomendada pelo quediva do Egito.'],
    ['Quem compôs a ópera "La Traviata"?', ['Giacomo Puccini', 'Giuseppe Verdi', 'Richard Wagner', 'Georges Bizet'], 1, 'A ópera é baseada no romance "A Dama das Camélias".'],
    ['Qual compositor alemão criou o ciclo "O Anel do Nibelungo"?', ['Gustav Mahler', 'Richard Strauss', 'Johannes Brahms', 'Richard Wagner'], 3, 'São quatro óperas que, juntas, duram cerca de quinze horas.'],
    ['Como se chama o sistema de doze sons criado por Arnold Schoenberg?', ['Escala pentatônica', 'Sistema modal', 'Dodecafonismo', 'Cromatismo tonal'], 2, 'No dodecafonismo, nenhuma nota é mais importante que as outras.'],
    ['Qual termo musical indica um andamento muito rápido?', ['adágio', 'presto', 'andante', 'largo'], 1, 'Largo e adágio indicam andamentos lentos.'],
    ['Qual é o intervalo entre as notas dó e sol?', ['terça', 'quarta', 'quinta', 'sétima'], 2, 'A quinta justa é um dos intervalos mais consonantes da música ocidental.'],
    ['Qual sinal indica a altura das notas no início da pauta?', ['a clave', 'o compasso', 'a pausa', 'a ligadura'], 0, 'As mais comuns são a clave de sol, a de fá e a de dó.'],
    ['Quantas linhas tem uma pauta musical?', ['3', '4', '6', '5'], 3, 'As cinco linhas formam quatro espaços onde as notas são escritas.'],
    ['Qual grupo de rap paulistano lançou "Sobrevivendo no Inferno"?', ['Facção Central', 'RZO', 'SNJ', 'Racionais MC’s'], 3, 'O disco de 1997 é hoje leitura obrigatória no vestibular da Unicamp.'],
    ['Quem compôs "Travessia", canção que venceu um festival em 1967?', ['Milton Nascimento', 'Lô Borges', 'Beto Guedes', 'Toninho Horta'], 0, 'A parceria com Fernando Brant projetou o cantor mineiro nacionalmente.'],
    ['Em qual festival Caetano Veloso apresentou "Alegria, Alegria", em 1967?', ['Festival de Águas Claras', 'Festival de Woodstock', 'Festival de Música Popular Brasileira da TV Record', 'Festival de Olinda'], 2, 'Ele foi vaiado por usar guitarra elétrica e acompanhamento de banda de rock.'],
    ['Qual cantora portuguesa é conhecida como a "Rainha do Fado"?', ['Mariza', 'Amália Rodrigues', 'Dulce Pontes', 'Carminho'], 1, 'Sua morte, em 1999, levou Portugal a decretar três dias de luto nacional.'],
    ['Qual gênero musical tradicional argentino é dançado a dois?', ['tango', 'cueca', 'chacarera', 'zamba'], 0, 'O tango nasceu nos bairros portuários de Buenos Aires e Montevidéu.'],
    ['Qual cantor cubano ficou mundialmente famoso com o Buena Vista Social Club?', ['Celia Cruz', 'Ibrahim Ferrer', 'Tito Puente', 'Rubén Blades'], 1, 'Ele havia se aposentado e engraxava sapatos quando foi convidado para o projeto.'],
    ['Qual banda britânica lançou o álbum "OK Computer", em 1997?', ['Oasis', 'Blur', 'Radiohead', 'The Verve'], 2, 'O disco é apontado como um dos mais influentes do rock dos anos 1990.'],
    ['Qual rapper americano lançou "The Marshall Mathers LP"?', ['Jay-Z', 'Nas', '50 Cent', 'Eminem'], 3, 'Marshall Mathers é o nome verdadeiro do artista.'],
  ],
});
