import { montar } from './montar';

/** Tecnologia e Internet — 100 perguntas (20 por nível). */
export const perguntasTecnologia = montar('tecnologia', {
  1: [
    ['Qual empresa criou o sistema operacional Windows?', ['Apple', 'Google', 'Microsoft', 'IBM'], 2, 'A primeira versão do Windows foi lançada em 1985.'],
    ['Qual é o site de buscas mais usado do mundo?', ['Google', 'Bing', 'Yahoo', 'DuckDuckGo'], 0, 'A empresa nasceu em 1998, em uma garagem na Califórnia.'],
    ['Qual empresa fabrica o iPhone?', ['Samsung', 'Apple', 'Motorola', 'Xiaomi'], 1, 'O primeiro iPhone foi apresentado por Steve Jobs em 2007.'],
    ['O que significa "www" nos endereços de sites?', ['World Wide Wire', 'Web World Wide', 'Wide Web World', 'World Wide Web'], 3, 'A expressão foi criada por Tim Berners-Lee no fim dos anos 1980.'],
    ['Qual dispositivo é usado para digitar em um computador?', ['teclado', 'monitor', 'mouse', 'impressora'], 0, 'O layout QWERTY foi criado ainda no tempo das máquinas de escrever.'],
    ['Qual rede social ficou famosa por vídeos curtos com música e dança?', ['Facebook', 'LinkedIn', 'X', 'TikTok'], 3, 'O aplicativo é de origem chinesa e explodiu no mundo a partir de 2018.'],
    ['Qual é o aplicativo de mensagens mais usado no Brasil?', ['Telegram', 'Signal', 'WhatsApp', 'Messenger'], 2, 'O app está instalado em praticamente todos os celulares do país.'],
    ['Para que serve o mouse?', ['digitar textos', 'mover o cursor na tela', 'imprimir documentos', 'armazenar arquivos'], 1, 'O primeiro mouse, de 1964, era feito de madeira.'],
    ['Qual empresa é dona do YouTube?', ['Microsoft', 'Meta', 'Amazon', 'Google'], 3, 'A compra aconteceu em 2006, por 1,65 bilhão de dólares.'],
    ['Qual memória guarda dados temporariamente enquanto o computador está ligado?', ['HD', 'RAM', 'SSD', 'pendrive'], 1, 'Ao desligar o computador, o conteúdo da memória RAM se perde.'],
    ['O que é um e-mail?', ['uma mensagem eletrônica', 'um tipo de vírus', 'um programa de edição de fotos', 'um site de buscas'], 0, 'O símbolo @ separa o nome do usuário do domínio do provedor.'],
    ['Qual empresa desenvolve o sistema Android?', ['Apple', 'Microsoft', 'Google', 'Nokia'], 2, 'É o sistema operacional móvel mais usado no mundo.'],
    ['Qual é a função de um antivírus?', ['acelerar a internet', 'proteger contra programas maliciosos', 'aumentar a memória', 'imprimir arquivos'], 1, 'Ele identifica e bloqueia vírus, spywares e outros programas nocivos.'],
    ['Qual destes é um navegador de internet?', ['Word', 'Excel', 'Chrome', 'Photoshop'], 2, 'Firefox, Safari e Edge também são navegadores.'],
    ['Qual é a moeda digital mais conhecida do mundo?', ['Real digital', 'Pix', 'Ethereum', 'Bitcoin'], 3, 'Ela surgiu em 2009 e não é emitida por nenhum banco central.'],
    ['Qual sistema de pagamento instantâneo foi criado pelo Banco Central do Brasil?', ['Pix', 'Bitcoin', 'PayPal', 'TED'], 0, 'Lançado em novembro de 2020, funciona 24 horas por dia.'],
    ['Qual dispositivo serve para imprimir documentos?', ['impressora', 'scanner', 'monitor', 'roteador'], 0, 'O scanner faz o contrário: transforma papel em arquivo digital.'],
    ['Qual rede social foi comprada por Elon Musk em 2022?', ['Instagram', 'TikTok', 'Twitter', 'Snapchat'], 2, 'A plataforma foi rebatizada como X no ano seguinte.'],
    ['O que é o Wi-Fi?', ['uma marca de computador', 'uma tecnologia de rede sem fio', 'um tipo de cabo', 'um programa de edição'], 1, 'Ele permite conectar vários aparelhos à internet sem fios.'],
    ['Qual destes é um sistema operacional?', ['Chrome', 'Word', 'Excel', 'Linux'], 3, 'Windows, macOS e Android também são sistemas operacionais.'],
  ],
  2: [
    ['Quem fundou a Microsoft ao lado de Paul Allen?', ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Larry Page'], 1, 'A empresa foi criada em 1975, quando Gates tinha 19 anos.'],
    ['Quem fundou a Apple ao lado de Steve Wozniak?', ['Bill Gates', 'Jeff Bezos', 'Elon Musk', 'Steve Jobs'], 3, 'A empresa nasceu em 1976, na garagem da família Jobs.'],
    ['Quem criou o Facebook?', ['Mark Zuckerberg', 'Jack Dorsey', 'Kevin Systrom', 'Evan Spiegel'], 0, 'A rede começou em 2004 restrita a estudantes de Harvard.'],
    ['O que significa a sigla CPU?', ['Central de Programas Unificados', 'Controle Principal de Uso', 'Unidade Central de Processamento', 'Conexão Padrão Universal'], 2, 'É o componente que executa os cálculos e comandos do computador.'],
    ['Qual unidade mede a capacidade de armazenamento de arquivos?', ['hertz', 'volt', 'pixel', 'byte'], 3, 'Um caractere de texto simples ocupa normalmente um byte.'],
    ['Quantos megabytes tem aproximadamente um gigabyte?', ['100', '1024', '10', '500'], 1, 'Na base binária, cada unidade é 1.024 vezes maior que a anterior.'],
    ['Qual empresa desenvolve o navegador Chrome?', ['Microsoft', 'Mozilla', 'Google', 'Opera Software'], 2, 'Lançado em 2008, tornou-se o navegador mais usado do mundo.'],
    ['Qual linguagem é usada para estruturar páginas na web?', ['HTML', 'Python', 'SQL', 'C++'], 0, 'Ela define títulos, parágrafos, links e imagens de uma página.'],
    ['Qual empresa é dona do Instagram e do WhatsApp?', ['Meta', 'Google', 'Microsoft', 'Amazon'], 0, 'A empresa se chamava Facebook até a mudança de nome, em 2021.'],
    ['Quem fundou a Amazon?', ['Elon Musk', 'Bill Gates', 'Jeff Bezos', 'Larry Ellison'], 2, 'A empresa começou em 1994 como uma livraria online.'],
    ['O que é a "nuvem" em computação?', ['um tipo de vírus', 'um cabo de rede', 'um programa de imagens', 'servidores remotos que guardam dados pela internet'], 3, 'Google Drive, iCloud e Dropbox são exemplos de serviços em nuvem.'],
    ['Qual é a função do HD ou do SSD?', ['processar cálculos', 'armazenar arquivos de forma permanente', 'exibir imagens', 'conectar à internet'], 1, 'O SSD é mais rápido porque não tem partes móveis.'],
    ['Qual empresa desenvolveu o ChatGPT?', ['Google', 'Meta', 'OpenAI', 'IBM'], 2, 'O lançamento, em novembro de 2022, popularizou a IA generativa.'],
    ['Qual empresa criou o assistente de inteligência artificial Claude?', ['Anthropic', 'OpenAI', 'Google', 'Apple'], 0, 'A empresa foi fundada em 2021 e tem foco em segurança em IA.'],
    ['O que significa a sigla IA?', ['Internet Avançada', 'Inteligência Artificial', 'Informação Automática', 'Interface de Acesso'], 1, 'Em inglês, a sigla equivalente é AI.'],
    ['Qual é o console de videogame fabricado pela Sony?', ['Xbox', 'Switch', 'Atari', 'PlayStation'], 3, 'O primeiro PlayStation foi lançado em 1994.'],
    ['Qual empresa fabrica o console Switch?', ['Sony', 'Microsoft', 'Sega', 'Nintendo'], 3, 'O console híbrido funciona tanto na TV quanto de forma portátil.'],
    ['Qual é o jogo eletrônico mais vendido da história?', ['Tetris', 'Minecraft', 'GTA V', 'Wii Sports'], 1, 'O jogo de blocos passou de 300 milhões de cópias vendidas.'],
    ['Qual é o nome do encanador italiano criado pela Nintendo?', ['Mario', 'Sonic', 'Link', 'Kirby'], 0, 'Ele apareceu pela primeira vez no jogo Donkey Kong, em 1981.'],
    ['O que é fazer um "download"?', ['enviar um arquivo para a internet', 'apagar arquivos', 'baixar um arquivo da internet', 'compactar arquivos'], 2, 'A operação inversa se chama upload.'],
  ],
  3: [
    ['Em qual década surgiu a Arpanet, precursora da internet?', ['1960', '1950', '1980', '1990'], 0, 'A rede militar americana conectou quatro universidades em 1969.'],
    ['Quem criou a World Wide Web, em 1989?', ['Bill Gates', 'Vint Cerf', 'Tim Berners-Lee', 'Steve Jobs'], 2, 'Ele trabalhava no Cern, na Suíça, e liberou a tecnologia sem patentes.'],
    ['Qual protocolo é usado para transferir páginas na web?', ['FTP', 'SMTP', 'TCP', 'HTTP'], 3, 'A sigla significa "protocolo de transferência de hipertexto".'],
    ['O que significa a sigla URL?', ['Unidade de Rede Local', 'Localizador Uniforme de Recursos', 'União de Redes Livres', 'Usuário Registrado no Link'], 1, 'É o endereço que identifica um recurso específico na internet.'],
    ['Qual linguagem de programação tem uma cobra como símbolo?', ['Ruby', 'Java', 'Python', 'Perl'], 2, 'O nome, porém, é uma homenagem ao grupo humorístico Monty Python.'],
    ['Qual sistema traduz nomes de sites em endereços numéricos de IP?', ['DNS', 'VPN', 'DHCP', 'FTP'], 0, 'Sem ele, seria preciso decorar sequências de números para acessar sites.'],
    ['O que é um "bug" em programação?', ['um vírus de computador', 'um erro no funcionamento do programa', 'um tipo de memória', 'um cabo defeituoso'], 1, 'O termo se popularizou nos anos 1940, na era dos computadores gigantes.'],
    ['Quem é considerada a primeira programadora da história?', ['Grace Hopper', 'Hedy Lamarr', 'Margaret Hamilton', 'Ada Lovelace'], 3, 'Em 1843, ela escreveu um algoritmo para a máquina analítica de Babbage.'],
    ['Qual foi o primeiro computador eletrônico de grande porte, apresentado em 1946?', ['UNIVAC', 'ENIAC', 'Colossus', 'Mark I'], 1, 'Ele pesava 30 toneladas e ocupava uma sala inteira.'],
    ['Qual cientista britânico decifrou a máquina Enigma e é considerado pai da computação?', ['John von Neumann', 'Claude Shannon', 'Charles Babbage', 'Alan Turing'], 3, 'Seu trabalho teria encurtado a Segunda Guerra Mundial em anos.'],
    ['O que significa "open source"?', ['software pago', 'software em fase de testes', 'software de código aberto', 'software desatualizado'], 2, 'Qualquer pessoa pode ver, alterar e redistribuir o código.'],
    ['Qual sistema operacional livre foi criado por Linus Torvalds?', ['Linux', 'Unix', 'MS-DOS', 'macOS'], 0, 'Ele começou o projeto em 1991, ainda como estudante na Finlândia.'],
    ['O que é phishing?', ['um jogo online', 'um tipo de memória', 'um cabo de rede', 'um golpe que finge ser fonte confiável para roubar dados'], 3, 'Costuma chegar por e-mail ou mensagem com links falsos.'],
    ['Qual tecnologia conecta dispositivos sem fio a curta distância, como fones de ouvido?', ['Wi-Fi', 'Bluetooth', 'GPS', 'RFID'], 1, 'O nome homenageia um rei viking dinamarquês do século X.'],
    ['O que significa 5G?', ['a quinta geração das redes móveis', 'cinco gigabytes de memória', 'cinco gigahertz de frequência', 'um tipo de cabo de fibra'], 0, 'A tecnologia promete menor latência e mais dispositivos conectados.'],
    ['Qual empresa lançou o computador pessoal que virou padrão do mercado nos anos 1980?', ['Apple', 'Microsoft', 'IBM', 'Commodore'], 2, 'O IBM PC, de 1981, definiu a arquitetura seguida pela indústria.'],
    ['Qual é a função de uma GPU?', ['armazenar dados', 'conectar à internet', 'processar gráficos e cálculos paralelos', 'resfriar o computador'], 2, 'Hoje ela também é essencial para treinar modelos de inteligência artificial.'],
    ['O que é o código binário?', ['um sistema que usa apenas 0 e 1', 'um tipo de vírus', 'uma linguagem de programação', 'um formato de senha'], 0, 'Toda informação em um computador é representada por sequências de bits.'],
    ['Qual rede social é voltada para currículos e contatos profissionais?', ['Instagram', 'TikTok', 'Pinterest', 'LinkedIn'], 3, 'A plataforma foi lançada em 2003 e hoje pertence à Microsoft.'],
    ['O que é um algoritmo?', ['um tipo de computador', 'uma sequência finita de passos para resolver um problema', 'um vírus', 'uma rede social'], 1, 'Uma receita de bolo é um bom exemplo de algoritmo do cotidiano.'],
  ],
  4: [
    ['Qual é a lei brasileira que regula o tratamento de dados pessoais?', ['Marco Civil da Internet', 'Lei Carolina Dieckmann', 'Lei do Software', 'LGPD'], 3, 'A Lei Geral de Proteção de Dados entrou em vigor em 2020.'],
    ['Qual lei de 2014 estabeleceu princípios para o uso da internet no Brasil?', ['LGPD', 'Marco Civil da Internet', 'Lei do Bem', 'Lei Geral de Telecomunicações'], 1, 'Ela consagrou a neutralidade de rede e a privacidade dos usuários.'],
    ['O que é uma VPN?', ['um antivírus', 'um navegador', 'uma rede privada virtual que protege a conexão', 'um tipo de memória'], 2, 'Ela cria um túnel criptografado entre o dispositivo e a internet.'],
    ['Qual é a diferença entre HTTP e HTTPS?', ['O HTTPS criptografa a comunicação', 'O HTTP é mais rápido', 'O HTTPS é pago', 'Não existe diferença'], 0, 'O cadeado no navegador indica que a conexão é segura.'],
    ['Qual estrutura de dados funciona no esquema "o último a entrar é o primeiro a sair"?', ['fila', 'pilha', 'lista ligada', 'árvore binária'], 1, 'A fila funciona ao contrário: o primeiro a entrar é o primeiro a sair.'],
    ['Qual arquitetura de rede neural está por trás dos modelos modernos de IA generativa?', ['RNN', 'CNN', 'Transformer', 'Perceptron'], 2, 'Ela foi apresentada em 2017 no artigo "Attention Is All You Need".'],
    ['O que é aprendizado de máquina?', ['técnica em que o sistema aprende padrões a partir de dados', 'um robô industrial', 'uma linguagem de programação', 'um sistema operacional'], 0, 'É um dos campos centrais da inteligência artificial moderna.'],
    ['Qual organização desenvolve o navegador Firefox?', ['Google', 'Microsoft', 'Apple', 'Mozilla'], 3, 'É um projeto de código aberto mantido por uma fundação sem fins lucrativos.'],
    ['Qual linguagem é executada no navegador para tornar páginas interativas?', ['Python', 'PHP', 'JavaScript', 'C#'], 2, 'Ela foi criada em apenas dez dias, em 1995.'],
    ['Qual é a relação entre Java e JavaScript?', ['São linguagens diferentes, apesar do nome parecido', 'JavaScript é a versão nova do Java', 'Java é escrito em JavaScript', 'São a mesma linguagem'], 0, 'O nome foi uma jogada de marketing na época do lançamento.'],
    ['O que é o código-fonte de um programa?', ['o arquivo executável', 'o texto escrito pelo programador', 'o manual do usuário', 'o banco de dados'], 1, 'Ele precisa ser compilado ou interpretado para virar um programa funcional.'],
    ['Qual foi um dos primeiros grandes portais de internet do Brasil, lançado em 1996?', ['Terra', 'Globo.com', 'iG', 'UOL'], 3, 'O Universo Online nasceu de uma parceria entre a Folha e o Grupo Abril.'],
    ['O que é blockchain?', ['um registro distribuído e encadeado de transações', 'um tipo de antivírus', 'um cabo de fibra óptica', 'uma rede social'], 0, 'Cada bloco guarda a impressão digital do bloco anterior, dificultando fraudes.'],
    ['Sob qual pseudônimo foi publicado o projeto original do Bitcoin?', ['Vitalik Buterin', 'Elon Musk', 'Hal Finney', 'Satoshi Nakamoto'], 3, 'A identidade real por trás do nome nunca foi confirmada.'],
    ['Qual foi o primeiro satélite artificial lançado ao espaço?', ['Explorer 1', 'Sputnik 1', 'Vanguard 1', 'Telstar'], 1, 'Lançado pela União Soviética em 1957, deu início à corrida espacial.'],
    ['Qual empresa lançou o primeiro telefone celular comercial, em 1983?', ['Nokia', 'Ericsson', 'Motorola', 'Siemens'], 2, 'O aparelho pesava quase um quilo e custava o equivalente a um carro popular.'],
    ['Em qual unidade é medida a frequência de um processador?', ['byte', 'hertz', 'pixel', 'watt'], 1, 'Processadores atuais operam na casa dos gigahertz, bilhões de ciclos por segundo.'],
    ['O que significa a sigla IoT?', ['Internet Ótima Total', 'Índice Operacional de Tráfego', 'Interface Online de Transmissão', 'Internet das Coisas'], 3, 'Refere-se a objetos do dia a dia conectados à rede, como geladeiras e lâmpadas.'],
    ['Qual foi a primeira mensagem transmitida pela Arpanet, em 1969?', ['HELLO', 'TEST', 'LO', 'ARPA'], 2, 'O sistema travou no meio da palavra "LOGIN", enviando apenas as duas letras.'],
    ['Qual robô da Nasa explora Marte desde 2021?', ['Perseverance', 'Curiosity', 'Spirit', 'Opportunity'], 0, 'Ele levou junto o helicóptero Ingenuity, primeiro a voar em outro planeta.'],
  ],
  5: [
    ['Qual teste avalia se uma máquina pode ser confundida com um ser humano em uma conversa?', ['Teste de Moore', 'Teste de Shannon', 'Teste de Turing', 'Teste de Von Neumann'], 2, 'Foi proposto em 1950, no artigo "Computing Machinery and Intelligence".'],
    ['Qual lei empírica prevê a duplicação do número de transistores em um chip a cada dois anos?', ['Lei de Metcalfe', 'Lei de Amdahl', 'Lei de Kryder', 'Lei de Moore'], 3, 'Foi formulada em 1965 por um dos fundadores da Intel.'],
    ['Qual matemático húngaro-americano definiu a arquitetura usada até hoje nos computadores?', ['Alan Turing', 'John von Neumann', 'Claude Shannon', 'Norbert Wiener'], 1, 'Nela, programa e dados ficam na mesma memória.'],
    ['Quem é considerado o pai da teoria da informação?', ['Claude Shannon', 'Alan Turing', 'Ada Lovelace', 'Charles Babbage'], 0, 'Foi ele quem propôs o bit como unidade básica de informação, em 1948.'],
    ['Qual inventor projetou a "máquina analítica" no século XIX?', ['Charles Babbage', 'Blaise Pascal', 'Gottfried Leibniz', 'Herman Hollerith'], 0, 'A máquina nunca foi concluída, mas já previa memória e unidade de processamento.'],
    ['Qual foi a primeira linguagem de programação de alto nível amplamente adotada?', ['COBOL', 'Fortran', 'ALGOL', 'Lisp'], 1, 'Criada pela IBM em 1957, era voltada para cálculos científicos.'],
    ['Qual cientista liderou o software de navegação das missões Apollo?', ['Grace Hopper', 'Katherine Johnson', 'Ada Lovelace', 'Margaret Hamilton'], 3, 'O código impresso que ela escreveu empilhava mais alto que ela própria.'],
    ['Quem popularizou o termo "bug" ao encontrar um inseto preso em um computador?', ['Alan Turing', 'John Mauchly', 'Grace Hopper', 'Konrad Zuse'], 2, 'A mariposa encontrada em 1947 foi colada no diário de bordo da máquina.'],
    ['Qual protocolo forma, junto com o IP, a base do funcionamento da internet?', ['HTTP', 'TCP', 'SMTP', 'UDP'], 1, 'Ele garante que os pacotes cheguem completos e na ordem correta.'],
    ['Qual empresa lançou o primeiro microprocessador comercial, o 4004, em 1971?', ['AMD', 'Motorola', 'Intel', 'Texas Instruments'], 2, 'O chip tinha 2.300 transistores e foi projetado para uma calculadora.'],
    ['O que caracteriza a computação quântica?', ['o uso de qubits, que exploram superposição e emaranhamento', 'o processamento em nuvem', 'o uso de vários processadores em paralelo', 'a transmissão por fibra óptica'], 0, 'Um qubit pode representar 0 e 1 ao mesmo tempo, ampliando o espaço de cálculo.'],
    ['Qual algoritmo de ordenação usa a estratégia de dividir a lista em torno de um pivô?', ['bubble sort', 'insertion sort', 'merge sort', 'quicksort'], 3, 'Na média, sua complexidade é O(n log n).'],
    ['Qual é a base do sistema hexadecimal?', ['2', '8', '10', '16'], 3, 'Ele usa os algarismos de 0 a 9 e as letras de A a F.'],
    ['Quantos bits formam um byte?', ['8', '4', '16', '32'], 0, 'Com 8 bits é possível representar 256 valores diferentes.'],
    ['Qual empresa criou a linguagem de programação Java?', ['Microsoft', 'IBM', 'Sun Microsystems', 'Borland'], 2, 'A Sun foi comprada pela Oracle em 2010, que passou a manter a linguagem.'],
    ['Qual foi o primeiro navegador gráfico a popularizar a web, em 1993?', ['Netscape Navigator', 'Mosaic', 'Internet Explorer', 'Opera'], 1, 'Sua equipe criaria depois o Netscape Navigator.'],
    ['Qual foi a primeira rede social a ultrapassar 1 bilhão de usuários?', ['Facebook', 'MySpace', 'Orkut', 'Twitter'], 0, 'A marca foi atingida em 2012, oito anos após a fundação.'],
    ['Qual rede social fez enorme sucesso no Brasil nos anos 2000 e foi encerrada em 2014?', ['MySpace', 'Orkut', 'Fotolog', 'Sonico'], 1, 'Criada por um engenheiro do Google, chegou a ter maioria de usuários brasileiros.'],
    ['Qual empresa comprou o LinkedIn, em 2016?', ['Google', 'Meta', 'Microsoft', 'Salesforce'], 2, 'O negócio foi fechado por cerca de 26 bilhões de dólares.'],
    ['O que é um ataque DDoS?', ['roubo de senhas por e-mail', 'criptografia de arquivos para pedir resgate', 'falsificação de remetente', 'sobrecarga de um servidor com acessos simultâneos'], 3, 'O ataque costuma usar milhares de máquinas infectadas ao mesmo tempo.'],
  ],
});
